### ISSUE TITLE
Equinox not part of the Eclipse IDE SDK Oomph setup?

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.releng.aggregator#1005]
I'm not sure if I messed up my install or if it is intentional, but I noticed that Equinox itself seems not be in my sdk workspace installed from here:

https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#create-an-eclipse-development-environment

So i tried to perform the setup tasks to maybe get it in, but still seems missing, the I noticed there is also an "Import Projects" item and then I see this

![grafik](https://user-images.githubusercontent.com/1331477/229778673-f122d51a-becf-4e13-b91f-625cf3bc0145.png)

so can I simply activate the "core" or do I mess up my install then, and even more interesting should equinox core have been included already?

**Comment by HannesWell** [comment]
> so can I simply activate the "core" or do I mess up my install then, and even more interesting should equinox core have been included already?

Importing projects in general does not influence your installation, unless the setup of that project contains some P2Director tasks that install new Plugins/Features, but the equinox-core setup does not have an extra P2Director task.

The configuration you mentioned includes the equinox-core setup:
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/oomph/PlatformSDKConfiguration.setup#L174-L175

Therefore I assume something went wrong at your local computer.

**Comment by merks** [comment]
For me it's included already:

![image](https://user-images.githubusercontent.com/208716/230002329-79d7a431-79cf-441f-a017-164f2b1c4e50.png)

And it's indeed defined that way in the configuration:

![image](https://user-images.githubusercontent.com/208716/230002575-c9b56af8-30b9-4cb3-bed6-2c3144d43830.png)

**Comment by laeubi** [comment]
Is there a way to reset the setup without starting with a complete empty folder?

**Comment by merks** [comment]
I'm not sure what you mean by "reset".  In general a Configuration is processed by the Installer.  The Installation of the Configuration, chooses the Product Version on the first page and is copied to the Installation.setup of the installation that's created.  The Workspace of the Configuration chooses Project Streams on the second page and is copied to the Workspace.setup of the workspace that's created.   You can edit the Installation.setup and the Workspace.setup, and importing Setup Projects will add additional Project Stream to the Workspace.setup, which seems like the only thing you want in this case, i.e., to include the equinox core.... 

It is possible to use the Installer with a Configuraiton to "overwrite" an existing location.  All the clones will already be there so such tasks don't need to perform again...

**Comment by laeubi** [comment]
Yes its more that I want to keep the clones (as I otherwise need to configure the forks again and loose my local branches), currently I do "perform setup tasks" and this often seem to fetch missing stuff, but it seems I somehow have removed equinox and can't get it back again ...

**Comment by merks** [comment]
Use Import Projects to add Project setups to the workspace (Workspace.setup).

![image](https://user-images.githubusercontent.com/208716/230012951-94657fbd-3911-4155-87a7-bb2592a2d239.png)
