### ISSUE TITLE
Migrate p2 to GitHub

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-platform/eclipse.platform.releng.aggregator#102]

**Comment by mickaelistria** [comment]
Opened https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/984

**Comment by mickaelistria** [comment]
Submitted PR #122 to continue the migration

**Comment by merks** [comment]
I think this is done now too then, right?

**Comment by mickaelistria** [comment]
That's not complete yet, some more steps of the workflow defined in #24 needs to be done/verified.
At the moment, i'm waiting for a happy build result from CI to merge the change in aggregator.

**Comment by mickaelistria** [comment]
An infra issue is actually blocking: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/984#note_616989

**Comment by mickaelistria** [comment]
We can now close, everything is working as expected and the only remaining details are better tracked directly in p2 tracker.
