### ISSUE TITLE
[21] Y-Build for Java 21

### ISSUE THREAD

**Issue by jarthana** [eclipse-platform/eclipse.platform.releng.aggregator#1028]
We need to start making Y builds so that jdt.debug and jdt.ui jobs can run tests reliably.

@MohananRahul Can you try creating this?

Copying @sravanlakkimsetti

**Comment by MohananRahul** [comment]
@jarthana @mpalat I will create it.

**Comment by jarthana** [comment]
I got the Y build nice and running. Thanks Rahul!
