### ISSUE TITLE
SDK build timeouts

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1038]
Something changed in the infrastructure OR in our build/tycho/maven/whatever.
Usually SDK builds run for ~45 to 90 minutes.
However since monday we see huge timeouts.

- https://ci.eclipse.org/releng/job/Builds/job/I-build-4.28/72/ took **9 hour 30 minutes**!!! 
![image](https://user-images.githubusercontent.com/964108/233275059-9b260a8b-d203-468e-b324-2419db8d06bc.png)
- https://ci.eclipse.org/releng/job/Builds/job/I-build-4.28/74/ build was aborted as it run over 6 hours!

**Comment by cdietrich** [comment]
we see a lot of timeouts in xtext ci as well recently. had created https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2952

**Comment by laeubi** [comment]
It was reported that maven central had issues:
https://news.ycombinator.com/item?id=35635538

**Comment by akurtakov** [comment]
Maven central has been fixed.
