### ISSUE TITLE
Migrate javax.inject and javax.annotations to Jakarta

### ISSUE THREAD

**Issue by HannesWell** [eclipse-platform/eclipse.platform.releng.aggregator#1056]
This is an umbrella issue to coordinate and collect the migration steps of the `javax.inject` and `java.annotations` bundles to Jakarta.

- [x] Migrate to the javax.inject|annotations bundles provided by Jakarta but with unchanged package names
    1. Only use Import-Package with a closed version range to reference `javax.inject|annotations` in Plugin Manifests.
        - Simplifies the exchange of the providing bundle
        - Additionally prevents possible split-package problems with the `javax.annotation` package provided by the `com.google.code.findbugs/jsr305` artifact. It is not used within the Eclipse platform but it guards down-stream consumers that could have it in their TP. E.g. Guava has a transitive dependency on it, so there is some chance it ends up in a TP if one is not careful.
        - PRs
          - https://github.com/eclipse-pde/eclipse.pde/pull/591
          - https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1019
          - https://github.com/eclipse-platform/eclipse.platform/pull/431
          - https://github.com/eclipse-platform/eclipse.platform.debug/pull/133
          - https://github.com/eclipse-platform/eclipse.platform.ua/pull/121
          - https://github.com/eclipse-platform/eclipse.platform.ui/pull/738

    2. Refactor code to not relay on the bundle-symbolicName of the javax-annotations provider bundle so that it can be easaly exchanged
        - https://github.com/eclipse-platform/eclipse.platform.ui/pull/745
        - https://github.com/eclipse-platform/eclipse.platform.common/pull/145
        - https://github.com/eclipse-pde/eclipse.pde/pull/593
      
    4. Replace javax-artifacts in the TP with the ones provided by Jakarta
        - https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1057 
        - https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1059

- [x] Support Annotations from `jakarta.inject|annotations` in all processors in the Eclipse platform
    - Add new jakarta.inject|annotations bundles to TP which version?
      - jakarta.inject:jakarta.inject-api:2.0.1
      - jakarta.annotation:jakarta.annotation-api:2.1.1
    - Support Jakarta Annotations in the E4 Injector (will create a dedicated issue):
      - https://github.com/eclipse-platform/eclipse.platform/pull/696
      - https://github.com/eclipse-platform/eclipse.platform/pull/792
      - https://github.com/eclipse-platform/eclipse.platform/pull/820
    - Are there more processors in the Eclipse-Platform?
    Looks like there are not more.

- [x] Migrate all uses of the `javax.inject|annotations`  packages to `jakarta.inject|annotations`
  - https://github.com/eclipse-platform/eclipse.platform/pull/696
  - https://github.com/eclipse-platform/eclipse.platform/pull/789
  - https://github.com/eclipse-platform/eclipse.platform/pull/791
  - https://github.com/eclipse-platform/eclipse.platform.ui/pull/1255
  - https://github.com/eclipse-platform/eclipse.platform.swt/pull/852
  - https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1527
  - https://github.com/eclipse-pde/eclipse.pde/pull/833

I'll start to work on the steps and update this initial comment with the created PRs.

**Comment by HannesWell** [comment]
The javax.inject/annotation bundles are also contained in some products and one feature. I think we can simply remove them there.
In the PDE the javax.inject/annotation bundle are also referenced as Packages and `as Plugins` in the E4 templates.
At least the parts where they are referenced as Plugins should be rewritten to use packages immediately.
And later, when the transition to the jakarta annotations is possible the package imports in the templates have to be adjusted too.

**Comment by HannesWell** [comment]
Part one is completed, all javax-bundles from Orbit are now replaced by their jakarta counterparts (or removed).

Since we are already relatively late in the release cycle I plan to postpone adding support for jakarta-annotations in the E4-injector. One reasons is we have only relatively little time to fix potential regressions and the other one is that I have other things on my list, that are more important to me.
But I have the intention to continue with that in the beginning of the next cycle.

**Comment by iloveeclipse** [comment]
@HannesWell : there is a broken PDE test expectation now (platform independent), see for example https://download.eclipse.org/eclipse/downloads/drops4/I20230509-1800/testresults/html/org.eclipse.pde.ui.tests_ep428I-unit-cen64-gtk3-java20_linux.gtk.x86_64_20.html



`org.eclipse.pde.ui.tests.launcher.FeatureBasedLaunchTest | testGetMergedBundleMap_autostartLevels`

```
Expecting map:
....
but could not find the following map entries:
["javax.inject"="default:default"]
```

I assume this is expected, could you please adapt test expectations if that is the case?

**Comment by HannesWell** [comment]
Thanks for the heads up.

> I assume this is expected, could you please adapt test expectations if that is the case?
>
Now that you mention it I remember this, but in between I forgot it. But I'm happy it is only one location 😅
I'll fix it this evening (a.t.m. I'm experiencing 502 Bad Gateway responses which makes it impossible to update my TP).

**Comment by iloveeclipse** [comment]
> I'm experiencing 502 Bad Gateway responses

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3130

**Comment by HannesWell** [comment]
With https://github.com/eclipse-platform/eclipse.platform/pull/696 the E4 injector now supports the new jakarta-annotations.
That PR also migrates all occurrences for eclipse.platform.
So the only remaining step to resolve this is to migrate all other Eclipse TLPs to the jakarta annotations.
The first step in the intial comment probably gives a good hint where to look, alternativly one can just search all sub-modules of the aggreator for `javax.inject` or `javax.annotation`.
Unless somebody else does it I'll try to provide PRs as time permits.

**Comment by HannesWell** [comment]
@laeubi or @akurtakov is there already an N&N entry for this and the deprecation note for javax-annotation support? https://github.com/eclipse-platform/eclipse.platform/pull/696#issuecomment-1760469327

**Comment by HannesWell** [comment]
Once the following PRs are submitted I consider the migration as completed:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1509
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1510
- https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/79

Should we already open an issue in eclipse.platform about the eventual removal of support for javax-annotation in the injector?

**Comment by akurtakov** [comment]
Is there anything still to be done here?

**Comment by HannesWell** [comment]
> Is there anything still to be done here?

With https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1510 being merged, I now consider this as resolved.
