### ISSUE TITLE
Delete now obsolete Jobs in Releng Jenkins

### ISSUE THREAD

**Issue by HannesWell** [eclipse-platform/eclipse.platform.releng.aggregator#1060]
PR https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/657 made the following Jenkins jobs obsolete (for the mater, it was argued that they are a.t.m. needed for backports)
- https://ci.eclipse.org/releng/job/deploy-eclipse-platform-parent-pom/
- https://ci.eclipse.org/releng/job/deploy-eclipse-sdk-target-pom/

With https://github.com/eclipse-platform/eclipse.platform.swt/pull/514 all jobs in the following view are obsolete
- https://ci.eclipse.org/releng/view/SWT%20Natives/

With https://github.com/eclipse-equinox/equinox/pull/603 all jobs in the following view are also obsolete:
- https://ci.eclipse.org/releng/view/Launcher/

On the long run those jobs should be deleted to not litter the Jenkins with abandoned jobs.
The main question is when?

This at least serves as a reminder.

**Comment by HannesWell** [comment]
PR #657 is now over a year old and I wonder if we can now reconsider if the two deploy jobs for the parent-pom and sdk-target-pom can be deleted?
@sravanlakkimsetti how for many releases/years back do you or your colleges plan to do maintenance work?
If you need the deployment for even older realeses one could backport the change on demand to deploy as part of those maintenance branch builds?

> With [eclipse-platform/eclipse.platform.swt#514](https://github.com/eclipse-platform/eclipse.platform.swt/pull/514) all jobs in the following view are obsolete
> 
>     * https://ci.eclipse.org/releng/view/SWT%20Natives/

Furthermore I wonder if we can now remove all these obsolete SWT-native jobs? Or are they used to back-port changes in the SWT natives if necessary, although I'm in doubt that this would work (but I haven't looked at these jobs in a while).
@akurtakov you ran the `SWT-Increment_if_needed` about a month ago, do you think these jobs should be kept?

**Comment by akurtakov** [comment]
Cleaning up stale jobs is fine by me and people had enough time to react if these were really needed so please proceed with the cleanup.

**Comment by HannesWell** [comment]
@sravanlakkimsetti do you want to comment on this one?

**Comment by HannesWell** [comment]
Now that https://github.com/eclipse-equinox/equinox/pull/603 has been submitted all jobs in the launcher group are obsolete as well:
https://ci.eclipse.org/releng/view/Launcher/

Once the new Equinox pipeline has proofed to work well, I'll delete all manually created jobs of the launcher jobs, unless somebody objects. I think shortly after the next release, so in the beginning of the 4.33 cycle would be a good target for that.

**Comment by HannesWell** [comment]
> > * https://ci.eclipse.org/releng/job/deploy-eclipse-platform-parent-pom/
> > * https://ci.eclipse.org/releng/job/deploy-eclipse-sdk-target-pom/
> 
> These jobs have already been deleted by somebody else.

I have to correct this statement, these jobs just have been renamed. So the same applies.
If there are no objects by Friday this week, I'll continue to delete the following jobs:
- https://ci.eclipse.org/releng/job/Releng/job/deployPlatformParentPom/
- https://ci.eclipse.org/releng/job/Releng/job/deploySdkPom/

And will remove them from the seed job via https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2139.

**Comment by HannesWell** [comment]
All seven jobs in the `SWT Natives` view and the view itself are deleted.
All eight jobs in the `Launcher` view and the view itself are deleted.

The jobs `deploySdkPom` and `deployPlatformParentPom` are deleted.

With that this issue is completed. Although there are probably more jobs that can be removed, but that's for another issue.
