### ISSUE TITLE
Crash eclipse-cpp-2022-12(4.26)

### ISSUE THREAD

**Issue by fuya-rule** [eclipse-platform/eclipse.platform.releng.aggregator#1063]
launch eclipse crash, no output log and error dialog:
![209](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/48354408/2f71c91f-1baf-4c1e-966e-792abae22485)

eclise info: 
eclipse version: 2022-12(4.26)
cdt version: default 11.0 change to 10.7.1
os : CentOS 7

**Comment by iloveeclipse** [comment]
Please if you test with latest 4.27 version, provide workspace error log and if entire Eclipse crashes, Java crash log and crash file (usually reported to console from which Eclipse was started).

**Comment by akurtakov** [comment]
As there is no further info from reporter for testing with recent release (4.29 now should be tested!) I'm closing this one.
