### ISSUE TITLE
Security Best Practices

### ISSUE THREAD

**Issue by ghost** [eclipse-platform/eclipse.platform.releng.aggregator#1068]
Hi,

As a member of the Security Team from the Eclipse Foundation, we used a tools [Scorecard](https://github.com/ossf/scorecard) and [StepSecurity](https://www.stepsecurity.io/) to analyze this repo  in order to push a pull request that cover some or all the following best practices below:
* Apply least privilege principle to [GITHUB_TOKEN](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/)
* Add or fine tune the use of [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates)
* Pin actions to a [full length commit SHA](https://michaelheap.com/ensure-github-actions-pinned-sha/)

As a result, You will see a PR coming from [StepSecurity](https://www.stepsecurity.io/) to help to implement those fixes above which will cover a list of points below identified detected:
* Apply least privilege principle to [GITHUB_TOKEN](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/) for files [.github/workflows/verifyFreezePeriod.yml](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/.github/workflows/verifyFreezePeriod.yml), [.github/workflows/checkMergeCommits.yml](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/.github/workflows/checkMergeCommits.yml), [.github/workflows/prepareRelease.yml](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/.github/workflows/prepareRelease.yml) 
* Add or fine tune the use of [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates)
* Pin Actions to a full length commit SHA for files [.github/workflows/verifyFreezePeriod.yml](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/.github/workflows/verifyFreezePeriod.yml), [.github/workflows/checkMergeCommits.yml](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/.github/workflows/checkMergeCommits.yml), [.github/workflows/prepareRelease.yml](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/.github/workflows/prepareRelease.yml)

Please don’t hesitate and reach out if there is something unclear above.

Kind Regards,
Francisco Perez

**Comment by fperezel** [comment]
Closing due to already merged the code pushed

**Comment by HannesWell** [comment]
@fperezel pinning the GH actions to a particular commit-id is of course beneficial in terms of preventing of unknown changes.
However I wonder how we can get updates to new versions once they are released? Does your tool handle that as well or will another tool like dependabot take care of this?
Using a resent version of actions is also important for security, I assume.

**Comment by fperezel** [comment]
Hi @HannesWell , StepSecurity, as far as, we have checked StepSecurit detects line similar to `actions/github-script@v6` and propose the equivalent with the hash each time that is executed. Unfortunately, I am unclear about StepSecurity could alert about new versions as dependabot. 

Please let me check out that and I will come back to you clarifying this. Sorry about that

Thanks,

**Comment by fperezel** [comment]
Hi @HannesWell ,

I have already asked about the possibility that StepSecurity may alert about new versions on those Pin action already applied.
 
However, my understanding after double check this PR. The alerts about new version for new versions for those docker file that have proposed a pint action may come from dependanbot because dependabot wasn't monitoring dockerfile configuration.

Finally, as long as I have clarified if StepSecurity has the capacity of alerting I will let you know.

Thanks,
