### ISSUE TITLE
Migrate releng wiki pages

### ISSUE THREAD

**Issue by trancexpress** [eclipse-platform/eclipse.platform.releng.aggregator#1084]
See: https://wiki.eclipse.org/Category:Eclipse_Platform_Releng

From what I can tell, none of those pages are migrated yet. In particular there is the platform build page that is essential: https://wiki.eclipse.org/Platform-releng/Platform_Build

Wiki is currently: https://github.com/eclipse-platform/eclipse.platform.releng/wiki

**Comment by trancexpress** [comment]
I've pushed the migrated pages, I've pruned some of the outdated information about Gerrit. But not all of it, and I'm fairly certain there is more outdated information in the pages.

Anyone who can take a look and delete whatever is outdated?

**Comment by trancexpress** [comment]
The platform build page is now: https://github.com/eclipse-platform/eclipse.platform.releng/wiki/Platform-Build

**Comment by iloveeclipse** [comment]
Correct url is: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/wiki/Platform-Build
