### ISSUE TITLE
Acknowledgment for 4.28

### ISSUE THREAD

**Issue by MohananRahul** [eclipse-platform/eclipse.platform.releng.aggregator#1088]

**Comment by MohananRahul** [comment]
https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/37

**Comment by MohananRahul** [comment]
Completed

**Comment by BeckerWdf** [comment]
In the list of names for platform there are duplicated names (e.g. my name "Matthias Becker" is stated twice).

**Comment by MohananRahul** [comment]
> In the list of names for platform there are duplicated names (e.g. my name "Matthias Becker" is stated twice).

fixed
