### ISSUE TITLE
Clean up intermediate artifacts (milestones, I-builds and old releases)

### ISSUE THREAD

**Issue by MohananRahul** [eclipse-platform/eclipse.platform.releng.aggregator#1150]
Done in below job
https://ci.eclipse.org/releng/job/Releng/job/cleanupReleaseArtifacts/2/

**Comment by laeubi** [comment]
@MohananRahul in this repo (and probabbly others) I still see unclosed milestone [4.28](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/milestone/31):

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/milestones

**Comment by MohananRahul** [comment]
@laeubi I am new in Eclipse , So could you please advise me what I need to follow to close milestone?

**Comment by laeubi** [comment]
It should be here (not sure if there is also a script @sravanlakkimsetti ?!?):

![grafik](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/1331477/9f652802-aff5-41f1-beac-82876c4a35c0)

**Comment by iloveeclipse** [comment]
Note: before closing milestones with linked **opened** issues, linked **opened** issues should ideally be checked if they are left open by mistake or should be moved to other milestone etc.
