### ISSUE TITLE
Promote next ecj build so it can be used to build SDK

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1184]
See discussion on https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1139

The latest compiler change will lead to ecj generating different bytecode for almost every bundle we build in SDK.

Such a basic change should be tested as early as possible, so we should make sure the ecj build with the next SDK build is promoted so it can be used to build SDK **before** M1.

This will also mean, we will have to "touch" lot of bundles.

**Comment by laeubi** [comment]
> This will also mean, we will have to "touch" lot of bundles.

The good news is that I already have touched a lot of bundles already and some more bumps will come for the UI in another PR.

For the remaining ones, one can checkout the repository and run the following command in a loop until the build succeeds and commit the resulting changes:

`mvn clean verify org.eclipse.tycho:tycho-versions-plugin:4.0.0-SNAPSHOT:bump-versions -Dtycho.bump-versions.increment=100 -DskipTests -Dcompare-version-with-baselines.skip=false`

**Comment by akurtakov** [comment]
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/RELEASE.md#milestone-week describes how to update ecj compiler

**Comment by iloveeclipse** [comment]
> For the remaining ones, one can checkout the repository and run the following command in a loop until the build succeeds and commit the resulting changes:

I don't think this will do it, because bundles with the **already** bumped version will also report problems (different artifacts produced from same code). 

So we will have to physically "touch" files in bundles by changing / creating "forceQualifierUpdate.txt" files.

@akurtakov : please correct me if I'm wrong.

**Comment by laeubi** [comment]
> I don't think this will do it, because bundles with the already bumped version will also report problems (different artifacts produced from same code).

I think `forceQualifierUpdate.txt` is only required if we actually want the changes to be included because otherwise it will be replaced with the old compiled versions but I we will see what happens after activating new ECJ version.

**Comment by akurtakov** [comment]
If only compiler change forcecontextqualifier would be needed yes.

**Comment by HannesWell** [comment]
> > I don't think this will do it, because bundles with the already bumped version will also report problems (different artifacts produced from same code).
> 
> I think `forceQualifierUpdate.txt` is only required if we actually want the changes to be included because otherwise it will be replaced with the old compiled versions but I we will see what happens after activating new ECJ version.

The default of Tycho i.e. the `tycho-p2:p2-metadata(-default)` goal is to replace artifacts with the baseline if version+qualifier is identical, but if the content actually differs the `compare-version-with-baselines` will complain so I think Andrey is right with assuming that all bounds have to be touched.

But in general, since we faced a similar problem in m2e where many bundles would have need to be touched after a Tycho-update due to a new ECJ version that generated different byte-code, is it possible to somehow determine if the generated byte-code is equivalent? Just comparing the sources is not always sufficient, because changes in referenced classes can be binary incompatible while being source compatible (e.g. narrowing the return type of a method or returning a Collection instead of an Array, when the method is called in an enhanced for-loop).

If that would be possible it would allow changes like https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/564, which then would make the version bumps in cases like changed byte-code emitted by ECJ unnecessary (of course the changes would then only end up in the bundle in a p2-repo if any other file was changed.

**Comment by iloveeclipse** [comment]
> is it possible to somehow determine if the generated byte-code is equivalent?

Equivalent will not work here. Build with target Java 8 will be "equivalent" to target Java 11 or 17, build with debug attributes will be "equivalent" to build without debug attributes, and so on.

I could only imagine tycho can detect compiler version change between baseline and current build and don't replace produced binary if it doesn't match baseline.

**Comment by iloveeclipse** [comment]
Tomorrow I plan to continue with
> Finally update the cbi-ecj-version in [eclipse.platform.releng.aggregator/eclipse-platform-parent/pom.xml](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse-platform-parent/pom.xml)

**Comment by iloveeclipse** [comment]
@akurtakov : I've changed compiler now & plan to start IBuild. Any objections?

**Comment by akurtakov** [comment]
Go for it.

**Comment by iloveeclipse** [comment]
Started https://ci.eclipse.org/releng/job/Builds/job/I-build-4.29/40/

**Comment by MohananRahul** [comment]
> @akurtakov : I've changed compiler now & plan to start IBuild. Any objections?

It is already in Schedule, 6 am

**Comment by iloveeclipse** [comment]
> 6 am 
which time zone?

**Comment by MohananRahul** [comment]
> 6 am
> which time zone?

EDT, New York

**Comment by iloveeclipse** [comment]
This is in 50 minutes, and previous builds took over hour to complete. So should we cancel current build?

**Comment by MohananRahul** [comment]
> This is in 50 minutes, and previous builds took over hour to complete. So should we cancel current build?

No ..  I think we cancel scheduled one

**Comment by MohananRahul** [comment]
> This is in 50 minutes, and previous builds took over hour to complete. So should we cancel current build?

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1190 Please merge to cancel schedule build.

**Comment by iloveeclipse** [comment]
279 comparator errors :-)

https://download.eclipse.org/eclipse/downloads/drops4/I20230630-0500/
https://download.eclipse.org/eclipse/downloads/drops4/I20230630-0500/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

I'm going to start touching bundles.

**Comment by iloveeclipse** [comment]
@akurtakov : where one can find actual bytecode **diffs**? I see classes that shouldn't be touched IMHO.

**Comment by iloveeclipse** [comment]
Found: https://download.eclipse.org/eclipse/downloads/drops4/I20230630-0500/buildlogs/comparatorlogs/

**Comment by akurtakov** [comment]
There must have been such cases in the past. @sravanlakkimsetti is there a way to not touch almost every bundle?

**Comment by sravanlakkimsetti** [comment]
the change is for reimplementation of string concat. Unfortunately we will need to touch all the bundles here. We did not had these many earlier though.  

It will be difficult for one person to do this. I will touch equinox and p2

**Comment by iloveeclipse** [comment]
> It will be difficult for one person to do this. I will touch equinox and p2

Thanks. I'm on platform right now.

**Comment by laeubi** [comment]
> @akurtakov : where one can find actual bytecode **diffs**? I see classes that shouldn't be touched IMHO.

Just in case here is how Tycho compare classes:

https://github.com/eclipse-tycho/tycho/blob/master/tycho-artifactcomparator/src/main/java/org/eclipse/tycho/zipcomparator/internal/ClassfileComparator.java

so just if someone with deeper knowledge can provide some mean to detect the string change the comparator can maybe made to accept string-only- changes.

**Comment by iloveeclipse** [comment]
platform, jdt.core, jdt.debug. addressed, will continue with pde next

**Comment by MohananRahul** [comment]
addressing SWT

**Comment by sravanlakkimsetti** [comment]
jdt.ui addressed

**Comment by sravanlakkimsetti** [comment]
equinox addressed

**Comment by iloveeclipse** [comment]
Starting platform.ui.

**Comment by merks** [comment]
@iloveeclipse @sravanlakkimsetti @MohananRahul @anamikaaggarwal43

The combined teamwork to make these sweeping changes is really impressive!  🎖️

**Comment by iloveeclipse** [comment]
Going to platform.ua.

**Comment by iloveeclipse** [comment]
platform releng addressed.

I believe this was the last one.

**Comment by sravanlakkimsetti** [comment]
equinox p2 is addressed

**Comment by iloveeclipse** [comment]
- [x] eclipse.jdt.core  
- [x] eclipse.jdt.debug  
- [x] eclipse.jdt.ui  
- [x] eclipse.pde  
- [x] eclipse.platform  
- [x] eclipse.platform.releng  
- [x] eclipse.platform.swt 
- [x]  eclipse.platform.swt.binaries  
- [x] eclipse.platform.ua  
- [ ] eclipse.platform.ui  
- [x] equinox  
- [x] rt.equinox.p2

Platform UI PR is pending.

**Comment by iloveeclipse** [comment]
Note: jdt.ui misses bundle version bumps! I will push a PR to fix that.

**Comment by MohananRahul** [comment]
addressing Platform UI

**Comment by iloveeclipse** [comment]
> addressing Platform UI

It is already addressed: https://github.com/eclipse-platform/eclipse.platform.ui/pull/901

**Comment by iloveeclipse** [comment]
We should be ready for build now.

**Comment by HannesWell** [comment]
Thanks to all of you.

**Comment by merks** [comment]
Really awesome teamwork indeed! 💯

**Comment by iloveeclipse** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3343 prevented us to validete last JDT UI fix, so I've merged it without validation and triggered new build to get ugly ecj bug fixed: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1201 - so we could rebuild ecj once again and rebuild SDK with fixed ecj for M1.

https://ci.eclipse.org/releng/job/Builds/job/I-build-4.29/43/

**Comment by iloveeclipse** [comment]
Triggered ecj 3.35.0.v20230702-0608 promotion from https://download.eclipse.org/eclipse/updates/4.29-I-builds/I20230702-0600/plugins/
via https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/153/console
Result is OK: https://repo.eclipse.org/content/repositories/eclipse-staging/org/eclipse/jdt/ecj/3.35.0.v20230702-0608/

**Comment by iloveeclipse** [comment]
Note: next SDKCbuild may again be marked as unstable, because ecj might generate changed bytecode after fix for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1201, but I believe that there will be not so many cases (if any at all) that need to be touched again.

So not closing this issue yet.

**Comment by iloveeclipse** [comment]
Triggered https://ci.eclipse.org/releng/job/Builds/job/I-build-4.29/45/

**Comment by iloveeclipse** [comment]
https://download.eclipse.org/eclipse/downloads/drops4/I20230702-1310/ is built with new ecj and has no comparator errors => done here.
