### ISSUE TITLE
Commits merged by github have "GitHub <noreply@github.com>" committer 

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#12]
I see in Eclipse History that differently to gerrit, where the user that triggered "merge" was recorded as committer, few commits are pushed where the committer is "GitHub <noreply@github.com>":
- 3dfa91e12b724ee6bdb4ab88e106645d81e37b12
- 004e0b224f8361da4c6ddf81c09e54aaa099d551
- 02999245b760e4ddb79bd80343277e4828b40fab

Is this something we want / can / should configure globally and **document in a policy**, or is this responsibility of the individuals to do so, and if yes, hhow it should be done?

See `git log --pretty=fuller` command output:

```
git log --pretty=fuller -n 3
commit 02999245b760e4ddb79bd80343277e4828b40fab (HEAD -> master, origin/master)
Author:     Jayaprakash Arthanareeswaran <jarthana@in.ibm.com>
AuthorDate: Wed Feb 9 17:37:29 2022 +0530
Commit:     GitHub <noreply@github.com>
CommitDate: Wed Feb 9 17:37:29 2022 +0530

    Create P-build for Java 18 #7 (#11)

commit 3dfa91e12b724ee6bdb4ab88e106645d81e37b12 (tag: Y20220209-0600)
Author:     Sarika Sinha <sarika.sinha@in.ibm.com>
AuthorDate: Wed Feb 9 14:27:28 2022 +0530
Commit:     GitHub <noreply@github.com>
CommitDate: Wed Feb 9 14:27:28 2022 +0530

    #7 Debug  j18 (#10)
    
    * Update repositories_java18patch.txt
    
    * Update pom.xml
    
    * Update feature.xml

commit 004e0b224f8361da4c6ddf81c09e54aaa099d551
Author:     Kalyan Prasad Tatavarthi <kalyan_prasad@in.ibm.com>
AuthorDate: Wed Feb 9 13:58:53 2022 +0530
Commit:     GitHub <noreply@github.com>
CommitDate: Wed Feb 9 13:58:53 2022 +0530

    #7 jdt ui changes for p-build (#9)
    
    * Update repositories_java18patch.txt
    
    * Update feature.xml
    
    * Update pom.xml
```

**Comment by mickaelistria** [comment]
An alternative is to just let the committer field as it, unless it actually is a problem. But at the moment, I don't see what problem it does causes.

**Comment by akurtakov** [comment]
@vogella is looking into a way to disable merge commits

**Comment by gzsombor** [comment]
AFAIK, this happens if you use "Squash commits..." button in Github, instead of the "Rebase and merge"

**Comment by SarikaSinha** [comment]
I had created a local branch with first patch. Second patch was merged to the local branch. Later pull request was created with the local branch and merged. And then local branch was deleted.

**Comment by akurtakov** [comment]
Looks like there is no one still interested so I guess it's not an issue.
