### ISSUE TITLE
Merge eclipse.platform.releng into this one

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.releng.aggregator#1216]
In addition to one less repo to maintain it will make version bumps detection for help and test features being properly detected and calculated and thus reduce the need for manual touching.

**Comment by akurtakov** [comment]
@sravanlakkimsetti Do you have anythings against ?

**Comment by akurtakov** [comment]
My view is to keep the eclipse.platform.releng folder as we have it already but it being proper folder rather than submodule.

**Comment by sravanlakkimsetti** [comment]
Please go ahead with the merge

**Comment by akurtakov** [comment]
@laeubi Can you spend some time to help with this one? You're our professional in merging now :).

**Comment by laeubi** [comment]
> @laeubi Can you spend some time to help with this one? You're our professional in merging now :).

So you just want that [eclipse.platform.releng](https://github.com/eclipse-platform/eclipse.platform.releng/tree/c861ab478210504182362ddced2d77155f09c518) is physically located here as we have done for [eclipse.platform.common](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/eclipse.platform.common) already?

**Comment by akurtakov** [comment]
> > @laeubi Can you spend some time to help with this one? You're our professional in merging now :).
> 
> So you just want that [eclipse.platform.releng](https://github.com/eclipse-platform/eclipse.platform.releng/tree/c861ab478210504182362ddced2d77155f09c518) is physically located here as we have done for [eclipse.platform.common](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/eclipse.platform.common) already?

100%

**Comment by laeubi** [comment]
See
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1218

**Comment by akurtakov** [comment]
I consider this one done. Thanks @laeubi !
