### ISSUE TITLE
SDK Linux builds randomly fail to start on jenkins

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1223]
I've created https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2877 (which is now duplicate of re-opened https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2478).

**Comment by akurtakov** [comment]
Is this one still needed?

**Comment by iloveeclipse** [comment]
Unfortunately yes. I've used to retrrigger failed Linux builds every second day.

**Comment by akurtakov** [comment]
I'm closing this one as it looks non actionable from project POV.
