### ISSUE TITLE
Impossible to enable logging for Apache HTTP Client 5 (no slf4j implementation available)

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#1226]
Moving from Bugzilla [Bug 579472](https://bugs.eclipse.org/bugs/show_bug.cgi?id=579472) - Impossible to enable logging/debug for Apache HTTP Client 5 (no slf4j implementation available)

When using the Eclipse SDK package from

https://download.eclipse.org/eclipse/downloads/drops4/R-4.23-202203080310/

it is impossible to debug the Apache HTTP Client 5 library.

This is because the bundles
  org.apache.httpcomponents.client5.httpclient5
  org.apache.httpcomponents.core5.httpcore5
depend on
  org.slf4j.api
but no implementation of org.slf4j.api is shipped with the SDK package:

  SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
  SLF4J: Defaulting to no-operation (NOP) logger implementation
  SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

In the Eclipse For Java package on the other hand, it looks we are lucky by chance:
- ch.qos.logback.slf4j is present which delegates logging to logback
- ch.qos.logback.core implementation is available as well
Both are part of the org.eclipse.m2e.logback.feature.

This raises the questions:
- Is it the product's responsibility to ship all necessary logging implementations
  or should the ECF filetransfer feature itself ship an implementation
  such as org.slf4j.simple?
- Since the logger binding works via classpath, the implementation has to be a fragment
  of the org.slf4j.api bundle. How would we deal with multiple fragments
  being available?
- Is there a way we could customize the org.apache.httpcomponents.client5.httpclient5
  bundle in Orbit so it includes e.g. the slf4j-simple implementation directly?

Related information:
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=338232
- https://www.eclipse.org//lists/cross-project-issues-dev/msg05659.html
- https://git.eclipse.org/r/c/orbit/orbit-recipes/+/96277/

**Comment by HannesWell** [comment]
> In general it is the responsibility of the _product_ to eventually include a binding

Yes absolutely.
But with https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1195 we could think about adding for example slf4j-simple to the sdk product (which does not contain m2e) as well as a proper configuration.
For the EPPs each package can decide on its own which logging back-end to use.
M2E could be enhanced to work with a logback configured by the product or maybe it could be tried to also work with log4j-2 as backend.

At the moment the SDK implicitly uses slf4j-nop and all EPPs that have m2e included use m2e-logback.
