### ISSUE TITLE
User cannot update Tip of the Day

### ISSUE THREAD

**Issue by jjohnstn** [eclipse-platform/eclipse.platform.releng.aggregator#1242]
From: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/678 opened by @andreasdc

Cannot complete the install because of a conflicting dependency.
Software being installed: Tip of the Day UI Feature 0.4.0.v20230429-1617 (org.eclipse.tips.feature.feature.group 0.4.0.v20230429-1617)
Software currently installed: Tip of the Day UI Feature Developer Resources 0.4.0.v20230317-0802 (org.eclipse.tips.feature.source.feature.group 0.4.0.v20230317-0802)
Only one of the following can be installed at once:
IDE Enablement for Tip of the Day 0.3.0.v20230315-0554 (org.eclipse.tips.ide 0.3.0.v20230315-0554)
IDE Enablement for Tip of the Day 0.3.0.v20230429-1617 (org.eclipse.tips.ide 0.3.0.v20230429-1617)
Cannot satisfy dependency:
From: Tip of the Day UI Feature 0.4.0.v20230317-0802 (org.eclipse.tips.feature.feature.group 0.4.0.v20230317-0802)
To: org.eclipse.equinox.p2.iu; org.eclipse.tips.ide [0.3.0.v20230315-0554,0.3.0.v20230315-0554]
Cannot satisfy dependency:
From: Tip of the Day UI Feature 0.4.0.v20230429-1617 (org.eclipse.tips.feature.feature.group 0.4.0.v20230429-1617)
To: org.eclipse.equinox.p2.iu; org.eclipse.tips.ide [0.3.0.v20230429-1617,0.3.0.v20230429-1617]
Cannot satisfy dependency:
From: Tip of the Day UI Feature Developer Resources 0.4.0.v20230317-0802 (org.eclipse.tips.feature.source.feature.group 0.4.0.v20230317-0802)
To: org.eclipse.equinox.p2.iu; org.eclipse.tips.feature.feature.group [0.4.0.v20230317-0802,0.4.0.v20230317-0802]

**Comment by merks** [comment]
Without steps to reproduce the problem this will just fester until someone closes it. It is a fact that one can’t install two different versions of the same feature so that’s not something that can be fixed.

**Comment by andreasdc** [comment]
Then how to fix that? Steps to reproduce:
try to update, the problem will appear.

**Comment by merks** [comment]
Can you provide details about what you currently have installed that you are trying to update?  The folks providing the packages you can install with the installer or download and unpack generally test that it can be updated to the next release. Have you  perhaps installed additional things after creating the installation that might be preventing updates?   Screen captures are often helpful and you can easily paste them into an issue in the browser, e.g., a screen shot of the about dialog and a screenshot of all the installed features in that dialog would answer many questions.

**Comment by andreasdc** [comment]
What do you mean what currently I have installed? Eclipse. Do you mean components or something? How to check it?

**Comment by andreasdc** [comment]
![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/82218780/c7fb1a07-7743-444f-b387-f351b8eee49b)

  Buildship: Eclipse Plug-ins for Gradle	3.1.6.v20220511-1359	org.eclipse.buildship.feature.group	Eclipse Buildship
  CodeTogether Collaboration	2023.1.1.202304181921	com.genuitec.eclipse.codetogether.feature.feature.group	Genuitec, LLC
  Debug Unit Test support	1.1.0.v20230317-0802	org.eclipse.unittest.ui	Eclipse.org
  Debug Unit Test support Source	1.1.0.v20230317-0802	org.eclipse.unittest.ui.source	Eclipse.org
  DevStyle (includes Darkest Dark Theme)	1.11.0.202306151725	com.genuitec.eclipse.theming.core.feature.feature.group	Genuitec, LLC
  DevStyle - Icon Designer	1.11.0.202306151725	com.genuitec.eclipse.theming.designer.feature.feature.group	Genuitec, LLC
  DevStyle with CodeTogether Bundle	1.11.0.202306151725	com.genuitec.eclipse.theming.feature.feature.group	Genuitec, LLC
  ECF Apache Httpclient 5 FileTransfer Provider Developer Resources	1.1.701.v20221112-0806	org.eclipse.ecf.filetransfer.httpclient5.feature.source.feature.group	Eclipse.org - ECF
  ECF Core Feature Developer Resources	1.6.1.v20211005-1944	org.eclipse.ecf.core.feature.source.feature.group	Eclipse.org - ECF
  ECF Core SSL Feature Developer Resources	1.1.501.v20210409-2301	org.eclipse.ecf.core.ssl.feature.source.feature.group	Eclipse.org - ECF
  ECF Filetransfer Feature Developer Resources	3.14.1800.v20220215-0126	org.eclipse.ecf.filetransfer.feature.source.feature.group	Eclipse.org - ECF
  ECF Filetransfer SSL Feature Developer Resources	1.1.401.v20210409-2301	org.eclipse.ecf.filetransfer.ssl.feature.source.feature.group	Eclipse.org - ECF
  Eclipse 2.0 Style Plugin Support	1.0.0.v20150202-1328	org.eclipse.osgi.compatibility.plugins.feature.feature.group	Eclipse.org - Equinox
  Eclipse e4 Progress View	0.3.700.v20230214-1401	org.eclipse.e4.ui.progress	Eclipse.org
  Eclipse e4 Progress View Source	0.4.0.v20230317-0802	org.eclipse.e4.ui.progress.source	Eclipse.org
  Eclipse e4 Tools Developer Resources	4.28.0.v20230404-0801	org.eclipse.e4.core.tools.feature.source.feature.group	Eclipse.org
  Eclipse IDE for Java Developers	4.27.0.20230309-1200	epp.package.java	Eclipse Packaging Project
  Eclipse p2 Discovery Developer Resources	1.3.0.v20230322-1009	org.eclipse.equinox.p2.discovery.feature.source.feature.group	Eclipse.org
  Eclipse Persistence	1.1.0.v20230317-0802	org.eclipse.e4.tools.persistence.feature.feature.group	Eclipse.org
  Eclipse Platform	4.27.0.v20230302-0300	org.eclipse.platform.feature.group	Eclipse.org
  Eclipse Platform Launcher Executables	3.8.2100.v20230307-1841	org.eclipse.equinox.executable.feature.group	Eclipse.org
  Eclipse Plug-in Test runner client for UnitTest View (Experimental)	1.0.400.v20230331-0919	org.eclipse.pde.unittest.junit.feature.group	Eclipse.org
  Eclipse Plug-in Test runner client for UnitTest View (Experimental) Developer Resources	1.0.400.v20230331-0919	org.eclipse.pde.unittest.junit.source.feature.group	Eclipse.org
  Eclipse Product Configuration	1.1.2000.v20221201-1120	org.eclipse.rcp.configuration.feature.group	Eclipse.org
  Eclipse RCP	4.27.0.v20230302-0300	org.eclipse.rcp.feature.group	Eclipse.org
  Eclipse SDK Examples Developer Resources	4.28.0.v20230405-1800	org.eclipse.sdk.examples.source.feature.group	Eclipse.org
  Eclipse SDK Tests	4.27.0.v20230302-0300	org.eclipse.sdk.tests.feature.group	Eclipse.org
  EMF - Eclipse Modeling Framework Core Runtime Developer Resources	2.31.0.v20230226-0921	org.eclipse.emf.ecore.source.feature.group	Eclipse Modeling Project
  EMF Common	2.29.0.v20230315-1321	org.eclipse.emf.common.feature.group	Eclipse Modeling Project
  EMF Common Developer Resources	2.29.0.v20230315-1321	org.eclipse.emf.common.source.feature.group	Eclipse Modeling Project
  EMF Data Binding	1.10.0.v20230211-1150	org.eclipse.emf.databinding.feature.group	Eclipse Modeling Project
  EMF Data Binding Developer Resources	1.10.0.v20230211-1150	org.eclipse.emf.databinding.source.feature.group	Eclipse Modeling Project
  EMF Edit	2.19.0.v20230211-1150	org.eclipse.emf.edit.feature.group	Eclipse Modeling Project
  EMF Edit Data Binding	1.10.0.v20230211-1150	org.eclipse.emf.databinding.edit.feature.group	Eclipse Modeling Project
  EMF Edit Data Binding Developer Resources	1.10.0.v20230211-1150	org.eclipse.emf.databinding.edit.source.feature.group	Eclipse Modeling Project
  EMF Edit Developer Resources	2.19.0.v20230211-1150	org.eclipse.emf.edit.source.feature.group	Eclipse Modeling Project
  Equinox p2, Discovery UI support	1.3.0.v20230322-1009	org.eclipse.equinox.p2.discovery.feature.feature.group	Eclipse.org - Equinox
  Git integration for Eclipse	6.5.0.202303070854-r	org.eclipse.egit.feature.group	Eclipse EGit
  Java implementation of Git	6.5.0.202303070854-r	org.eclipse.jgit.feature.group	Eclipse JGit
  JUnit Test runner client for UnitTest View	1.1.0.v20230323-1830	org.eclipse.jdt.ui.unittest.junit.feature.feature.group	Eclipse.org
  JUnit Test runner client for UnitTest View Developer Resources	1.1.0.v20230323-1830	org.eclipse.jdt.ui.unittest.junit.feature.source.feature.group	Eclipse.org
  M2E - Maven Integration for Eclipse	2.3.0.20230523-2033	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e
  M2E - POM Editor using LemMinX language server (includes Incubating components)	2.0.4.20230520-0934	org.eclipse.m2e.lemminx.feature.feature.group	Eclipse.org - m2e
  M2E - SLF4J over Logback Logging	2.1.2.20230523-2106	org.eclipse.m2e.logback.feature.feature.group	Eclipse.org - m2e
  Marketplace Client	1.10.1.v20221110-1841	org.eclipse.epp.mpc.feature.group	Eclipse Marketplace Client
  Mylyn WikiText Editors	3.0.46.202301111837	org.eclipse.mylyn.wikitext.editors_feature.feature.group	Eclipse Mylyn
  Oomph Setup	1.28.0.v20230523-0636	org.eclipse.oomph.setup.feature.group	Eclipse Oomph Project
  SWT Tools	3.108.700.v20220914-2245	org.eclipse.swt.tools.feature.feature.group	Eclipse.org
  SWT Tools Developer Resources	3.108.700.v20220914-2245	org.eclipse.swt.tools.feature.source.feature.group	Eclipse.org
  Tip of the Day UI Feature	0.4.0.v20230317-0802	org.eclipse.tips.feature.feature.group	Eclipse.org
  Tip of the Day UI Feature Developer Resources	0.4.0.v20230317-0802	org.eclipse.tips.feature.source.feature.group	Eclipse.org
  TM Terminal	11.1.0.202212091724	org.eclipse.tm.terminal.feature.feature.group	Eclipse CDT
  Wild Web Developer XML tools	1.1.0.202304242122	org.eclipse.wildwebdeveloper.xml.feature.feature.group	Eclipse Wild Web Developer project

**Comment by merks** [comment]
Thank you.  I'll have a closer look tomorrow...

**Comment by andreasdc** [comment]
Did I update successfully?

Eclipse IDE for Java Developers (includes Incubating components)

Version: 2023-06 (4.28.0)
Build id: 20230608-1333

**Comment by merks** [comment]
I downloaded this:

https://mirror.tspu.ru/eclipse/technology/epp/downloads/release/2023-03/R/eclipse-java-2023-03-R-win32-x86_64.zip

That installed this version:
```
Eclipse IDE for Java Developers (includes Incubating components)

Version: 2023-03 (4.27.0)
Build id: 20230309-1520
```
I did Help -> Check for Updates, and these came up:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/343d126e-1994-4292-a625-fd284fe3da61)

I let it make those updates and now have this installed:
```
Eclipse IDE for Java Developers (includes Incubating components)

Version: 2023-06 (4.28.0)
Build id: 20230608-1333
```
So this does work generally.  But it's possible for other things you've installed to "do bad things".  For example, they might provide a feature that **includes** some bundle or feature from the platform, locking in that one specific version such that only if there is an update to that including feature can the included bundle or feature be updated. That's likely the case here but tracking down which specific thing might be doing that is not feasible for me, and you seem to have gotten it to update anyway...

**Comment by andreasdc** [comment]
> Did I update successfully?
> 
> Eclipse IDE for Java Developers (includes Incubating components)
> 
> Version: 2023-06 (4.28.0) Build id: 20230608-1333

If yes then I don't know what I did, but it works. Eclipse is still bugged though.
