### ISSUE TITLE
Is org.apache.jasper.glassfish actually required?

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.releng.aggregator#1251]
I've been trying to eliminate bundles in the target platform from old cvs-based orbit builds.

Looking at SimRel, the only strict requirement on org.apache.jasper.glassfish is the inclusion in the help feature:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/bc3d5ce1-4c7d-4b6d-8e5b-80b0d54c6fb9)

Looking at what the bundle provides we see two dependencies on the exported packages:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/2ad34ca9-797c-45ed-857b-0e20edb6753e)

But if we look at that package requirement

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/eaff82db-1070-4478-b6f4-d81b58a86dd7)

it's also satisfied by org.glassfish.web.javax.servlet.jsp /2.3.4

And that's already in the target platform:
```
			  <dependency>
				  <groupId>org.glassfish.web</groupId>
				  <artifactId>javax.servlet.jsp</artifactId>
				  <version>2.3.4</version>
				  <type>jar</type>
			  </dependency>
```
So I think we can remove this now and remove the inclusion in the feature
```
      <!-- In process of being replaced by org.glassfish.web.javax.servlet.jsp from Central -->
      <unit id="org.apache.jasper.glassfish" version="2.2.2.v201501141630"/>
      <unit id="org.apache.jasper.glassfish.source" version="2.2.2.v201501141630"/>
```

@akurtakov 

Or is there something I've overlooked?

**Comment by akurtakov** [comment]
If the help system still works without org.apache.jasper.glassfish (aka jsp files are getting compiled and render after that) you can remove it. IIRC @mickaelistria tried to replace it but it was not working.

**Comment by merks** [comment]
The short answer is that currently it is required.  

The long answer is that with some small effort it can be replaced the following:

https://repo1.maven.org/maven2/org/eclipse/jetty/apache-jsp/10.0.15/apache-jsp-10.0.15.pom

But firstly we have to make sure the requirements of that are satisfied and that's not the case with the current  contents of the target platform  We need these:
```
			  <dependency>
				  <groupId>org.eclipse.jetty.toolchain</groupId>
				  <artifactId>jetty-servlet-api</artifactId>
				  <version>4.0.6</version>
				  <type>jar</type>
			  </dependency>
			  <dependency>
				  <groupId>org.mortbay.jasper</groupId>
				  <artifactId>apache-jsp</artifactId>
				  <version>9.0.52</version>
				  <type>jar</type>
			  </dependency>
```

We also have to be wary of all the places the name bundle symbolic name is hard coded:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/5aa7bb8a-aafd-47be-8ce5-61e17882e666)

To get it working with the newer dependencies, we have to allow newer versions and com.sun.el is needed:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/36352cbd-3dc1-437c-b061-8c2eab7215ce)

The specialized class loader needs to be able to load com.sun.el.EpxressionFactory:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/d9c211b3-1987-4d73-9df7-1867ca1c1318)

And finally the servlet needs to initialize Jasper 

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/85b1323d-98fe-468e-888b-6c068136d616)

The older include can be removed from here:

/org.eclipse.help-feature/feature.xml

And then the help system works:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/df8db9bd-15ae-46e8-8da0-7a333384597d)

@akurtakov 

I'm not sure if it's appropriate to make these changes immediately.  Perhaps we'll have to wait for 2023-12 m1?

**Comment by akurtakov** [comment]
Help systems jsp support is extremely fragile so please keep it for M1. Also I do believe that an effort to move to Jetty 12 (https://www.eclipse.org/lists/jetty-announce/msg00177.html)  with EE 8 should be done prior or toghether with that as that would open the door for switching the EE implementation without changing major Jetty version.

**Comment by merks** [comment]
FYI, looking here:

- https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-bom/12.0.0/jetty-bom-12.0.0.pom

versus here:

- https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-bom/10.0.15/jetty-bom-10.0.15.pom
- https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-bom/11.0.15/jetty-bom-11.0.15.pom

the JSP support seems not to be present:

https://repo1.maven.org/maven2/org/eclipse/jetty/apache-jsp/

So I don't yet see an upgrade path via 12.x..

**Comment by akurtakov** [comment]
That's because Jetty 12 is independent of EE version and one can switch between EE 8 (https://repo1.maven.org/maven2/org/eclipse/jetty/ee8/jetty-ee8-bom/12.0.0/jetty-ee8-bom-12.0.0.pom), EE 9 (https://repo1.maven.org/maven2/org/eclipse/jetty/ee9/jetty-ee9-bom/12.0.0/jetty-ee9-bom-12.0.0.pom) and EE 10 (https://repo1.maven.org/maven2/org/eclipse/jetty/ee10/jetty-ee10-bom/12.0.0/jetty-ee10-bom-12.0.0.pom) .

**Comment by merks** [comment]
I see!Not sure version of the dependency is specified when no version is specified.  The largest I guess:

https://repo1.maven.org/maven2/org/eclipse/jetty/ee10/jetty-ee10-apache-jsp/12.0.0/jetty-ee10-apache-jsp-12.0.0.pom

Oh well, stuff to revisit in September...

Thanks for sharing your insights!

**Comment by mickaelistria** [comment]
I tried to remove it a while ago in #774 , but gave up. Not sure whether the reasons still apply with newer versions of other deps.

**Comment by merks** [comment]
@akurtakov 

I think I can get JSP working with newer dependencies as described here:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1251#issuecomment-1678788042

But I don't have the capacity to try to migrate everything to Jetty 12.x.

So should I do the smaller step for now, or should I just leave the whole thing for someone to do the Jetty 12.x work eventually?

**Comment by akurtakov** [comment]
Whatever can be done now is better than waiting for big bang changes IMHO.

**Comment by merks** [comment]
@iloveeclipse @akurtakov 

I see the nightly I-Build fails like this:
```
00:50:31  [ERROR] Cannot resolve project dependencies:
00:50:31  [ERROR]   Software being installed: org.eclipse.equinox.sdk.product 4.30.0.qualifier
00:50:31  [ERROR]   Missing requirement: org.mortbay.jasper.apache-jsp 9.0.52 requires 'java.package; org.eclipse.jdt.core.compiler 0.0.0' but it could not be found
00:50:31  [ERROR]   Cannot satisfy dependency: org.eclipse.equinox.jsp.jasper 1.1.800.v20230914-1441 depends on: java.package; org.apache.jasper.servlet [9.0.0,10.0.0)
00:50:31  [ERROR]   Cannot satisfy dependency: org.eclipse.equinox.sdk.feature.group 3.23.1000.v20230914-1441 depends on: org.eclipse.equinox.p2.iu; org.eclipse.equinox.jsp.jasper [1.1.800.v20230914-1441,1.1.800.v20230914-1441]
00:50:31  [ERROR]   Cannot satisfy dependency: org.eclipse.equinox.sdk.product 4.30.0.qualifier depends on: org.eclipse.equinox.p2.iu; org.eclipse.equinox.sdk.feature.group 0.0.0
```
This suggests that org.eclipse.jdt.core.compiler.batch is needed in the org.eclipse.equinox.sdk feature:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/b57a179c-09da-422d-8664-2f47f719a94f)

One might have expected Tycho to have resolved that package import...

**Comment by mickaelistria** [comment]
Aren't we discussing removal of org.eclipse.equinox.sdk.product in #1235 ?

**Comment by merks** [comment]
That may be.  But the build is broken and it appears that the Equinox SDK feature is "incomplete", at least as far as inclusion in a product is concern...

**Comment by iloveeclipse** [comment]
> That may be. But the build is broken and it appears that the Equinox SDK feature is "incomplete", at least as far as inclusion in a product is concern...

Fully agree. I'm going to merge https://github.com/eclipse-equinox/equinox/pull/312 & start an I-Build.

**Comment by merks** [comment]
@akurtakov  @iloveeclipse 

I created an installation using the installer based on the just-completed I-Build from today.  The help system is working:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/481d1704-3d71-4b7e-933e-95d7053c6fb2)

So I think we're in pretty reasonable shape...

Hopefully there are only test issues to iron out; or better yet, hopefully there are none of those!

**Comment by merks** [comment]
For this build I see all the UA tests pass for this:

https://download.eclipse.org/eclipse/downloads/drops4/I20230915-0520/testresults/xml/org.eclipse.ua.tests_ep430I-unit-macM1-java17_macosx.cocoa.aarch64_17.xml

Including the org.eclipse.ua.tests.help.webapp.HelpServerInterrupt and the org.eclipse.ua.tests.help.webapp.HelpServerBinding tests, which were the ones failing for the PR build.

I'll need to key an eye on these when they are done, but it's looking promising:

https://download.eclipse.org/eclipse/downloads/drops4/I20230915-0750/testResults.php

**Comment by merks** [comment]
The tests are fine

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/3a537934-7498-4639-995c-55dd46038539)

so this is done.
