### ISSUE TITLE
Readme file for 4.29

### ISSUE THREAD

**Issue by Shee43** [eclipse-platform/eclipse.platform.releng.aggregator#1262]
Readme file needs to be added for 4.29.

For more details on the readme see [Bug 493368](https://bugs.eclipse.org/bugs/show_bug.cgi?id=493368).

ReadMe for 4.28 - https://github.com/eclipse-platform/eclipse.platform.releng/issues/233

**Comment by SarikaSinha** [comment]
We also need to change in eclipse.org.
Ref https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/30/files

**Comment by SarikaSinha** [comment]
We should also send a mail to Eclipse mailing list, so that interested people can review and change for their Projects if applicable.
