### ISSUE TITLE
Eliminate dependencies on ancient Orbit bundles

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.releng.aggregator#1349]
I'd like to eliminate the dependencies on these 4 bundles:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/d4215ecd-1ec1-4655-8a91-1270b3b58661)

In particular, I'd like to to eliminate/replace these:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/18a16b9fee9249fd0987b771c9937ffef8e2b195/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target#L55-L64

All of the direct batik dependencies are satisfied by this newer bundle:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/878a1692-fae4-4e4a-a794-2a5bcd9a4071)

That bundle is maintained with source here:

https://github.com/eclipse-orbit/orbit-legacy/tree/main/plugins/org.eclipse.orbit.xml-apis-ext

The org.w3c.dom.events package is provided by the JDK so there is no need for an ancient bundle to provide those packages.

I'm not 100% sure the best path forward.  To start, I think it would be best to eliminate all includes these bundles in features or products, not replace then with different/new ones.  We should also eliminate any bundle requires...

@akurtakov 

Do you have any concerns or suggestions?

**Comment by laeubi** [comment]
> The org.w3c.dom.events package is provided by the JDK so there is no need for an ancient bundle to provide those packages.

is this really always the case? I remember some issue with `w3c.dom` coming from different bundles / jdk packages cause issues so one better imports these with a proper version range. Neverless all these should be available from maven central

**Comment by merks** [comment]
> > The org.w3c.dom.events package is provided by the JDK so there is no need for an ancient bundle to provide those packages.
> 
> is this really always the case? I remember some issue with `w3c.dom` coming from different bundles / jdk packages cause issues so one better imports these with a proper version range. Neverless all these should be available from maven central

We're taking here **only** about eliminating dependencies on the org.w3c.dom.events **bundle** not about eliminating any package requirements (that can be satisfied by whatever/something else).  

The a.jre.javase IU does provide it:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/7be65bc7-a41d-4425-8efe-97eb6d4861c1)

so from the p2 resolution point of view, there is an expectation that the JRE will provide it...

**Comment by akurtakov** [comment]
No concerns from my side. These ancient bundles have been PITA for too long.

**Comment by merks** [comment]
I think mostly the replacements are done.  I will retest tomorrow in the IDE when there is a new I-Build.

These two places are of concern, because I don't really understand the purpose for these:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/9e5bbc8a72d5a590b570651e430d1241a89b4092/eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/pom.xml#L229-L233

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/9e5bbc8a72d5a590b570651e430d1241a89b4092/eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/platformOptions.txt#L173

I think I will just replace them with org.eclipse.orbit.xml-apis-ext to be sure that nothing breaks...

**Comment by HannesWell** [comment]
> > The org.w3c.dom.events package is provided by the JDK so there is no need for an ancient bundle to provide those packages.
> 
> is this really always the case? I remember some issue with `w3c.dom` coming from different bundles / jdk packages cause issues so one better imports these with a proper version range. Neverless all these should be available from maven central

The w3c.dom packages were mentioned in the validation error messages because PDE did not consider the packages provided by the JVM and just used the hard-coded list of packages for a EE from Equinox for pre Java-9 EEs, but that is fixed now.
Or are you refering to something else?
In general proper version ranges are of course good. Only if the package comes from the JVM, there is no package version available.

**Comment by iloveeclipse** [comment]
Two releng tests are failing probably because of this change:

https://download.eclipse.org/eclipse/downloads/drops4/I20230913-1800/testresults/html/org.eclipse.releng.tests_ep430I-unit-win32-java17_win32.win32.x86_64_17.html

Plugin directory missing required files: C:\Users\genie.releng\workspace\AutomatedTests\ep430I-unit-win32-java17\workarea\I20230913-1800\eclipse-testing\test-eclipse\eclipse\plugins\org.eclipse.orbit.xml-apis-ext_1.0.0.v20230815-1152.jar;

```
java.lang.AssertionError: Plugin directory missing required files: C:\Users\genie.releng\workspace\AutomatedTests\ep430I-unit-win32-java17\workarea\I20230913-1800\eclipse-testing\test-eclipse\eclipse\plugins\org.eclipse.orbit.xml-apis-ext_1.0.0.v20230815-1152.jar;
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.eclipse.releng.tests.BuildTests.testPluginFiles(BuildTests.java:182)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by merks** [comment]
@iloveeclipse 

As I mentioned in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1349#issuecomment-1718097187 those things are a mystery to me.  

The error message has exactly the right jar name:

org.eclipse.orbit.xml-apis-ext_1.0.0.v20230815-1152.jar

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/c0239d99-bed2-4b97-ad17-6b06f0d664d6)

which makes me wonder how it's missing when it knows exactly the correct name?

Do you have any ideas what exactly might needs changing?

**Comment by merks** [comment]
@iloveeclipse 

I think the test itself needs fixing:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/a1464d5f-2f88-453d-b60f-7da7da1be6b9)

The file isn't missing, it's named org.eclipse.orbit so it's being treated as a Eclipse project file, which it is not...

**Comment by akurtakov** [comment]
Yeah, looks like it has to be added to the exceptions like jetty and ecf.

**Comment by merks** [comment]
How does one see the javadoc logs for the other test failure?  The error message is rather 'black box'.

**Comment by akurtakov** [comment]
It's in the https://download.eclipse.org/eclipse/downloads/drops4/I20230913-1800/logs.php#javadoc . https://download.eclipse.org/eclipse/downloads/drops4/I20230913-1800/compilelogs/platform.doc.isv.javadoc.txt points that first failure is due to search.[core/ui] split and not being added to javadoc build.

**Comment by merks** [comment]
@akurtakov  

Thanks!  So that problem is unrelated and my additional PR just now should fix the test failure actually related to this issue's changes...

**Comment by merks** [comment]
@iloveeclipse 

Big compliments for finding and tracking such problem so quickly!

**Comment by laeubi** [comment]
> Or are you refering to something else?

Yes, see for example:
- https://github.com/eclipse-tycho/tycho/issues/93

> In general proper version ranges are of course good.

correct

> Only if the package comes from the JVM, there is no package version available.

Exactly, that's why it is dangerous to rely on **any** package that is not `java.*` from the JVM as these are vendor specific and might be provided with separate plugins as well.

> The a.jre.javase IU does provide it

This IU is actually a different problem because it is generated from one specific JVM or even hand-crafted, **there is no gurantee** that the runtime JVM provides it nor does P2 checks that a package is provided by the current JVM...

**Comment by mickaelistria** [comment]
Some time ago, we added a check for Java version by excluding the `a.jre` units from the resolution, and injecting a unit instead based on the currently running VM. This approach is not the one that fully drives the director as it's a preliminary check which is then discarded; but I believe this strategy could be implemented directly in the director, and that the generation of `a.jre.javase` units could then be abandoned.
And IMO, the best approach is now to embed JustJ. It makes everything straightfully without being polluted by a.jre.javase.
I would even advocate that, for the best interest of the community of maintainers and consumers; Platform's product should include the latest version of JustJ and thanks to it bother less about other jREs, at install and runtime ;)
