### ISSUE TITLE
Stop generating org.eclipse.rcp*.zip

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.releng.aggregator#135]
Download stats are pretty much non-existing (data from https://dev.eclipse.org/committers/committertools/stats.php ). Using 4.22 stats as 4.23 is just released so this shows the downloads in full cycle:
* org.eclipse.rcp-4.22.zip | 84
* org.eclipse.rcp.source-4.22.zip | 71

Not publishing and thus creating these files will simplify eclipse.platform.repository manual mirroring which is known to have limitations like not mirroring pgp signatures.

**Comment by akurtakov** [comment]
@sravanlakkimsetti wdyt?

**Comment by sravanlakkimsetti** [comment]
I am fine with this one. Lets wait for @vogella for his view on this one

**Comment by vogella** [comment]
More stuff which could IMHO be deleted:
![image](https://user-images.githubusercontent.com/139910/159488884-aa0adc9a-0b2d-4108-9c23-ca06be92fea8.png)

**Comment by akurtakov** [comment]
Nightly tests rely on the first 2 zips in your screenshots. The other two are to be removed in this issue.

**Comment by vogella** [comment]
One day we will use Tycho to run these tests instead of Ant. :-o cc @laeubi

**Comment by akurtakov** [comment]
If you want to drive such changes I'm all for that.

**Comment by sravanlakkimsetti** [comment]
> I see p2 director is used at https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/production/testScripts/configuration/sdk.tests/testScripts/test.xml#L525 and uses the actual build repository to gather necessary content. I believe this task could just be extended to install 1 root "test" feature and let p2 install everything necessary. If this works, there is no need for extra delivery of tests.

I was actually looking at this https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/a0d1042097db0a2aace78abf7f73777756eaa4ea/production/testScripts/configuration/sdk.tests/testScripts/test.xml#L534 here we are using file instead of repository. if we can move to repo, I think we can get rid of tests.

Also I think we install framework using online repository. its only the tests we use from zip.
