### ISSUE TITLE
Is org.glassfish.web.javax.servlet.jsp actually required?

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.releng.aggregator#1358]
The only requirement that I see on this IU is its inclusion in this feature:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/3783123c-3a74-4e34-beac-d022a3361eb2)

The help system works in the IDE without that bundle and the UA webapp tests pass without that bundle so I think it's not needed at all.

**Comment by akurtakov** [comment]
I think this one is leftover from previous attempt to remove the glassfish library which didn't work out so should be fairly safe to get rid of it.

**Comment by merks** [comment]
Yes, when I looked at the history, that was my impression too.  This removal should be much less painful and the last JSP changes!!
