### ISSUE TITLE
Are there bundles included by features that are unused?

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.releng.aggregator#1361]
I did an analysis of the Platform repository, excluding all features, to see if there are IUs that are not strictly required by anything, i.e., ones with no children in the view:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/377488a1-e98d-4e10-93fe-24d6834b2850)

I suspect these can be removed...

There are also these, but I think these are not present for use at runtime but rather are needed at development time, so that's okay:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/5a0adc73-3ae2-4343-b2d8-04dc02b28b00)

**Comment by HannesWell** [comment]
Sounds good to me.

> There are also these, but I think these are not present for use at runtime but rather are needed at development time, so that's okay:
> 
> ![image](https://user-images.githubusercontent.com/208716/268436888-5a0adc73-3ae2-4343-b2d8-04dc02b28b00.png)


Yes they are used by PDE:
https://github.com/eclipse-pde/eclipse.pde/blob/b01e2c4bffc42b5aecfe6479fffd6dd9c2495f8e/ui/org.eclipse.pde.core/src/org/eclipse/pde/internal/core/annotations/OSGiAnnotationsClasspathContributor.java#L44-L46

**Comment by akurtakov** [comment]
Is there something planned here?

**Comment by merks** [comment]
I think these can be removed and the appear to be present purely because features include them.

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/5a28462d-8228-4005-81a5-26abb1968c10)

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/328e592b-976b-4963-b131-8d85d7253804)

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/65881ee5-8504-4f8b-a359-b1ad65944114)

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/1777863a-fa58-4900-876e-f1380ba8c450)

So we could plan and try to remove them, though one is always concerned that something might stop working for unexpected reasons...

Looking at a one of these, it does appear that the exported packages that are _potentially_ used are provided by alternatives, e.g., mortbay:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/9b989699-a194-4464-a17f-cc6ada98cc2c)

So my sense is that this is accumulated baggage and that we might be well-served to clean it up...

What do you think?

**Comment by akurtakov** [comment]
Sounds the right thing to do to me.

**Comment by merks** [comment]
Looking closely at all the places to remove includes from features I found this feature:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/1465c29c-11e5-422c-84ce-d22c57663d88)

It appears to be an orphan that is not needed and not used; if I cleaned it up, it would be an empty feature!

Perhaps I start the cleanup process by removing this feature...

**Comment by merks** [comment]
Using some targlet magic I excluded the three bundles from the target platform and jasper bundle still compiles and the help still works:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/6244e18e-24ee-449f-8f44-ee5c343011b9)

**Comment by merks** [comment]
All the removals all complete.  We'll need to keep an eye on the next I-Build for regressions.
