### ISSUE TITLE
Switch Java 20 Linux build to Java 21

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1381]
[Java 21 is released](https://www.oracle.com/java/technologies/downloads/#java21), we should switch [ep430I-unit-cen64-gtk3-java20](https://ci.eclipse.org/releng/view/Builds/job/AutomatedTests/job/ep430I-unit-cen64-gtk3-java20/) build running on Java 20 now to Java 21 (create new one and run that instead of [ep430I-unit-cen64-gtk3-java20](https://ci.eclipse.org/releng/view/Builds/job/AutomatedTests/job/ep430I-unit-cen64-gtk3-java20/)).

I have no idea if Java 21 is available in our infra, I guess a ticket is needed.

@MohananRahul : could you take care of this task?

**Comment by merks** [comment]
FYI, 

I still could not find it here:

https://adoptium.net/temurin/releases/

Of course I'd like to create JustJ JREs for it, but the ones I did find are all still labeled "beta"...

**Comment by iloveeclipse** [comment]
@MohananRahul : thanks for creating the job definition.

Some more questions: 
- Could you please create it on jenkins?
- Could you please check with the infra team if the Java 21 is already available on eclipse.org servers?

**Comment by iloveeclipse** [comment]
@akurtakov : it is safe to run that job at any time? (I Build is running right now).

**Comment by akurtakov** [comment]
Relatively so. Running jobs will not be affected but if the job calls another one (like the tests) and they are modified breakage may occur.

**Comment by iloveeclipse** [comment]
OK, I will run it after the build finishes.

**Comment by iloveeclipse** [comment]
> OK, I will run it after the build finishes.

Done, see https://ci.eclipse.org/releng/job/Create%20Jobs/85/

Now we have https://ci.eclipse.org/releng/job/AutomatedTests/job/ep430I-unit-cen64-gtk3-java21/.

Next: get it running, or will it automatically run on next I Build?

**Comment by akurtakov** [comment]
Next I-build should run it as per https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/3dcf9ffa164422d7a8a4c3f1cd80ed2e6668a16f/JenkinsJobs/Builds/I_build.groovy#L510 and results will be visible in jenkins but publishing will fail as https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/3dcf9ffa164422d7a8a4c3f1cd80ed2e6668a16f/eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/staticDropFiles/testConfigs.php#L17 (and maybe others) would still be looking for Java 20 test results.

**Comment by akurtakov** [comment]
The following files refer to java20 configs and have to be changed/updated (Y-build ones are questionable as I'm not sure about the process there) :
JenkinsJobs/SmokeTests/StartSmokeTests.groovy
JenkinsJobs/YBuilds/Y_build.groovy
cje-production/Y-build/testConfigs.php
cje-production/scripts/publish.xml
eclipse-platform-parent/pom.xml
eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/staticDropFiles/testConfigs.php

**Comment by iloveeclipse** [comment]
Okm, with build I20230922-0140 we have Java 21 test results: https://download.eclipse.org/eclipse/downloads/drops4/I20230922-0140/testResults.php
