### ISSUE TITLE
org.eclipse.help feature shows "warnings" on many platform bundles

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1432]
Follow up on https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1419, side effect of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1384

`org.eclipse.help` feature shows "warnings" on many platform bundles (seen in older builds as also in latest I20231010-1800):
![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/964108/dcfb582b-d6ee-4173-930f-7c9bb50bad39)

**Comment by iloveeclipse** [comment]
I have wrongly assumed it's due out-of-date bundles (because of older timestamps like org.eclipse.equinox.jsp.jasper.registry), but turned out the bundle versions were correct.

Also it is impossible to open bundle manifest by double clicking on "warning" bundle. Looks like PDE issue => I will create it for PDE.

**Comment by akurtakov** [comment]
Should this one be closed now?

**Comment by iloveeclipse** [comment]
It would make sense to show tooltips / statusline with explanation of the warning, or give some other way a hint where the problem is.

**Comment by akurtakov** [comment]
Please create a dedicated report in PDE about this issue in this case and then close this one.

**Comment by iloveeclipse** [comment]
> Please create a dedicated report in PDE about this issue in this case and then close this one.

https://github.com/eclipse-pde/eclipse.pde/issues/796
