### ISSUE TITLE
Remove includes of org.eclipse.jetty bundles from org.eclipse.help feature

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.releng.aggregator#1444]
The following includes of org.eclipse.jetty.* bundles seem questionable:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/f5926b5138ccb030a1f097f01a62276eba728833/eclipse.platform.releng/features/org.eclipse.help-feature/feature.xml#L108-L148

One problem here is that the help feature locks in a very specific version of Jetty, but downstream clients may also be using Jetty for other purposes.  Also, there may well be releases of Jetty with bug fixes or CVE fixes after the Platform has released.  It would be good for it to possible for downstream clients to install an updated compatible version of Jetty.

Analyzing a Platform update site, these are the Jetty bundles in the site along with their non-feature-based dependencies:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/0ad73562-a1e6-49b4-a6ac-515bff169653)

Firstly note that there are a bunch of Jetty bundles not included by the feature.  Secondly note that the org.eclipse.jetty.util.ajax bundle appears not to be required at all, other than the feature inclusion.

I think we can simply remove the includes.

**Comment by akurtakov** [comment]
Most likely these are remnants from the past when tooling wasn't good enough to automate things.

**Comment by merks** [comment]
The following includes are questionable as well:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/5f190b81-855d-4034-9565-794bfeb820bd)

**Comment by merks** [comment]
The org.eclipse.equinox.server.jetty feature only has bundle imports, but these are unbounded and appear to provide no value.  It also imports org.eclipse.jetty.util.ajax which appears unused so does worse than provide no value.
