### ISSUE TITLE
Default Eclipse JVM should not have -XmX parameter

### ISSUE THREAD

**Issue by grandinj** [eclipse-platform/eclipse.platform.releng.aggregator#1463]
I have noticed that recent installers, when using the default supplied VM to run Eclipse, has an -XmX parameter.

This leads to an extremely frustrating experience with large projects. I suddenly found my debugger doing all sorts of very weird things, which led to a loooooooong goose chase before I found the cause.

Either
(a) the platform needs some indication that it is running into memory issues
(b) just leave that parameter out, in which case the VM will grow to use available memory on the machine.

(I vote for option b)

Thanks.

**Comment by iloveeclipse** [comment]
I believe option (b) makes sense. On "usual" working environments today we have way more RAM as before and JVM would "automatically" reserve more than default 2GB (SDK sets `-Xms256m -Xmx2048m` in the sdk.product). 

The only problem I see "smaller" configurations like Jenkins platform builds that usually suffer from too strict resources limits and where JVM would set smaller heap. 
But there we could set VM heap limits in Jenkins files.

**Comment by merks** [comment]
FYI, this issue was discussed here as well:

https://github.com/eclipse-packaging/packages/issues/37

Most folks are using one of the EPP packages, so what the Platform does has much narrower impact than what EPP does...

**Comment by jonahgraham** [comment]
As I mentioned in https://github.com/eclipse-packaging/packages/issues/37#issuecomment-1656967319 the EPP normally aims to follow where the Platform/SDK leads. This has been the case because we used to inherit the Platform settings, that was changed [recently(ish)](https://github.com/eclipse-packaging/packages/commit/a6b90b060b8c3684596e691254bf2f74a559b8aa#diff-16e6384c25129c8b79f16290a9820ce1f15fbbce94fddcd6f14d39996078ceb5) which gives us the option to drop the xmx from EPP.

In this case perhaps EPP should lead and platform/SDK can follow along later?

**Comment by iloveeclipse** [comment]
> In this case perhaps EPP should lead and platform/SDK can follow along later?

Or we can just try to do this in SDK and see if something breaks on Jenkins/official build & fix Jenkins files etc in case we still need Xmx option. I will push a PR in a moment.

**Comment by iloveeclipse** [comment]
> Or we can just try to do this in SDK and see if something breaks on Jenkins/official build & fix Jenkins files etc in case we still need Xmx option.

Any objections? => https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1471

**Comment by iloveeclipse** [comment]
So far there were no regressions in the SDK tests, we will see if some Jenkins jobs would fail.

The default SDK `eclipse.ini` looks like this now (Linux build):

```
-startup
plugins/org.eclipse.equinox.launcher_1.6.600.v20231012-1237.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.800.v20231003-1442
--launcher.defaultAction
openFile
--launcher.appendVmargs
-vmargs
-Dosgi.requiredJavaVersion=17
-Dosgi.dataAreaRequiresExplicitInit=true
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
--add-modules=ALL-SYSTEM
-Dorg.slf4j.simpleLogger.defaultLogLevel=off
-Djava.security.manager=allow
```

**Comment by laeubi** [comment]
> It also looks like there are multiple tasks running in parallel

Platform build is executed in parallel

> Which Eclipse/tycho task has reported [ERROR] java.lang.OutOfMemoryError: Java heap space? Is it org.eclipse.core.tests.resources test? Something else?

You can see the limits here: https://ci.eclipse.org/platform/job/eclipse.platform/job/PR-731/5/consoleText

```
  resources:
      limits:
        cpu: "2000m"
        memory: "4096Mi"
      requests:
        cpu: "1000m"
        memory: "4096Mi"
```

but I don't really understand how `eclipse.ini` relates to Jenkins build execution... so if we know how/if this makes a difference there might be a way to further configure this, e.g. for maven one would use `.mvn/jvm.config` but tests are using different setting depending on they are forked or not...

**Comment by iloveeclipse** [comment]
> but I don't really understand how `eclipse.ini` relates to Jenkins build execution...

If the tycho starts SDK product during tests, it uses `eclipse.ini` we've changed in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1471. 

I honestly don't know what tycho does to construct the test application and if that inherits `eclipse.ini` coming from the SDK product. If tycho based test instance inherits that file, it also doesn't use `-XmX2g` defaults anymore and probably uses only 1GB heap (1/4 from machine RAM on Jenkins).

But still open question: any clue **which task** has reported OOM?

**Comment by laeubi** [comment]
> But still open question: any clue which task has reported OOM?

`infocenter-product 1.0.0-SNAPSHOT .................. FAILURE [  7.372 s]`

is the module failing the build, but this might only be a side-effect of the JVM itsel running out of memmory, thats why I said, I can't see that a **PROCESS** (that can read eclipse.ini) is failing, the JVM that running the **BUILD** seems going OOM...

**Comment by laeubi** [comment]
If you want to share things in common, it is best placed here in `pluginManagement` section of the build:
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse-platform-parent/pom.xml

**Comment by iloveeclipse** [comment]
> infocenter-product 1.0.0-SNAPSHOT .................. FAILURE

I don't see which / where is this FAILURE reported in the log (above the table)? The last relevant entry I see is an INFO
`10:16:48.454 [INFO] --- tycho-p2-repository:4.0.4-SNAPSHOT:assemble-repository (default-assemble-repository) @ infocenter-product`

**Comment by iloveeclipse** [comment]
> If you want to share things in common, it is best placed here in `pluginManagement` section of the build: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse-platform-parent/pom.xml

So this line has to be adopted to have `-Xmx` option: 
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/10afb28126eb07236c1ba6d118ffd4314cdda8e8/eclipse-platform-parent/pom.xml#L529

**Comment by iloveeclipse** [comment]
Change is reverted, due possibility that is causes OOM in Jenkins builds.
If someone sees OOM's an platform jenkims builds **after** next IBuild, please comment here.

**Comment by iloveeclipse** [comment]
OK, looks like we see OOM's elsewhere without this patch, see https://github.com/eclipse-platform/eclipse.platform/pull/764.

So I plan to re-submit https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1471 as soon as we have solution for more RAM on Jenkins, see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3885 .

**Comment by iloveeclipse** [comment]
https://github.com/eclipse-platform/eclipse.platform/pull/784 provided now 8 GB RAM for Platform builds on Jenkins, let see if that helped or not.

**Comment by jonahgraham** [comment]
Has there been any negative effects of this? EPP will make this same change too unless someone raises a concern inhttps://github.com/eclipse-packaging/packages/issues/37

**Comment by iloveeclipse** [comment]
> Has there been any negative effects of this?

Only for poor VM (Jenkins) instances with <= 4GB RAM. 

For PC's/VM's with >=8 GB everything should be fine.

**Comment by merks** [comment]
I have 128GB of RAM.  Without any memory options I don't see Eclipse grabbing too much space on startup.  The upper limit to which it can grow might be very high.  But it seems okay to me.
