### ISSUE TITLE
Google calendar from "check-freeze-period" build step cannot be opened

### ISSUE THREAD

**Issue by marcushoepfner** [eclipse-platform/eclipse.platform.releng.aggregator#1544]
The [check freeze build](https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/6874432867/job/18696089971?pr=1283) tells me to open https://calendar.google.com/calendar/u/0/r?cid=calendarId=prfk26fdmpru1mptlb06p0jh4s@group.calendar.google.com which seems to be broken.

At least I cannot add/import this calendar. Also manually adding by URL does not work.

BTW: If I don't have a google account I cannot open this link at all. Can this be moved to some other "calendar service"?

**Comment by laeubi** [comment]
https://github.com/eclipse-simrel/.github/blob/main/wiki/SimRel/2023-12.md has a link to

https://calendar.google.com/calendar/embed?src=gchs7nm4nvpm837469ddj9tjlk@group.calendar.google.com&dates=20231201%2F20231231&hl=en&mode=AGENDA

what seem to work ...

**Comment by marcushoepfner** [comment]
Thanks. Can you kindly "repair" this in the freeze build?

**Comment by sratz** [comment]
> https://calendar.google.com/calendar/embed?src=gchs7nm4nvpm837469ddj9tjlk@group.calendar.google.com&dates=20231201%2F20231231&hl=en&mode=AGENDA

That's the simrel calendar.

The correct one is the platform calendar.

URL https://calendar.google.com/calendar/u/0/embed?src=prfk26fdmpru1mptlb06p0jh4s@group.calendar.google.com works.

See #1545

**Comment by HannesWell** [comment]
> URL https://calendar.google.com/calendar/u/0/embed?src=prfk26fdmpru1mptlb06p0jh4s@group.calendar.google.com works.

That's right. But the main issue was that there is a superfluous `calendarId=`.

> BTW: If I don't have a google account I cannot open this link at all. Can this be moved to some other "calendar service"?

Switching from `r?cid=` to `embed?src=` seems to allow that. At least when I lock-out from my Google account I can see the calendar with the latter but not with the former.

**Comment by marcushoepfner** [comment]
Thank you
