### ISSUE TITLE
Add Ubuntu 22.04 test run in smoke tests

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#160]
Docker image for Ubuntu 22.04 is already available. Need to create our own custom docker image, and use it in smoke tests

**Comment by akurtakov** [comment]
Ubuntu 18.04 will be dropped at the same time, right? We support last two LTS releases only.

**Comment by sravanlakkimsetti** [comment]
> Ubuntu 18.04 will be dropped at the same time, right? We support last two LTS releases only.

We will drop testing 21.10. I did not realize that we support last Two LTS releases only. We can drop 18.04 as well. If we drop 18.04, There is one hidpi implementation I would like to remove.

**Comment by akurtakov** [comment]
As per https://wiki.eclipse.org/Eclipse/PMC/Minutes_2018 (June 05, 2018) only last LTS is in our target environment but automated tests for the previous one could still be run if feasible. Now, 3 is a bit more than what we should load our infrastructure.
Is the hidpi implementation Ubuntu 18.04 specific or Gtk 3.22 specific? If the later note that Gtk 3.22 is still SWT's min requirement.

**Comment by sravanlakkimsetti** [comment]
In this case we can drop Ubuntu 18.04. The hidpi problem is noticed only on ubuntu 18. I was planning to remove extra code once we drop support to ubuntu 18. Lets keep the hidpi implementation for now.
