### ISSUE TITLE
Wrong classname for Parameterized Tests on jenkins

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.releng.aggregator#1630]
for example org.eclipse.equinox.common.tests.text.StringMatcherFindTest 
results in junit result XMLs like

`    <testcase classname="[line 50: NOK pattern=a*bc*d, text=.abeced[0,7]]" name="testFind[line 50: NOK pattern=a*bc*d, text=.abeced[0,7]]" time="0.0" />
`
which jenkins shows like

`https://ci.eclipse.org/releng/job/AutomatedTests/job/ep431I-unit-win32-java17/lastSuccessfulBuild/testReport/[line%20103_%20OK%20pattern=*a*b*g*n*t,%20text=abcd_abcdefg_abcdefghijk_abcdefghijklmnop/txt]/testStringMatchCaseInsensitive_line_103__OK_pattern__a_b_g_n_t__text_abcd_abcdefg_abcdefghijk_abcdefghijklmnop_txt_/`

the "classname" in the xml is wrong.

https://openclover.org/doc/manual/4.2.0/maven--surefire-and-junit4-parameterized-tests.html
say we have to add JUnitTestRunnerInterceptor to maven-surefire-plugin

**Comment by jukzi** [comment]
Causes SWT builds to fail :-(
Idea anybody how to solve, or revert?

**Comment by akurtakov** [comment]
https://github.com/eclipse-platform/eclipse.platform.swt/pull/933#issuecomment-1842208154

**Comment by jukzi** [comment]
How to "dependency to this one being added in the surefire configuration (dependency tag) " ? Can we try to?

**Comment by akurtakov** [comment]
https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit.html#using-custom-listeners-and-reporters

**Comment by akurtakov** [comment]
Please test with swt locally whether your change works.

**Comment by jukzi** [comment]
> Please test with swt locally whether your change works.

I have no clue how todo so, i never build locally. please instruct

**Comment by akurtakov** [comment]
`mvn clean verify` in eclipse.platform.swt repo with eclipse.platform.swt.binaries being next to it.

**Comment by laeubi** [comment]
> > Please test with swt locally whether your change works.
> 
> I have no clue how todo so, i never build locally. please instruct

The Jenkinsfile gives you a hint how to execute this on your machine.

Beside that I have no clue what "clover" is and where we use it but wanted to mention that the tests are not executed with standard [maven-surefire-plugin](https://maven.apache.org/surefire/maven-surefire-plugin/), for verification builds it uses [tycho-surefire-plugin](https://tycho.eclipseprojects.io/doc/latest/tycho-surefire-plugin/plugin-info.html) and the I-Builds use[ something totally different](https://wiki.eclipse.org/Platform-releng/Automated_Testing)!

**Comment by iloveeclipse** [comment]
> > Please test with swt locally whether your change works.
> 
> I have no clue how todo so, i never build locally. please instruct

@jukzi : in case you are not sure how to proceed, I would prefer to revert this PR and get SDK build running again.
I've created https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1640 for tracking this issue.

**Comment by laeubi** [comment]
https://github.com/openclover/clover-examples/blob/master/parameterized-junit4-example/pom.xml shows it needs 

```
<dependency>
    <groupId>org.openclover</groupId>
    <artifactId>clover</artifactId>
    <version>4.4.1</version>
</dependency>
```

somehow to work ...
