### ISSUE TITLE
The 4.31-I-builds composite is accumulating way too many children

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.releng.aggregator#1646]
## Steps to reproduce

If you look at  this:

https://www.eclipse.org/downloads/download.php?file=/eclipse/updates/4.31-I-builds/compositeContent.jar

It has these children:
```
  <children size='15'>
    <child location='categories'/>
    <child location='I20231128-0510'/>
    <child location='I20231128-1030'/>
    <child location='I20231128-1800'/>
    <child location='I20231130-0020'/>
    <child location='I20231130-0550'/>
    <child location='I20231202-0500'/>
    <child location='I20231202-1800'/>
    <child location='I20231203-0800'/>
    <child location='I20231203-1800'/>
    <child location='I20231204-0730'/>
    <child location='I20231204-1800'/>
    <child location='I20231205-0520'/>
    <child location='I20231206-0410'/>
    <child location='I20231206-1800'/>
  </children>
```

It seems to me this is way too many children. I think in the past it was limited to 5.

This repository is heavily used downstream and forcing each downstream consumer to load 15 repositories is really bad in my opinion,.  Not just bad for the client, but bad for the download.eclipse.org server.

@MohananRahul 

I'm not sure where the limit on the composite is controlled.

**Comment by MohananRahul** [comment]
@merks This https://ci.eclipse.org/releng/job/Cleanup/job/dailyCleanOldBuilds/ was disabled for release process. 
Now it is enable and ran the job. Please note I will Split up this job so that we will never encounter this issue again.

**Comment by merks** [comment]
That was fast.  🚀   Thanks. 😄
