### ISSUE TITLE
Buid I20231208-1800 is unstable

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1653]
See
- https://download.eclipse.org/eclipse/downloads/drops4/I20231208-1800/
- https://download.eclipse.org/eclipse/downloads/drops4/I20231208-1800/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

Looks like most bundles from the **[platform repository](https://github.com/eclipse-platform/eclipse.platform)** were affected.

I assume this is caused by https://github.com/eclipse-platform/eclipse.platform/pull/965 that changed build settings for compilation with maven.

The most intriguing question is: **which** settings were used before???

I will check that later.

**Comment by iloveeclipse** [comment]
> which settings were used before???

@laeubi : I would be interested in your opinion regarding this question. Is that maven/tycho/ecj who defines defaults if nothing is specified? Or do we have some default "profile" or whatever that is used in such case?

**Comment by laeubi** [comment]
First, ecj defaults are used (not sure where these are defined) then compiler args are used (e.g. https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/888de3410f302c380ca3f7c0fabcc225d6a0fa39/eclipse-platform-parent/pom.xml#L473-L507), what then now is [overridden here](https://github.com/eclipse-platform/eclipse.platform/pull/965) to use the project specific settings file, see https://tycho.eclipseprojects.io/doc/latest/tycho-compiler-plugin/compile-mojo.html#useProjectSettings if file `${project.basedir}/.settings/org.eclipse.jdt.core.prefs` can be found by tycho.

**Comment by HannesWell** [comment]
@iloveeclipse is it correct that unstable builds are not added to the i-builds composite and therefore I cannot use the methods added in https://github.com/eclipse-equinox/equinox/pull/424 in https://github.com/eclipse-platform/eclipse.platform/pull/972?

**Comment by iloveeclipse** [comment]
Exact. Until we have a stable build we can't move forward. Makes sense.

**Comment by iloveeclipse** [comment]
Ome can revert https://github.com/eclipse-platform/eclipse.platform/pull/965 as a quick fix.

**Comment by HannesWell** [comment]
> Exact. Until we have a stable build we can't move forward. Makes sense.

Absolutely. Just wanted to confirm it. :)

> Ome can revert [eclipse-platform/eclipse.platform#965](https://github.com/eclipse-platform/eclipse.platform/pull/965) as a quick fix.

Yes. I although I wonder what can be configured in the settings that only changes the generated byte-code?

Looking for example at
https://github.com/eclipse-platform/eclipse.platform/blob/a5789fbe6b8787def560cc10ed086c50f3662980/runtime/bundles/org.eclipse.core.jobs/.settings/org.eclipse.jdt.core.prefs#L12-L15

I would say it is probably on of
```
`inlineJsrBytecode=enabled`
`methodParameters=do not generate`
`codegen.unusedLocal=preserve`
```

**Comment by akurtakov** [comment]
unusedLocal=preserve looks wrong to me and my gut feeling is that this is the reason why POP is replaced by ASTORE

**Comment by iloveeclipse** [comment]
I haven't investigated this deeper, so no proposal from my side here.

**Comment by HannesWell** [comment]
Looking at the build logs of a PR from eclipse.platform I see so it is reproducible (but doesn't fail the build)
```
10:22:25.107 [WARNING] MavenProject: org.eclipse.platform:org.eclipse.core.jobs:3.15.200-SNAPSHOT @ /home/jenkins/agent/workspace/eclipse.platform_PR-971/runtime/bundles/org.eclipse.core.jobs/.polyglot.META-INF: baseline and build artifacts have same version but different contents
   no-classifier: different
      org/eclipse/core/internal/jobs/ImplicitJobs.class: different
      org/eclipse/core/internal/jobs/InternalWorker.class: different
      org/eclipse/core/internal/jobs/JobListeners.class: different
      org/eclipse/core/internal/jobs/JobManager.class: different
      org/eclipse/core/internal/jobs/LockManager$LockState.class: different
      org/eclipse/core/internal/jobs/LockManager.class: different
      org/eclipse/core/internal/jobs/OrderedLock.class: different
      org/eclipse/core/internal/jobs/ThreadJob.class: different
      org/eclipse/core/internal/jobs/Worker.class: different
      org/eclipse/core/internal/jobs/WorkerPool.class: different
```

I'll try out a few options and check the results in a PR.
In general we could consider to fail the build in such cases by setting `-Dtycho.p2.baselineMode` to a corresponding value.

**Comment by akurtakov** [comment]
What is the status here? If there is no fix in the next couple of hours I'll partially revert the patch causing it to not change compiler options.

**Comment by HannesWell** [comment]
I cannot help on this issue any more before this evening.
For me there is some input/knowledge missing at the moment.
But since a soonish resultion is desired anybody else has to take action based on what has been said already.

**Comment by akurtakov** [comment]
We can not afford continuing without a build - that's for sure. Improving/changing/etc. is always welcome and should come when this missing input/knowledge is gathered and the changes are better needed and executed in more integral way.

**Comment by jukzi** [comment]
good morning, ill take a look now

**Comment by jukzi** [comment]
The only "codgen" options that ecj changes in "org.eclipse.jdt.internal.compiler.batch.Main.initializeWarnings(String)" (when using parameter `-properties {file}`) seems to be `org.eclipse.jdt.core.compiler.codegen.unusedLocal`.
As far as i understand the unusedLocal is by default "optimize out" when not parameter is given but defaults to "preserve" when jdt UI or ecjs `-properties` is used

**Comment by srikanth-sankaran** [comment]
> unusedLocal=preserve looks wrong to me and my gut feeling is that this is the reason why POP is replaced by ASTORE

See https://github.com/eclipse-platform/eclipse.platform/pull/973#issuecomment-1849674611

**Comment by iloveeclipse** [comment]
There is now a jface error: https://download.eclipse.org/eclipse/downloads/drops4/I20231211-0340/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

**Comment by iloveeclipse** [comment]
OK, I see Alex created https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1655 for that.

**Comment by akurtakov** [comment]
I have opened https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1655 as it's api_description file this time so most likely different issue.
