### ISSUE TITLE
Build I20231211-0340 unstable (comparator issue)

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.releng.aggregator#1655]
As can be seen at https://download.eclipse.org/eclipse/downloads/drops4/I20231211-0340/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt :
```
Comparator differences from current build
	/home/jenkins/agent/workspace/Builds/I-build-4.31/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/siteDir/eclipse/downloads/drops4/I20231211-0340
compared to reference repo at 
	https://download.eclipse.org/eclipse/updates/4.31-I-builds

1.  eclipse.platform.ui/bundles/org.eclipse.jface/.polyglot.META-INF
   no-classifier: different
      .api_description: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

```

**Comment by iloveeclipse** [comment]
> `.api_description: different`

@laeubi : any hints what this is supposed to say us, where it is coming from?

**Comment by iloveeclipse** [comment]
Note: this error was hidden by others and was first reported in https://download.eclipse.org/eclipse/downloads/drops4/I20231210-2110/
https://download.eclipse.org/eclipse/downloads/drops4/I20231210-2110/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

**Comment by akurtakov** [comment]
Now I wonder, wouldn't https://github.com/eclipse-pde/eclipse.pde/pull/913 combined with migrating to actually using the annotations give us a more standard situation where analysis can be seen on class level rather than this one off format no one knows about nor where it actually comes from.

**Comment by laeubi** [comment]
> > `.api_description: different`
> 
> @laeubi : any hints what this is supposed to say us, where it is coming from?

This one is generated by API tools and Tycho has recently upgraded to latest PDE, can one see the actual difference here? This is ultimately done by [ApiFileGenerationMojo](https://github.com/eclipse-tycho/tycho/blob/master/tycho-apitools-plugin/src/main/java/org/eclipse/tycho/apitools/ApiFileGenerationMojo.java) and as one can see this literally calls the [APIFileGenerator](https://github.com/eclipse-pde/eclipse.pde/blob/master/apitools/org.eclipse.pde.api.tools/src/org/eclipse/pde/api/tools/internal/APIFileGenerator.java) here, so I have no special insights nor changed anything in Tycho in this regard (beside the PDE upgrade) as I only written the wrapper some time ago but have not analyzed where this file is needed/used.

**Comment by akurtakov** [comment]
The actual diff I see in .api_description baseline and my local build is :
```
--- /home/akurtakov/git/eclipse.platform.ui/bundles/org.eclipse.jface/target/baseline/.api_description
+++ /home/akurtakov/git/eclipse.platform.ui/bundles/org.eclipse.jface/target/.api_description
@@ -34,6 +34,7 @@
         <type name="FontRegistry" restrictions="2"/>
         <type name="ImageRegistry" restrictions="2"/>
         <type name="JFaceResources" restrictions="6"/>
+        <type name="LazyResourceManager" restrictions="8"/>
         <type name="ResourceLocator" restrictions="4"/>
         <type name="StringConverter" restrictions="6"/>
     </package>
```

**Comment by laeubi** [comment]
@akurtakov I think this is because of

- https://github.com/eclipse-pde/eclipse.pde/pull/913

now **the only place** ([LazyResourceManager](https://github.com/eclipse-platform/eclipse.platform.ui/blob/12ff8bc994bce2f5d7164b558d6841086a76eaf6/bundles/org.eclipse.jface/src/org/eclipse/jface/resource/LazyResourceManager.java#L27)) that actually uses the annotation is now discovered and end up the the description file (finally).

**Comment by akurtakov** [comment]
Makes sense. So up until now the api_description was incomplete in binaries. This can actually explain why there have been differences between workspace and builds in various cases. I'll do some minor change in the bundle to get it rebuilt.

**Comment by laeubi** [comment]
> I'll do some minor change in the bundle to get it rebuilt.

You can add more class versus javadoc annotations :-D

**Comment by iloveeclipse** [comment]
https://download.eclipse.org/eclipse/downloads/drops4/I20231211-0900/ is stable. Thanks Alex!
