### ISSUE TITLE
Deploy ecj snapshot and use in parent pom to build SDK

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1668]
Now all verification builds show numerous of warnings like:

```
[WARNING] MavenProject: org.eclipse.pde:org.eclipse.pde.build.tests:1.4.300-SNAPSHOT @ /home/jenkins/agent/workspace/eclipse.pde_PR-1010/build/org.eclipse.pde.build.tests/.polyglot.META-INF: baseline and build artifacts have same version but different contents
no-classifier: different
org/eclipse/pde/build/internal/tests/AssembleTests.class: different
org/eclipse/pde/build/internal/tests/ScriptGenerationTests.class: different
org/eclipse/pde/build/internal/tests/SourceTests.class: different
org/eclipse/pde/build/internal/tests/Utils.class: different
org/eclipse/pde/build/internal/tests/p2/LicenseTests.class: different
org/eclipse/pde/build/internal/tests/p2/P2TestCase.class: different
org/eclipse/pde/build/internal/tests/p2/P2Tests.class: different
org/eclipse/pde/build/internal/tests/p2/PublishingTests.class: different
org/eclipse/pde/build/tests/PDETestCase.class: different
```

because verification builds use the default ECJ compiler and not the latest-and-greatest... so I think there must be a deploy and parent pom must use new ECJ compiler.

_Originally posted by @laeubi in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1659#issuecomment-1858129712_

**Comment by iloveeclipse** [comment]
@MohananRahul : I forgot where is the job that triggers latest ecj deployment? Can you please trigger it to deploy latest snapshot, so SDK build can use it in pom file?

**Comment by MohananRahul** [comment]
> @MohananRahul : I forgot where is the job that triggers latest ecj deployment? Can you please trigger it to deploy latest snapshot, so SDK build can use it in pom file?

Configured, Please run https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/ once it done, merge Update ECJ PR : https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1671

**Comment by iloveeclipse** [comment]
Triggered https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/159/, restarted PR build to see if everything works.

**Comment by iloveeclipse** [comment]
> > @MohananRahul : I forgot where is the job that triggers latest ecj deployment? Can you please trigger it to deploy latest snapshot, so SDK build can use it in pom file?
> 
> Configured, Please run https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/ once it done, merge Update ECJ PR : #1671

Thanks @MohananRahul! I think we are done here now.
