### ISSUE TITLE
Mac builds DNF since days

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1669]
See https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4055
Example:
- https://download.eclipse.org/eclipse/downloads/drops4/I20231215-0520/testResults.php

Our Mac M1 builds fail for no obvious reason.
We should investigate if that is platform issue or environment / OS issue.

A committer with Mac access is welcome to check if the recent builds can be used on Mac in general, show some unexpected errors etc. Ideally run tests on Mac and see if they show something special.

**Comment by BeckerWdf** [comment]
I downloaded 

https://download.eclipse.org/eclipse/downloads/drops4/I20231215-0520/download.php?dropFile=eclipse-SDK-I20231215-0520-macosx-cocoa-aarch64.dmg

I could start it without problems. I also created a java project and could compile it and execute it.
So from this smoke-test everything looks fine.

**Comment by iloveeclipse** [comment]
Thanks Matthias, that corresponds to what I see on builds behavior. Every second passes, which means, the instability must be  somewhere in the infrastructure / environment.
