### ISSUE TITLE
Migration of website repositories

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#168]
Need to migrate 

- [eclipse/news.git](https://git.eclipse.org/c/www.eclipse.org/eclipse/news.git/)
- [eclipse.git](https://git.eclipse.org/c/www.eclipse.org/eclipse.git/)

Requested the process for this as these needs to be published to the website automatically. Ref [Migration of documentation repositories](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1092)

**Comment by merks** [comment]
FYI, I've updated the setups to use these new URIs for cloning.

https://git.eclipse.org/c/oomph/org.eclipse.oomph.git/commit/?id=37a3d41115a11c58682f2ae18766ff023231d770

**Comment by sravanlakkimsetti** [comment]
Created temporary jobs to sync github and gerrit repos. 

- [Sync_eclipse_website_repo](https://ci.eclipse.org/releng/view/Miscellaneous/job/Sync_eclipse_website_repo/)
- [Sync_news_website_repo](https://ci.eclipse.org/releng/view/Miscellaneous/job/Sync_news_website_repo/)

Lets wait for a proper publishing solution before continuing with other website repos(jdt, equinox and pde)
