### ISSUE TITLE
I20231219-1800 - BUILD FAILED, I20231220-0500 unstable

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1682]
See https://ci.eclipse.org/releng/job/Builds/job/I-build-4.31/50/console

```
01:18:15  [apitooling.analysis] ==========================
01:18:15  [apitooling.analysis] API tools verification check : 33631ms
01:18:15  
01:18:15  BUILD FAILED
01:18:15  /home/jenkins/agent/workspace/Builds/I-build-4.31/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/eclipse.platform.releng.tychoeclipsebuilder/eclipse/buildScripts/api-tools-builder.xml:115: java.lang.ArrayIndexOutOfBoundsException
01:18:15  
01:18:15  Total time: 50 seconds
01:18:16  An error has occurred. See the log file
01:18:16  /home/jenkins/agent/workspace/Builds/I-build-4.31/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/tmp/workspace-apitoolingsLogs/.metadata/.log.
01:18:16  + [[ 13 -ne 0 ]]
01:18:16  + echo 'Failed in Generate API tools reports stage'
01:18:16  Failed in Generate API tools reports stage
01:18:16  + exit 1
```

**Comment by laeubi** [comment]
Last time it helped to simply restart the build.

**Comment by iloveeclipse** [comment]
> Last time it helped to simply restart the build.

https://ci.eclipse.org/releng/job/Builds/job/I-build-4.31/51/

**Comment by iloveeclipse** [comment]
This looks like a side effect of https://github.com/eclipse-platform/eclipse.platform.swt/pull/947 change.
"Touching" affected fragments should be solution, I'm looking into that now.

**Comment by HeikoKlare** [comment]
> This looks like a side effect of [eclipse-platform/eclipse.platform.swt#947](https://github.com/eclipse-platform/eclipse.platform.swt/pull/947) change.
> "Touching" affected fragments should be solution, I'm looking into that now.

Does that mean that we always have to force a qualifier update on SWT fragments once we commit changes to the SWT bundle?

**Comment by iloveeclipse** [comment]
> Does that mean that we always have to force a qualifier update on SWT fragments once we commit changes to the SWT bundle?

Honestly, I can't say for sure, @laeubi: I believe the switch from PDE API application used by tycho to tycho rew-implemented API check could be the root cause. May be we had a "special" case for SWT handling, as SWT source is shared between fragments. I can't remember we needed to do that before in SWT.

**Comment by iloveeclipse** [comment]
Triggered https://ci.eclipse.org/releng/job/Builds/job/I-build-4.31/52/ to get new **stable** build.

**Comment by laeubi** [comment]
> I believe the switch from PDE API check application used by tycho to tycho new re-implemented API check could be the root cause. 

For what? The previous failing step did not use Tycho (it calls ant) uses, the baseline compare has nothing to do with API tools... I just remember there was some problems with SWT build qualifier computation (overflow?) and something was adjusted I think @mickaelistria was involved there.

**Comment by iloveeclipse** [comment]
Argh, sorry, too many bugs. That's not API tools related, right.

**Comment by iloveeclipse** [comment]
Build https://download.eclipse.org/eclipse/downloads/drops4/I20231220-0750/ is stable.
