### ISSUE TITLE
Build: I20231221-1800 Unstable

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1686]
Build: I20231221-1800 has comparator errors.

- https://download.eclipse.org/eclipse/downloads/drops4/I20231221-1800/
- https://download.eclipse.org/eclipse/downloads/drops4/I20231221-1800/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt
- https://download.eclipse.org/eclipse/downloads/drops4/I20231221-1800/buildlogs/comparatorlogs/artifactcomparisons.zip

```
1.  equinox/bundles/org.eclipse.osgi/pom.xml
   no-classifier: different
      org/eclipse/osgi/internal/framework/SystemBundleActivator.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

2.  eclipse.platform.ui/bundles/org.eclipse.e4.ui.css.core/.polyglot.META-INF
   no-classifier: different
      org/eclipse/e4/ui/css/core/dom/properties/css2/AbstractCSSPropertyTextHandler.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

3.  eclipse.platform.ui/bundles/org.eclipse.e4.ui.css.swt/.polyglot.META-INF
   no-classifier: different
      org/eclipse/e4/ui/css/swt/dom/WidgetElement.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

4.  eclipse.platform/runtime/bundles/org.eclipse.core.expressions/.polyglot.META-INF
   no-classifier: different
      org/eclipse/core/internal/expressions/StandardElementHandler.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

5.  eclipse.platform.ui/bundles/org.eclipse.ui.workbench/.polyglot.META-INF
   no-classifier: different
      org/eclipse/ui/SelectionEnabler.class: different
      org/eclipse/ui/internal/ExtensionEventHandler.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

6.  eclipse.platform/ua/org.eclipse.ui.cheatsheets/pom.xml
   no-classifier: different
      org/eclipse/ui/internal/cheatsheets/data/CheatSheetParser.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

7.  eclipse.platform.ui/bundles/org.eclipse.text/.polyglot.META-INF
   no-classifier: different
      org/eclipse/jface/text/templates/TemplateTranslator.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

8.  eclipse.platform.ui/bundles/org.eclipse.ui.workbench.texteditor/.polyglot.META-INF
   no-classifier: different
      org/eclipse/ui/texteditor/AbstractTextEditor.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

9.  eclipse.jdt.debug/org.eclipse.jdt.launching/pom.xml
   no-classifier: different
      org/eclipse/jdt/internal/launching/environments/EnvironmentsManager.class: different
      org/eclipse/jdt/launching/JavaRuntime.class: different
      org/eclipse/jdt/launching/StandardSourcePathProvider.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

10.  eclipse.pde/ui/org.eclipse.pde.core/.polyglot.META-INF
   no-classifier: different
      org/eclipse/pde/internal/core/builders/PluginBaseErrorReporter.class: different
      org/eclipse/pde/internal/core/feature/Feature.class: different
      org/eclipse/pde/internal/core/schema/Schema.class: different
      org/eclipse/pde/internal/core/site/Site.class: different
      org/eclipse/pde/internal/core/target/TargetPersistence35Helper.class: different
      org/eclipse/pde/internal/core/target/TargetPersistence36Helper.class: different
      org/eclipse/pde/internal/core/target/TargetPersistence38Helper.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

11.  eclipse.jdt.ui/org.eclipse.jdt.junit.core/.polyglot.META-INF
   no-classifier: different
      org/eclipse/jdt/internal/junit/buildpath/JUnitContainerInitializer.class: different
      org/eclipse/jdt/internal/junit/model/TestRunHandler.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

12.  eclipse.jdt.ui/org.eclipse.jdt.junit/.polyglot.META-INF
   no-classifier: different
      org/eclipse/jdt/internal/junit/ui/JUnitQuickFixProcessor.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

13.  eclipse.platform/debug/org.eclipse.unittest.ui/.polyglot.META-INF
   no-classifier: different
      org/eclipse/unittest/internal/junitXmlReport/TestRunHandler.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

14.  eclipse.pde/apitools/org.eclipse.pde.api.tools/.polyglot.META-INF
   no-classifier: different
      lib/apitooling-ant.jar: different
         org/eclipse/pde/api/tools/internal/tasks/APIFreezeReportConversionTask$ConverterDefaultHandler.class: different
      org/eclipse/pde/api/tools/internal/ApiDescriptionManager.class: different
      org/eclipse/pde/api/tools/internal/search/UseScanParser.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

15.  eclipse.pde/ui/org.eclipse.pde.ui/.polyglot.META-INF
   no-classifier: different
      org/eclipse/pde/internal/ui/editor/category/CategoryDetailsSection.class: different
      org/eclipse/pde/internal/ui/editor/plugin/OverviewPage.class: different
      org/eclipse/pde/internal/ui/editor/product/OverviewPage.class: different
      org/eclipse/pde/internal/ui/editor/site/CategoryDetailsSection.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

16.  eclipse.pde/ua/org.eclipse.pde.ua.core/.polyglot.META-INF
   no-classifier: different
      org/eclipse/pde/internal/ua/core/cheatsheet/comp/CompCSTaskObject.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

17.  rt.equinox.p2/bundles/org.eclipse.equinox.p2.director.app/.polyglot.META-INF
   no-classifier: different
      org/eclipse/equinox/internal/p2/director/app/IUListFormatter.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]
```

Could be related to https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1773, I'm looking into it.

**Comment by merks** [comment]
It seems like comparator errors are a semi-daily occurrence.  😱   Thank you for your diligence dealing with such issues:  🏅

**Comment by iloveeclipse** [comment]
OK, looks like in all cases I've checked line number table was changed in code that contained switch cases. it seems there were few more local variable slots computed now, now less, so the numbering of local variables and stack size changed, like here in the `org.eclipse.pde.internal.core.feature.Feature.parse(Node)` method:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/964108/54fcc019-911b-4a69-a48d-f02518224386)

@srikanth-sankaran, I assume this is expected side effect of https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1773 ?

**Comment by srikanth-sankaran** [comment]
Studying ...

**Comment by iloveeclipse** [comment]
I've prepared PR's to touch bundles **if needed**:

- [ ] PDE https://github.com/eclipse-pde/eclipse.pde/pull/1028
- [ ] Platform UI https://github.com/eclipse-platform/eclipse.platform.ui/pull/1451
- [ ] Platform https://github.com/eclipse-platform/eclipse.platform/pull/1066
- [ ] JDT UI https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1031
- [ ] P2 https://github.com/eclipse-equinox/p2/pull/419
- [ ] Equinox https://github.com/eclipse-equinox/equinox/pull/459

and a small fix for TouchBundles script (to handle PDE repo if differently named locally)
- [ ] https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1687

**Comment by srikanth-sankaran** [comment]
> I've prepared PR's to touch bundles **if needed**:
> 
> * [ ]  PDE [Touch bundles affected by changed compiler generation for switch eclipse-pde/eclipse.pde#1028](https://github.com/eclipse-pde/eclipse.pde/pull/1028)
> * [ ]  Platform UI [Touch bundles affected by changed compiler generation for switch eclipse.platform.ui#1451](https://github.com/eclipse-platform/eclipse.platform.ui/pull/1451)
> * [ ]  Platform [Touch bundles affected by changed compiler generation for switch eclipse.platform#1066](https://github.com/eclipse-platform/eclipse.platform/pull/1066)
> * [ ]  JDT UI [Touch bundles affected by changed compiler generation for switch eclipse-jdt/eclipse.jdt.ui#1031](https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1031)
> * [ ]  P2 [Touch bundles affected by changed compiler generation for switch eclipse-equinox/p2#419](https://github.com/eclipse-equinox/p2/pull/419)
> * [ ]  Equinox [Touch bundles affected by changed compiler generation for switch eclipse-equinox/equinox#459](https://github.com/eclipse-equinox/equinox/pull/459)
> 
> and a small fix for TouchBundles script (to handle PDE repo if differently named locally)
> 
> * [ ]  [Small fix for TouchBundles to properly touch PDE #1687](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1687)

Is this list supposed to be exhaustive ? How come it doesn't include jdt.core ?? I see one comparator diff in `WrapPreparator` which is what I am looking at presently to see if the changes are justified.

**Comment by srikanth-sankaran** [comment]
Are the class files themselves readily accessible ? The textual diff is not completely informative. For example the local variable table is missing.

**Comment by iloveeclipse** [comment]
> Is this list supposed to be exhaustive ? 

Yes

> How come it doesn't include jdt.core ?? I see one comparator diff in `WrapPreparator`

Interesting. This class diff contained in the class artifacts but not in the overview diff above. **Now** it is touched via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1780 .

> Are the class files themselves readily accessible ?

Yes, if you download https://download.eclipse.org/eclipse/downloads/drops4/I20231221-1800/ you will get the "old" classes.
If you use that SDK for your workspace, you will get "new" classes for projects imported in your workspace.

**Comment by iloveeclipse** [comment]
> Are the class files themselves readily accessible ? The textual diff is not completely informative. For example the local variable table is missing.

I've created https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1688.

**Comment by srikanth-sankaran** [comment]
> @srikanth-sankaran, I assume this is expected side effect of [eclipse-jdt/eclipse.jdt.core#1773](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1773) ?

OK, I have studied a handful of cases. This is a result of https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1773 - This is _not_ an expected side effect. This is not harmful for correctness - the local variable slots are simply wasted - but needs be rectified.

Basically, the compiler will add two unnamed secret variables per each _classic_ string switch that _also declares some other local in one of the case blocks_ 

I'll propose a patch shortly.

**Comment by srikanth-sankaran** [comment]
> I have raised [eclipse-jdt/eclipse.jdt.core#1782](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1782)

PR under test: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1784

**Comment by srikanth-sankaran** [comment]
> > I have raised [eclipse-jdt/eclipse.jdt.core#1782](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1782)
> 
> PR under test: [eclipse-jdt/eclipse.jdt.core#1784](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1784)

This is merged in - I'll check back tomorrow to see if anu further action is required.

**Comment by iloveeclipse** [comment]
https://ci.eclipse.org/releng/job/Builds/job/I-build-4.31/56/ started

**Comment by iloveeclipse** [comment]
> https://ci.eclipse.org/releng/job/Builds/job/I-build-4.31/56/ started

... and successfully finished:

https://download.eclipse.org/eclipse/downloads/drops4/I20231222-0620/

@srikanth-sankaran : many thanks for a quick fix!

I will close now opened PR's, they are not needed anymore.

PS: 
I will have no access to any PC from 24.12 to 04.01, so in case some changes in platform would be needed, please contact @trancexpress.
