### ISSUE TITLE
Hundreds of tests failing with "No more handles" error

### ISSUE THREAD

**Issue by jarthana** [eclipse-platform/eclipse.platform.releng.aggregator#1695]
The latest build produces quite a few test failures on Windows and all if not most of them appear to be failing with the following error message:

```
No more handles
org.eclipse.swt.SWTError: No more handles 
```

Note that the failures are also on non SWT projects. Perhaps, one or more of the test machines need to be rebooted.

## Steps to reproduce

Just look at the test results here - https://download.eclipse.org/eclipse/downloads/drops4/I20240103-1800/testResults.php

**Comment by MohananRahul** [comment]
@jarthana issue in gitLab https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4118

**Comment by MohananRahul** [comment]
Looks like after restarting requested in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4118 , works now
https://download.eclipse.org/eclipse/downloads/drops4/I20240104-1800/testResults.php
