### ISSUE TITLE
I20240108-1340 build is unstable

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1704]
- https://download.eclipse.org/eclipse/downloads/drops4/I20240108-1340/
- https://download.eclipse.org/eclipse/downloads/drops4/I20240108-1340/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

```
Comparator differences from current build
	/home/jenkins/agent/workspace/Builds/I-build-4.31/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/siteDir/eclipse/downloads/drops4/I20240108-1340
compared to reference repo at 
	https://download.eclipse.org/eclipse/updates/4.31-I-builds

1.  eclipse.jdt.core/org.eclipse.jdt.core.tests.model/pom.xml
   no-classifier: different
      org/eclipse/jdt/core/tests/model/TypeHierarchySerializationTests.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]
```

**Comment by iloveeclipse** [comment]
Must be side effect of https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1783.
I hope to push a fix in a moment.

**Comment by iloveeclipse** [comment]
Yes, the diff shows that type change of `org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.missingTypes` field was reflected in the test class.

**Comment by iloveeclipse** [comment]
Should be fixed in next IBuild via https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1822

**Comment by HannesWell** [comment]
[Build I20240108-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20240108-1800/) was stable again.
Thanks for the fast fix.
