### ISSUE TITLE
BUILD I20240110-1800 Failed

### ISSUE THREAD

**Issue by MohananRahul** [eclipse-platform/eclipse.platform.releng.aggregator#1707]
https://ci.eclipse.org/releng/job/Builds/job/I-build-4.31/80/console 

04:48:26  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.6.1:copy-dependencies (copy) on project org.eclipse.platform.doc.isv: Artifact has not been packaged yet. When used on reactor artifact, copy should be executed after packaging: see MDEP-187.

**Comment by MohananRahul** [comment]
Is it related to https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/211 ?

**Comment by laeubi** [comment]
I'm looking into it now ...

**Comment by merks** [comment]
This is same same failures as are seen in the PRs here:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pulls

The last message in the top part of the log is

> 07:19:40  [INFO] Copying org.eclipse.jdt.launching.macosx to /home/jenkins/agent/workspace/atform.releng.aggregator_PR-1708/eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/target/dependency/org.eclipse.jdt.launching.macosx-3.6.200-SNAPSHOT.jar

Later in the log we see this:

> 07:19:40  [INFO] org.eclipse.jdt.launching.macosx 3.6.200-SNAPSHOT .. SKIPPED

So indeed an artifact is being copied before it's built...
