### ISSUE TITLE
New ECJ required for the verification builds

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.releng.aggregator#1729]
As seen here the verification builds show comparator issues:

- https://ci.eclipse.org/pde/job/eclipse.pde/job/PR-1053/5/maven-warnings/new/source.541fd16c-50c1-4ddb-ac28-9266cfd65479/#1850
- https://ci.eclipse.org/pde/job/eclipse.pde/job/PR-1053/5/maven-warnings/source.8bb9948d-8d38-4e1b-94c5-ae353ab6a529/#1063

as these are not seen in the ibuilds I suspect that there where compiler changes that need a new ECJ version to be deployed.

@iloveeclipse @MohananRahul can you trigger the required steps?

**Comment by MohananRahul** [comment]
I configured it @laeubi Could please run https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/ and merge https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1730

**Comment by iloveeclipse** [comment]
https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/160/ started

**Comment by MohananRahul** [comment]
> I configured it @laeubi Could please run https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/ and merge #1730

Done

**Comment by laeubi** [comment]
Thanks
