### ISSUE TITLE
Milestone builds don't get posted anymore ??

### ISSUE THREAD

**Issue by srikanth-sankaran** [eclipse-platform/eclipse.platform.releng.aggregator#1734]
Hello!

I don't see https://www.eclipse.org/lists/platform-releng-dev/msg39789.html precluding publishing of M1, M2 etc. Just that they now follow light weight processes. However I don't see 4.31 M1 being published at https://download.eclipse.org/eclipse/downloads/ or its availability being announced.

Please clarify the intent and expectations. Thanks

**Comment by akurtakov** [comment]
This is part of the light weight process - M2 was not pushed either. With the short 3 months release cycles just use I-builds as there is no practical difference between I-build and Mx if there is no extra testing and etc.

**Comment by srikanth-sankaran** [comment]
@akurtakov Thanks for clarifying.

**Comment by srikanth-sankaran** [comment]
Just two vestiges - 1. Github still talks of M1, M2 etc as being targets. 2. I **think** I was blocked from merging code for a couple of days during what would have been the 4.31 M1 week by the github checks.

**Comment by akurtakov** [comment]
> Just two vestiges - 1. Github still talks of M1, M2 etc as being targets.

I think these are fine for people to plan but if not usefull maybe there is no point in having these at all. If you think it's worth to stop creating them please open new discussion here so people can jump in with their opinion.

> 2. I **think** I was blocked from merging code for a couple of days during what would have been the 4.31 M1 week by the github checks.

Sorry about that, that was an issue with not updating the calendar accordingly after the policy change.
