### ISSUE TITLE
Update ecj build used in aggregator to latest

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1760]
Follow up on https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1921.
We should deploy updated ecj version and use that in aggregator.

See steps from https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/wiki/Releng-Tasks#update-jdt-compiler-note-required-for-m2-milestone-as-well

**Comment by MohananRahul** [comment]
Configured ECJ : 3.37.0.v20240131-1047 version please run : https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/

**Comment by iloveeclipse** [comment]
Started https://ci.eclipse.org/jdt/job/copyAndDeployJDTCompiler/162/

**Comment by iloveeclipse** [comment]
https://repo.eclipse.org/content/repositories/eclipse-staging/org/eclipse/jdt/ecj/3.37.0.v20240131-1047/ is available now.
