### ISSUE TITLE
CI-Builds Fail

### ISSUE THREAD

**Issue by BeckerWdf** [eclipse-platform/eclipse.platform.releng.aggregator#1788]
CI-Builds e.g. for
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1786
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1787
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1772
fail.

What's the issue here?

**Comment by BeckerWdf** [comment]
I don't understand the details for https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1960 much.
What does that mean for the PRs?

**Comment by akurtakov** [comment]
For the record - the only way to make releng and builds saner is to have projects handle it on their own as the level of spaghetti here is umanageable. https://github.com/eclipse-pde/eclipse.pde/issues/1136 is an umbrella issue for first effort to do so with PDE. Over time JDT and even Equinox should go that path.

**Comment by laeubi** [comment]
> I don't understand the details for [eclipse-jdt/eclipse.jdt.core#1960](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1960) much. What does that mean for the PRs?

It does not really reduce the memory consumption (this would be a different PR probably) but helps to have less indirection, less risk of a (unwanted) hard reference.

For example in my analysis I see 32 instances of that buffer with each having "only" about 20 MB making 640 MB of constant memory used.

**Comment by jukzi** [comment]
Is a OOME heapdump available for download?

**Comment by laeubi** [comment]
`export MAVEN_OPTS="-XX:+HeapDumpOnOutOfMemoryError -Xmx1500m"`
then run the maven command from CI ...

**Comment by laeubi** [comment]
> i am still not familiar with running CI locally and don't want to become, but i could analyse a Headump that is shared.

Just start with C&P this one here: 

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator?tab=readme-ov-file#how-to-build-the-eclipse-sdk

you probably want to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator?tab=readme-ov-file#build-with-custom-compiler

and as said limit memory and CPUs.

**Comment by laeubi** [comment]
> Is there something unclear in the communication? i offer limited help.

Don't know but if you want to have your question answered:

No there is no heapdump available for download.

**Comment by laeubi** [comment]
According to the global flags these settings apply to the maven build:

```
InitialHeapSize                          = 67108864 (roughly 500 MB)
MaxHeapSize                              = 1073741824 (roughly 1 GB)
```

I'll try to increase the max mem.

**Comment by jukzi** [comment]
I wondered where the 1 GB limit came from (and all those other non-default "ergonomic" values) and found

https://www.heise.de/hintergrund/Java-Virtual-Machine-und-Container-ein-Dream-Team-mit-Startschwierigkeiten-7329126.html?seite=3
https://docs.oracle.com/en/java/javase/21/gctuning/ergonomics.html
=> jvm uses `Maximum heap size of 1/4 of physical memory ` on servers
which corresponds to
`double MaxRAMPercentage                         = 25.000000                                 {product} {default}`
it is also possible to tweek -XX:MaxRAMPercentage=50 instead of setting a fixed heapsize, to adapt to the container size

**Comment by laeubi** [comment]
> I wondered where the 1 GB limit came from (and all those other non-default "ergonomic" values) and found
> 
> https://www.heise.de/hintergrund/Java-Virtual-Machine-und-Container-ein-Dream-Team-mit-Startschwierigkeiten-7329126.html?seite=3 https://docs.oracle.com/en/java/javase/21/gctuning/ergonomics.html => jvm uses `Maximum heap size of 1/4 of physical memory ` on servers which corresponds to `double MaxRAMPercentage = 25.000000 {product} {default}` it is also possible to tweek -XX:MaxRAMPercentage=50 instead of setting a fixed heapsize, to adapt to the container size

Just try it out by edit this file: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/.mvn/jvm.config
