### ISSUE TITLE
"Templates" Page is not documented in the User Guide

### ISSUE THREAD

**Issue by BeckerWdf** [eclipse-platform/eclipse.platform.releng.aggregator#1794]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:
I tried

find documentation about the "Templates" view under Help > Help Contents. I did only find documentation about specific templates preference pages (e.g. for ANT).
I expected: I would expect to find documentation about the generic "Templates" view.

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by BeckerWdf** [comment]
With #1795 we now have some documentation. It better than nothing but it's quite short. Let's improve this.

**Comment by akurtakov** [comment]
Closing this one as a PR has been merged. If/when someone decides to enhance it further they can open a PR with the change directly.

**Comment by BeckerWdf** [comment]
> Closing this one as a PR has been merged. If/when someone decides to enhance it further they can open a PR with the change directly.

Thanks for cleaning up the issues...
