### ISSUE TITLE
Tip of the Day cannot connect to http: because of security policy

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.releng.aggregator#1825]
- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

1. Open Tip of the Day
2. Dialog opens
3. Error Message:

<img width="372" alt="Screenshot 2024-02-27 at 10 25 30" src="https://github.com/eclipse-platform/eclipse.platform/assets/600504/3c746b25-d4ec-4cb1-bda6-095e3de2800b">

It should use `https:` protocol:

https://www.eclipse.org/downloads/download.php?r=1&file=/eclipse/tips/org.eclipse.jdt.tips.user/content/941624342282108929/941624342282108929.html

Eclipse SDK I20240226-1800 (4.31)

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by Phillipus** [comment]
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/78b5b46ade77774b421655a41a05e4b4d2a3c68a/eclipse.platform.common/bundles/org.eclipse.jdt.tips.user/src/org/eclipse/jdt/tips/user/internal/JDTTipProvider.java#L37

**Comment by Phillipus** [comment]
This makes Tip of the Day unusable. Is this worth fixing before 4.31 final? @merks

**Comment by iloveeclipse** [comment]
> Is this worth fixing before 4.31 final

I will provide PR in a moment.

**Comment by merks** [comment]
I imagine the fix is risk free.

**Comment by iloveeclipse** [comment]
@Phillipus : could you please check if https://download.eclipse.org/eclipse/downloads/drops4/I20240227-0600 fixes the problem?

**Comment by Phillipus** [comment]
> @Phillipus : could you please check if https://download.eclipse.org/eclipse/downloads/drops4/I20240227-0600 fixes the problem?

That build doesn't have this fix in, so no the problem exists in that build. I guess we have to wait for the next build?

**Comment by iloveeclipse** [comment]
> That build doesn't have this fix in

Damn, I was a bit too late. Sorry, please check with the next one.

**Comment by iloveeclipse** [comment]
So now please check with https://download.eclipse.org/eclipse/downloads/drops4/I20240227-1800/

**Comment by Phillipus** [comment]
Yes, the tips are loading now. Although I have no idea what the empty squares in the bottom left are.

<img width="1092" alt="Screenshot 2024-02-28 at 09 23 42" src="https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/600504/74c7fa0c-50df-495a-95bc-2818750a7d15">

**Comment by Phillipus** [comment]
> Yes, the tips are loading now. Although I have no idea what the empty squares in the bottom left are.

Reported [here](https://github.com/eclipse-platform/eclipse.platform/issues/1217)

**Comment by iloveeclipse** [comment]
> @iloveeclipse This problem is back again in https://download.eclipse.org/eclipse/downloads/drops4/I20240229-0520/

Can you please attach error log & check your version of `org.eclipse.jdt.tips.user` bundle?

I fear that somehow the wrong code or wrong bundle version is shipped with 4.31 RC2.

**Comment by Phillipus** [comment]
I had to clear my workspace and it's working again.

**Comment by Phillipus** [comment]
This is strange. And now it's not working with a new workspace.

**Comment by Phillipus** [comment]
I don't understand this. I'm getting the http error with a freshly unpacked Eclipse, a new empty workspace and the `~/.eclipse` folder deleted. Same on `I20240227-1800` and `I20240229-0520`

**Comment by Phillipus** [comment]
Which jar file contains the `JDTTipProvider`?

**Comment by Phillipus** [comment]
<img width="372" alt="Screenshot 2024-03-01 at 14 32 58" src="https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/600504/847344ea-91db-4442-8ed0-a6b8cac7f63c">

> The code is in org.eclipse.jdt.tips.user bundle

Yes, but I'm trying to find this in the Eclipse installation to see what version it has. I can't see the bundle name in the plugins folder.

**Comment by Phillipus** [comment]
I really don't understand this. It's Mac specific as even older version work on Windows, and a search for "The resource could not be loaded because the App Transport Security policy..." brings up Apple stuff. But I don't understand why there's still a `http:` url.

**Comment by Phillipus** [comment]
This file:

https://github.com/eclipse-platform/eclipse.platform/blob/master/ua/org.eclipse.tips.ide/src/org/eclipse/tips/ide/internal/provider/twittertips.json

Has this line:

```
"baseUrl": "http://www.eclipse.org/downloads/download.php?r=1&file=/eclipse/tips/org.eclipse.jdt.tips.user"
```

But even if I change that to `https:` it doesn't work. Also, the content at that URL uses HTTP

**Comment by Phillipus** [comment]
I hacked the https://github.com/eclipse-platform/eclipse.platform/blob/master/ua/org.eclipse.tips.ide/src/org/eclipse/tips/ide/internal/provider/twittertips.json file and changed that basUrl to `https` and it works. So that file needs changing too.

**Comment by Phillipus** [comment]
Re-open this as it's still a problem until https://github.com/eclipse-platform/eclipse.platform/pull/1228

**Comment by Phillipus** [comment]
Sorry, I'll close this one as the PR is for platform, and this one was for aggregator.
