### ISSUE TITLE
Missing org.eclipse.pde.doc.user in platform common bundles

### ISSUE THREAD

**Issue by alshamams** [eclipse-platform/eclipse.platform.releng.aggregator#1833]
This folder was present until 4.30. Absence of this now is failing my script that copies N and N contents.

**Comment by laeubi** [comment]
That's not a bug, the content was moved here:
https://github.com/eclipse-pde/eclipse.pde/tree/master/org.eclipse.pde.doc.user

**Comment by alshamams** [comment]
Thanks @laeubi for the information. May I know the reason ? Also does this mean that org.eclipse.pde.doc.user is update in terms of N and N and doesn't require any manual editing?

**Comment by akurtakov** [comment]
@alshamams Prior to using github docs were in a platform repository (with handcrafter permission model) to which PDE/Equinox/Platform/JDT committers could push changes. Nowadays, there is proper permission model with no exceptions - only committers to given project can push to repositories of the project which means that PDE/JDT committers have to find Platform committer to push their changes to PDE/JDT documentation - this is wrong in every aspect. 
It was yesterday when we had a JDT committer complaining he can't push to JDT docs (https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1828#issuecomment-1966697685) so JDT documentation bundles will be moved to JDT repository in one of the next releases (depending on finding time only).
