### ISSUE TITLE
Update ASM to 9.7

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1951]
ASM 9.7 released with Java 23 support, see https://asm.ow2.io/versions.html
We should update platform dependencies, I will push a PR.

**Comment by merks** [comment]
FYI I held off because jacoco does not work with the new version. 

https://github.com/jacoco/jacoco/issues/1599

**Comment by iloveeclipse** [comment]
> FYI I held off because jacoco does not work with the new version.

But it should be fine to update now, as jacoco problem seem to be fixed?

**Comment by merks** [comment]
A new version is not yet published to maven central. That doesn’t mean the platform shouldn’t update, but I cannot update orbit and I typically try to keep the platform and orbit exactly in sync.

**Comment by iloveeclipse** [comment]
> A new version is not yet published to maven central

Are you sure?
https://central.sonatype.com/artifact/org.ow2.asm/asm
![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/964108/3b0451e3-5dc9-4c04-957c-360ed21508fd)

**Comment by merks** [comment]
I speak of jacoco.  No 0.8.12 yet

https://repo1.maven.org/maven2/org/jacoco/org.jacoco.core/

And 0.8.11 excludes the latest asm. 

Details are in the jacoco issue I referenced.
