### ISSUE TITLE
Class file diff in validation builds

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.releng.aggregator#1960]
The PDE validation build currently reports a classfile difference here:

https://ci.eclipse.org/pde/job/eclipse.pde/job/PR-1217/2/maven-warnings/new/source.b3bd3a11-fb9e-418b-b444-b56138864442/#11109
https://ci.eclipse.org/pde/job/eclipse.pde/job/PR-1217/2/eclipse/new/source.72006889-9cf8-483f-9cc9-ec32c906cc12/#0

Compile logs and artifact comparison can be found here:

https://ci.eclipse.org/pde/job/eclipse.pde/job/PR-1217/2/artifact/e4tools/bundles/org.eclipse.e4.tools.emf.ui/target/

The PR itself does not change that file at all.

**Comment by akurtakov** [comment]
Do you think updating to latest ecj in parent is what's needed ?

**Comment by laeubi** [comment]
Probably yes at laest the Ibuild seem to not report comparator diffs.
