### ISSUE TITLE
4.32 M1 build is missing

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1967]
Not sure how the "promotion" of M1 build is done (job or manually), but I don't see 4.32 M1 build announced and download page is also don't show anything related. 

In my understanding, we should have had `I20240405-1800` build promoted as M1, but it was failing to build: https://ci.eclipse.org/releng/job/Builds/job/I-build-4.32/58/ .

I've triggered new build, it is available now: https://download.eclipse.org/eclipse/downloads/drops4/I20240406-0130/, so should that be M1? If yes, *how* we promote this build as M1?

**Comment by merks** [comment]
Recall we switched to light weight milestones

**Comment by merks** [comment]
Note the simrel was updated.

**Comment by iloveeclipse** [comment]
> Recall we switched to light weight milestones

Does it mean, we will have no build that could be marked as M1? Which build will be used for simrel?

**Comment by merks** [comment]
This contribution to SimRel is the "defacto" M1:

https://github.com/eclipse-simrel/simrel.build/blame/afe289a059f54b0a27736cee1cb1709f8d789bfa/ep.aggrcon#L3

**Comment by iloveeclipse** [comment]
> This contribution to SimRel is the "defacto" M1:
> 
> https://github.com/eclipse-simrel/simrel.build/blame/afe289a059f54b0a27736cee1cb1709f8d789bfa/ep.aggrcon#L3

Can we update it to the today build please ? We had a fix for Java 22 support that was missing before and made PDE and JDT UI unhappy.

**Comment by merks** [comment]
I think an update would not be a problem. 

Could you share the exact url you’d like to have contributed?  I’ll make sure it gets done.

**Comment by iloveeclipse** [comment]
OK, actually tomorrow build will be even better.
- https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2286
- https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/421

**Comment by merks** [comment]
@iloveeclipse 

Is this the one you want?

https://download.eclipse.org/eclipse/updates/4.32-I-builds/I20240406-1800/

**Comment by iloveeclipse** [comment]
Yep.

**Comment by iloveeclipse** [comment]
One of the reasons I've created this issue was the external visibility of Eclipse 4.32 milestones, which is important for downstream SDK consumers like QFS. I can't get a working QFS Eclipse tests with 4.32 at the moment because their SWT patch waits for official M1 release, see https://gitlab.com/qfs/qfs-swt-patches/-/issues/3.

So is there a way to mark https://download.eclipse.org/eclipse/downloads/drops4/I20240406-1800/ build as **M1** and link to it on https://download.eclipse.org/eclipse/downloads/? I assume if we've managed to do that for all previous releases, there must be some job or script or whatever else that one can trigger? @sravanlakkimsetti ?

**Comment by sravanlakkimsetti** [comment]
We can still do it. the promotion scripts will be able to handle them. Because of light weight milestones we have stopped the promotion activity. We could still do it if required. 

Basically two jobs 
1. [Rename and Promote](https://ci.eclipse.org/releng/job/Releng/job/renameAndPromote/)  - To create the milestone build. But will be hidden
2. [Make Visible](https://ci.eclipse.org/releng/job/Releng/job/makeVisible/) - to make the build visible to public

@MohananRahul @akurtakov need your views on this one

**Comment by merks** [comment]
Thank you!  💕

**Comment by iloveeclipse** [comment]
Yes, big thanks.
