### ISSUE TITLE
Reference to 4.31 in p2.inf files

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-platform/eclipse.platform.releng.aggregator#1974]
Hi releng folk,

as an update to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1854 it looks like there are still some references to 4.31, for example:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/8a53dc4e7e46f283f68b5a1310f0a038bbc180ab/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.p2.inf#L12

**Comment by jonahgraham** [comment]
Here is the line in the other p2.inf file:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/8a53dc4e7e46f283f68b5a1310f0a038bbc180ab/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.p2.inf#L12

**Comment by jonahgraham** [comment]
I guess this script needs an update to capture it for the next version:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/77edf9205fe78f67ab1b4e354d356630884a5c3a/scripts/updateProductVersion.sh#L18

**Comment by MohananRahul** [comment]
> I guess this script needs an update to capture it for the next version:
> 
> https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/77edf9205fe78f67ab1b4e354d356630884a5c3a/scripts/updateProductVersion.sh#L18

I think this is usually done when the release happens.

**Comment by jonahgraham** [comment]
> > I guess this script needs an update to capture it for the next version:
> > https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/77edf9205fe78f67ab1b4e354d356630884a5c3a/scripts/updateProductVersion.sh#L18
> 
> I think this is usually done when the release happens.

My comment was unclear - that comment meant I think a line needs to be added to it, e.g. something like the following so that next version the p2.inf change isn't missed.

```
find $script_location/.. -type f -name *.p2.inf -exec sed -i 's/4.31/4.32/g' {} \;
```

In addition, I think there are some other places that say 4.31 that probably shouldn't still, but I haven't done a full check:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/5be6f6ab89801b813dc208a9fe422709e3bf9e87/oomph/Platform.setup#L179

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/5be6f6ab89801b813dc208a9fe422709e3bf9e87/eclipse.platform.common/bundles/org.eclipse.platform.doc.isv/platformOptions.txt#L200

There are a bunch of other search result for 4.31, some of them look out of date too.

**Comment by merks** [comment]
FYI. The setup tasks indicated above are disabled and will be modified and enabled when 4.33 master opens but 4.32 is not yet released.

**Comment by akurtakov** [comment]
Is there anything to be done here?

**Comment by jonahgraham** [comment]
The files were manually updated in #1975, but the [script](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/scripts/updateProductVersion.sh) wasn't updated yet so it seems this problem will recur in the next version bump. If the script should not be updated, this issue can be closed.

**Comment by akurtakov** [comment]
What is the status here?

**Comment by akurtakov** [comment]
Closing due to lack of interest.
