### ISSUE TITLE
Improve process for contributing to SimRel

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.releng.aggregator#2000]
@MohananRahul  @iloveeclipse  @akurtakov 

I see there is still no contribution to SimRel for M2.  The deadline for that was Friday.    I also see no M2 version on the download page:

https://download.eclipse.org/eclipse/downloads/

I need to know which URL to contribute to SimRel ASAP.   Please advise.

**Comment by iloveeclipse** [comment]
It should be [I20240425-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20240425-1800/) but I would take [I20240427-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20240427-1800/) to get also fixes 
* https://github.com/eclipse-platform/eclipse.platform.ui/pull/1860
* https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2390

**Comment by MohananRahul** [comment]
Build I20240428-1800 : contributed. Updating ECJ latest to 3.38.0.v20240427-0959

**Comment by akurtakov** [comment]
I don't see anything to improve(automate?) the process thus closing this one.

**Comment by iloveeclipse** [comment]
No notification / ecj update also for M3. Reopening.

AFAIK this build is supposed to be M3 and we should sent a mail about started RC phase.

@sravanlakkimsetti, @MohananRahul ?

**Comment by iloveeclipse** [comment]
Mails are sent, ecj build is done, aggregator update PR pending: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2028
