### ISSUE TITLE
Comparator Errors in 4.32 I20240506-1800

### ISSUE THREAD

**Issue by HannesWell** [eclipse-platform/eclipse.platform.releng.aggregator#2011]
Since https://download.eclipse.org/eclipse/downloads/drops4/I20240506-1800/ there are [two unanticipated comparator errors](https://download.eclipse.org/eclipse/downloads/drops4/I20240506-1800/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt):
```
Comparator differences from current build
	/home/jenkins/agent/workspace/Builds/I-build-4.32/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/siteDir/eclipse/downloads/drops4/I20240506-1800
compared to reference repo at 
	https://download.eclipse.org/eclipse/updates/4.32-I-builds

1.  eclipse.platform.releng.tychoeclipsebuilder/rcp.config/.polyglot.feature.xml
   classifier-root.cocoa.macosx.aarch64: different
      Eclipse.app/Contents/MacOS/eclipse: different
   classifier-root.gtk.linux.x86_64: different
      eclipse: different
   classifier-root.win32.win32.x86_64: different
      eclipse.exe: different
      eclipsec.exe: different
   classifier-root.cocoa.macosx.x86_64: different
      Eclipse.app/Contents/MacOS/eclipse: different
   classifier-root.gtk.linux.ppc64le: different
      eclipse: different
   classifier-root.gtk.linux.aarch64: different
      eclipse: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [root.cocoa.macosx.aarch64, root.gtk.linux.x86_64, root.win32.win32.x86_64, root.cocoa.macosx.x86_64, root.gtk.linux.ppc64le, root.gtk.linux.aarch64]

2.  eclipse.platform.releng.tychoeclipsebuilder/rcp.config/.polyglot.feature.xml
   classifier-root.cocoa.macosx.aarch64: different
      Eclipse.app/Contents/MacOS/eclipse: different
   classifier-root.gtk.linux.x86_64: different
      eclipse: different
   classifier-root.win32.win32.x86_64: different
      eclipse.exe: different
      eclipsec.exe: different
   classifier-root.cocoa.macosx.x86_64: different
      Eclipse.app/Contents/MacOS/eclipse: different
   classifier-root.gtk.linux.ppc64le: different
      eclipse: different
   classifier-root.gtk.linux.aarch64: different
      eclipse: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [root.cocoa.macosx.aarch64, root.gtk.linux.x86_64, root.win32.win32.x86_64, root.cocoa.macosx.x86_64, root.gtk.linux.ppc64le, root.gtk.linux.aarch64]
```

Probably `eclipse.platform.releng.tychoeclipsebuilder/rcp.config` needs a qualifier bump after https://github.com/eclipse-equinox/equinox/pull/603.

**Comment by jarthana** [comment]
The compiler code-gen also changed by https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2414
Copying @mpalat who might be able to shed some light.

**Comment by srikanth-sankaran** [comment]
> The compiler code-gen also changed by [eclipse-jdt/eclipse.jdt.core#2414](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2414) Copying @mpalat who might be able to shed some light.

That is unlikely to be involved - that is a bug fix for a preview feature and is a corner case at that.

In any event, we don't seem to have any class files that differ - only platform native binary files

**Comment by mpalat** [comment]
> > The compiler code-gen also changed by [eclipse-jdt/eclipse.jdt.core#2414](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2414) Copying @mpalat who might be able to shed some light.
> 
> That is unlikely to be involved - that is a bug fix for a preview feature and is a corner case at that.

Agree with Srikanth - unless there are class file differences this change should not cause an issue

**Comment by iloveeclipse** [comment]
I've merged https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2012 and will trigger a build now.

**Comment by iloveeclipse** [comment]
@HannesWell : thanks, your patch worked fine & new build has no comparator errors: https://download.eclipse.org/eclipse/downloads/drops4/I20240507-0220

**Comment by HannesWell** [comment]
> @HannesWell : thanks, your patch worked fine & new build has no comparator errors: https://download.eclipse.org/eclipse/downloads/drops4/I20240507-0220

Great. Thanks for pushing.
