### ISSUE TITLE
4.32 RC2 references 4.31 and 2024-03 SimRel in available updates

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-platform/eclipse.platform.releng.aggregator#2059]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

* Go to available software sites and 4.31 and 2024-03 URLs are in use:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/679236/02f4c2aa-1a4a-4cb2-9a27-aa384c667be4)

I expected: 4.32 + 2024-06 URLs

But got: *<what is the actual undesired behavior?>*

## Tested under this environment:
* OS & version: Linux
* tar: eclipse-SDK-4.32RC2-linux-gtk-x86_64.tar.gz 
* Eclipse IDE/Platform version (as shown in *Help > About*): Version: 2024-06 (4.32) Build id: I20240529-1800

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by iloveeclipse** [comment]
Is this related?

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/bd412a329b26f66aff2422f1eaa9619c7cb9ff15/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/platform.product#L202

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/bd412a329b26f66aff2422f1eaa9619c7cb9ff15/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product#L207

**Comment by jonahgraham** [comment]
I assume the issue is this:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/032b43ee222469005f0692c7fae4f8c43a23c7b2/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/sdk.product#L207-L208

**Comment by jonahgraham** [comment]
EPP made the update, so only affect Platform/SDK

https://github.com/eclipse-packaging/packages/blob/6d2a1e6508feda746b8e8e48de5092feb866c38f/packages/org.eclipse.epp.package.cpp.product/epp.product#L284C1-L287C6

**Comment by jonahgraham** [comment]
I can do a PR in a moment, but I think we need to respin RC2?

**Comment by iloveeclipse** [comment]
@jonahgraham : would you provide a PR? Looks like we continue with the traditional RC2a builds...

@sravanlakkimsetti , @MohananRahul : not sure if this is supposed to be automatically changed during release preparation steps, and if yes, any idea why it wasn't done?

**Comment by jonahgraham** [comment]
> @jonahgraham : would you provide a PR? Looks like we continue with the traditional RC2a builds...

Done see #2060 

> @sravanlakkimsetti , @MohananRahul : not sure if this is supposed to be automatically changed during release preparation steps, and if yes, any idea why it wasn't done?

See #1974 - that issue is still open. I believe it should have been changed at beginning of development, just no one noticed until now. I tried to identify all the items missed by updateProductVersion.sh, but I guess there are still some more, like this one that updates the product doesn't go far enough:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/bd412a329b26f66aff2422f1eaa9619c7cb9ff15/scripts/updateProductVersion.sh#L20

**Comment by merks** [comment]
I'm not 100% convinced this requires a respin...

**Comment by MohananRahul** [comment]
> @jonahgraham : would you provide a PR? Looks like we continue with the traditional RC2a builds...
> 
> @sravanlakkimsetti , @MohananRahul : not sure if this is supposed to be automatically changed during release preparation steps, and if yes, any idea why it wasn't done?

Previously It was done manually by @akurtakov.

**Comment by MohananRahul** [comment]
> > I'm not 100% convinced this requires a respin...
> 
> Is that because this only affects non-EPP / non-Oomph users?

@merks @jonahgraham Can we do respin for RC2a?

**Comment by iloveeclipse** [comment]
+1 for respin from me, if that is needed.

**Comment by merks** [comment]
Yes I gave a PMC +1 elsewhere already too.  Doing it before Monday is minimally disruptive. Thanks 🙏

**Comment by MohananRahul** [comment]
IBuild Started : https://ci.eclipse.org/releng/job/Builds/job/I-build-4.32/132/

**Comment by HannesWell** [comment]
Thank you Jonah for providing this fix.
@MohananRahul could you please add this the the list of tasks for the release preparation?
Since https://download.eclipse.org/eclipse/updates/4.32/ is currently effectively empty I think this should be done very late, but it should not be forgotten again:
![grafik](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/44067969/55a61465-79dc-4a28-8cae-aa651462b025)

**Comment by merks** [comment]
It being empty is not a problem. Better that all downloads for an ongoing release point at a repository that will contain the release. I think EPP sets it earlier too but of course that repo is not empty and contains milestones.
