### ISSUE TITLE
No test results for I20240605-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#2101]
See https://download.eclipse.org/eclipse/downloads/drops4/I20240605-1800/
We have no idea about build quality.

At least SDK is starting now on Linux, so that [SWT binaries problem](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2085) is not a problem anymore.

**Comment by MohananRahul** [comment]
This issue appears to be related to the automated test , Jenkins parameters. somehow the parameter field is not generated when the test is triggered automatically. However, when we rebuild the test manually, the buildID parameter is available and  passed correctly. Raised :  https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4717

**Comment by iloveeclipse** [comment]
OK, we have some changes made by Sebastien on https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4717 and now it **seem** to me that the tests are started properly but we have build? errors with some plugins missing
https://download.eclipse.org/eclipse/downloads/drops4/I20240606-0650/testResults.php

```
Missing Files
org.eclipse.core.tests.resources_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.equinox.p2.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.jdt.apt.pluggable.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.jdt.apt.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.jdt.compiler.apt.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.jdt.compiler.tool.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.jdt.core.tests.builder_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.jdt.core.tests.compiler_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.jdt.core.tests.model_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.jdt.core.tests.performance_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.jdt.debug.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.jdt.text.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.jdt.ui.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.jdt.ui.tests.refactoring_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.jface.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.jface.text.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.osgi.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.pde.api.tools.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.pde.build.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.pde.genericeditor.extension.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.pde.ua.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.pde.ui.templates.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.pde.ui.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
org.eclipse.ui.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
```

@sravanlakkimsetti , @akurtakov : I'm not sure what means the `Missing Files` table and what are "usual" reasons for that?

**Comment by sravanlakkimsetti** [comment]
> This issue appears to be related to the automated test , Jenkins parameters. somehow the parameter field is not generated when the test is triggered automatically. However, when we rebuild the test manually, the buildID parameter is available and passed correctly. Raised : https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4717

Don't forget to update the configuration as suggested by [Sébastien Heurtematte](https://gitlab.eclipse.org/heurtemattes) in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/JenkinsJobs/Builds/I_build.groovy and https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/JenkinsJobs/YBuilds/Y_build.groovy

**Comment by sravanlakkimsetti** [comment]
> OK, we have some changes made by Sebastien on https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4717 and now it **seem** to me that the tests are started properly but we have build? errors with some plugins missing https://download.eclipse.org/eclipse/downloads/drops4/I20240606-0650/testResults.php
> 
> ```
> Missing Files
> org.eclipse.core.tests.resources_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.equinox.p2.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.jdt.apt.pluggable.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.jdt.apt.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.jdt.compiler.apt.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.jdt.compiler.tool.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.jdt.core.tests.builder_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.jdt.core.tests.compiler_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.jdt.core.tests.model_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.jdt.core.tests.performance_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.jdt.debug.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.jdt.text.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.jdt.ui.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.jdt.ui.tests.refactoring_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.jface.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.jface.text.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.osgi.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.pde.api.tools.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.pde.build.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.pde.genericeditor.extension.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.pde.ua.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.pde.ui.templates.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.pde.ui.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> org.eclipse.ui.tests_ep433I-unit-win32-java17_win32.win32.x86_64_17.xml
> ```
> 
> @sravanlakkimsetti , @akurtakov : I'm not sure what means the `Missing Files` table and what are "usual" reasons for that?

This means the testing has aborted in between. To debug I will normally check the console logs at https://download.eclipse.org/eclipse/downloads/drops4/I20240606-0650/logs.php#console. In this case [ep433I-unit-win32-java17_win32.win32.x86_64_17_consolelog.txt](https://download.eclipse.org/eclipse/downloads/drops4/I20240606-0650/testresults/consolelogs/ep433I-unit-win32-java17_win32.win32.x86_64_17_consolelog.txt).

In that file there should be 78 instances of `java-test:` for successful test run. If not check the last instance and the log 

In this instance I see 
```
java-test:
     [echo] Running org.eclipse.pde.ui.tests.AllPDETests. Result file: C:\Users\genie.releng\workspace\AutomatedTests\ep433I-unit-win32-java17/workarea/I20240606-0650/eclipse-testing/results/ep433I-unit-win32-java17_win32.win32.x86_64_17/org.eclipse.pde.ui.tests.AllPDETests.xml
     [echo] timout property: 7200000
     [echo] frameworkvmargs:  -Xms256m -Xmx2048m  -Djava.security.manager=allow
     [echo] vmargs: 
     [echo] extraVMargs: 
     [echo] frameworkperfargs: 
     [echo] crash loglocationarg (if any): ${loglocationarg}
     [echo] crash loglocation (if not default): 
     [java] Jun 06, 2024 2:42:12 PM org.apache.aries.spifly.BaseActivator log
     [java] INFO: Registered provider org.slf4j.simple.SimpleServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle slf4j.simple
     [java] WARNING: Annotation classes from the 'javax.inject' or 'javax.annotation' package found.
     [java] It is recommended to migrate to the corresponding replacements in the jakarta namespace.
     [java] The Eclipse E4 Platform will remove support for those javax-annotations in a future release.
     [java] To suppress this warning, set the VM property: -Declipse.e4.inject.javax.warning=false
     [java] To disable processing of 'javax' annotations entirely, set the VM property: -Declipse.e4.inject.javax.disabled=true
     [java] 
     [java] INFO: timeoutScreenOutputDir: C:\Users\genie.releng\workspace\AutomatedTests\ep433I-unit-win32-java17\workarea\I20240606-0650\eclipse-testing\results\ep433I-unit-win32-java17_win32.win32.x86_64_17/timeoutScreens
     [java] INFO: timeout: 7200000
     [java] WARNING: A terminally deprecated method in java.lang.System has been called
     [java] WARNING: System::setSecurityManager has been called by org.eclipse.ant.internal.core.ant.InternalAntRunner (file:C:/Users/genie.releng/workspace/AutomatedTests/ep433I-unit-win32-java17/workarea/I20240606-0650/eclipse-testing/test-eclipse/eclipse/configuration/org.eclipse.osgi/66/0/.cp/lib/antsupportlib.jar)
     [java] WARNING: Please consider reporting this to the maintainers of org.eclipse.ant.internal.core.ant.InternalAntRunner
     [java] WARNING: System::setSecurityManager will be removed in a future release
     [java] WARNING: A terminally deprecated method in java.lang.System has been called
     [java] WARNING: System::setSecurityManager has been called by org.eclipse.ant.internal.core.ant.InternalAntRunner (file:C:/Users/genie.releng/workspace/AutomatedTests/ep433I-unit-win32-java17/workarea/I20240606-0650/eclipse-testing/test-eclipse/eclipse/configuration/org.eclipse.osgi/66/0/.cp/lib/antsupportlib.jar)
     [java] WARNING: Please consider reporting this to the maintainers of org.eclipse.ant.internal.core.ant.InternalAntRunner
     [java] WARNING: System::setSecurityManager will be removed in a future release
     [java] WARNING: A terminally deprecated method in java.lang.System has been called
     [java] WARNING: System::setSecurityManager has been called by org.eclipse.ant.internal.core.ant.InternalAntRunner (file:C:/Users/genie.releng/workspace/AutomatedTests/ep433I-unit-win32-java17/workarea/I20240606-0650/eclipse-testing/test-eclipse/eclipse/configuration/org.eclipse.osgi/66/0/.cp/lib/antsupportlib.jar)
     [java] WARNING: Please consider reporting this to the maintainers of org.eclipse.ant.internal.core.ant.InternalAntRunner
     [java] WARNING: System::setSecurityManager will be removed in a future release
     [java] WARNING: A terminally deprecated method in java.lang.System has been called
     [java] WARNING: System::setSecurityManager has been called by org.eclipse.ant.internal.core.ant.InternalAntRunner (file:C:/Users/genie.releng/workspace/AutomatedTests/ep433I-unit-win32-java17/workarea/I20240606-0650/eclipse-testing/test-eclipse/eclipse/configuration/org.eclipse.osgi/66/0/.cp/lib/antsupportlib.jar)
     [java] WARNING: Please consider reporting this to the maintainers of org.eclipse.ant.internal.core.ant.InternalAntRunner
     [java] WARNING: System::setSecurityManager will be removed in a future release
     [java] WARNING: A terminally deprecated method in java.lang.System has been called
     [java] WARNING: System::setSecurityManager has been called by org.eclipse.ant.internal.core.ant.InternalAntRunner (file:C:/Users/genie.releng/workspace/AutomatedTests/ep433I-unit-win32-java17/workarea/I20240606-0650/eclipse-testing/test-eclipse/eclipse/configuration/org.eclipse.osgi/66/0/.cp/lib/antsupportlib.jar)
     [java] WARNING: Please consider reporting this to the maintainers of org.eclipse.ant.internal.core.ant.InternalAntRunner
     [java] WARNING: System::setSecurityManager will be removed in a future release
     [java] WARNING: A terminally deprecated method in java.lang.System has been called
     [java] WARNING: System::setSecurityManager has been called by org.eclipse.ant.internal.core.ant.InternalAntRunner (file:C:/Users/genie.releng/workspace/AutomatedTests/ep433I-unit-win32-java17/workarea/I20240606-0650/eclipse-testing/test-eclipse/eclipse/configuration/org.eclipse.osgi/66/0/.cp/lib/antsupportlib.jar)
     [java] WARNING: Please consider reporting this to the maintainers of org.eclipse.ant.internal.core.ant.InternalAntRunner
     [java] WARNING: System::setSecurityManager will be removed in a future release
     [java] WARNING: A terminally deprecated method in java.lang.System has been called
     [java] WARNING: System::setSecurityManager has been called by org.eclipse.ant.internal.core.ant.InternalAntRunner (file:C:/Users/genie.releng/workspace/AutomatedTests/ep433I-unit-win32-java17/workarea/I20240606-0650/eclipse-testing/test-eclipse/eclipse/configuration/org.eclipse.osgi/66/0/.cp/lib/antsupportlib.jar)
     [java] WARNING: Please consider reporting this to the maintainers of org.eclipse.ant.internal.core.ant.InternalAntRunner
     [java] WARNING: System::setSecurityManager will be removed in a future release
     [java] WARNING: A terminally deprecated method in java.lang.System has been called
     [java] WARNING: System::setSecurityManager has been called by org.eclipse.ant.internal.core.ant.InternalAntRunner (file:C:/Users/genie.releng/workspace/AutomatedTests/ep433I-unit-win32-java17/workarea/I20240606-0650/eclipse-testing/test-eclipse/eclipse/configuration/org.eclipse.osgi/66/0/.cp/lib/antsupportlib.jar)
     [java] WARNING: Please consider reporting this to the maintainers of org.eclipse.ant.internal.core.ant.InternalAntRunner
     [java] WARNING: System::setSecurityManager will be removed in a future release
     [java] WARNING: A terminally deprecated method in java.lang.System has been called
     [java] WARNING: System::setSecurityManager has been called by org.eclipse.ant.internal.core.ant.InternalAntRunner (file:C:/Users/genie.releng/workspace/AutomatedTests/ep433I-unit-win32-java17/workarea/I20240606-0650/eclipse-testing/test-eclipse/eclipse/configuration/org.eclipse.osgi/66/0/.cp/lib/antsupportlib.jar)
     [java] WARNING: Please consider reporting this to the maintainers of org.eclipse.ant.internal.core.ant.InternalAntRunner
     [java] WARNING: System::setSecurityManager will be removed in a future release
     [java] WARNING: A terminally deprecated method in java.lang.System has been called
     [java] WARNING: System::setSecurityManager has been called by org.eclipse.ant.internal.core.ant.InternalAntRunner (file:C:/Users/genie.releng/workspace/AutomatedTests/ep433I-unit-win32-java17/workarea/I20240606-0650/eclipse-testing/test-eclipse/eclipse/configuration/org.eclipse.osgi/66/0/.cp/lib/antsupportlib.jar)
     [java] WARNING: Please consider reporting this to the maintainers of org.eclipse.ant.internal.core.ant.InternalAntRunner
     [java] WARNING: System::setSecurityManager will be removed in a future release
Terminate batch job (Y/N)? 
```

It appears pde tests are looking for user input. Please check the org.eclipse.pde.ui.tests.AllPDETests bundle

**Comment by iloveeclipse** [comment]
> It appears pde tests are looking for user input

That would mean, the Jenkins job parameters aren't resolved?

**Comment by HannesWell** [comment]
> It appears pde tests are looking for user input. Please check the org.eclipse.pde.ui.tests.AllPDETests bundle

Do you read that from the `timout property` line?
> ```
> java-test:
>      [echo] Running org.eclipse.pde.ui.tests.AllPDETests. Result file: C:\Users\genie.releng\workspace\AutomatedTests\ep433I-unit-win32-java17/workarea/I20240606-0650/eclipse-testing/results/ep433I-unit-win32-java17_win32.win32.x86_64_17/org.eclipse.pde.ui.tests.AllPDETests.xml
>      [echo] timout property: 7200000
> ```

I have to admit I don't know what to check because I don't find anything that seem relevant when searching for `timeout property` or `timeout` and way too much when searching for `property`.


https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2107

**Comment by iloveeclipse** [comment]
The tests are executed again. Only remaining part is to update scripts that create jobs => https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2108

**Comment by sravanlakkimsetti** [comment]
> > It appears pde tests are looking for user input. Please check the org.eclipse.pde.ui.tests.AllPDETests bundle
> 
> Do you read that from the `timout property` line?
> 
> > ```
> > java-test:
> >      [echo] Running org.eclipse.pde.ui.tests.AllPDETests. Result file: C:\Users\genie.releng\workspace\AutomatedTests\ep433I-unit-win32-java17/workarea/I20240606-0650/eclipse-testing/results/ep433I-unit-win32-java17_win32.win32.x86_64_17/org.eclipse.pde.ui.tests.AllPDETests.xml
> >      [echo] timout property: 7200000
> > ```
> 
> I have to admit I don't know what to check because I don't find anything that seem relevant when searching for `timeout property` or `timeout` and way too much when searching for `property`.

My guess was based on 
```
> Terminate batch job (Y/N)?
```

**Comment by HannesWell** [comment]
> The tests are executed again. Only remaining part is to update scripts that create jobs => #2108

Just submitted #2108 and deplyed the job configurations in the RelEng JIPP I also triggered an I-build and aborted it after the first stage to verify that there are no sever syntax errors.
I'll check tonight's I-build result, triggered by the cron-trigger, if they are still successful. If yes I think this can be considered resolved.

**Comment by MohananRahul** [comment]
The unit test failed to start again because the parameter field was not generated.

<img width="1091" alt="image" src="https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/121536011/4b992b5a-11db-4139-b9dc-2306ca020c8f">

**Comment by HannesWell** [comment]
> The unit test failed to start again because the parameter field was not generated.

Yes I noticed that as well at this moment :( Looks like #2108 wasn't sufficient.
Triggered an I-build manually so that we have test-results for yesterdays changes:
https://ci.eclipse.org/releng/job/Builds/job/I-build-4.33/9/

Since it makes a difference if the job is triggered manually or by the cron-tigger I wonder if it is actually a question of permissions?
Will continue to investigate.

**Comment by HannesWell** [comment]
I did some investigation with my local Jenkins and since the Parameters tab ob the test jobs does not show anything I have the impression that the test-jobs somehow 'forgets' that it has parameters. If the triggering job would not pass the buildId parameter the default value would be used but the parameter would still be displayed (which is not the case if a job is cron triggered):
https://ci.eclipse.org/releng/job/AutomatedTests/job/ep433I-unit-cen64-gtk3-java17/9/parameters/

> Since it makes a difference if the job is triggered manually or by the cron-tigger I wonder if it is actually a question of permissions?
> Will continue to investigate.

With that in mind, @heurtematte could it be that the removal of
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/132e5e71aad91cfccc2a5648ad6e87becb6a6d7b/JenkinsJobs/Builds/I_build.groovy#L77-L78

in #2107 makes the difference?

**Comment by HannesWell** [comment]
In the past night triggering the I-build test succeeded as desired again:
https://download.eclipse.org/eclipse/downloads/drops4/I20240608-1800/testResults.php

There are quite some failures in JDT's tests but they also happened in the I-build before which I triggered manually:
https://download.eclipse.org/eclipse/downloads/drops4/I20240608-0320/

Trying to explain that in retrospective I would say that's because pipeline jobs need to run once to know their parameters:
- https://issues.jenkins.io/browse/JENKINS-41929
- https://issues.jenkins.io/browse/JENKINS-46594

And it looks like this behavior is for each kind of trigger?
Looking at the job configuration history I can see that SYSTEM changed the config to add the parameter as part of the job config outside the pipeline definition after the first run since deploying https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2108:
https://ci.eclipse.org/releng/job/AutomatedTests/job/ep433I-unit-cen64-gtk3-java17/jobConfigHistory/showDiffFiles?timestamp1=2024-06-07_13-33-43&timestamp2=2024-06-07_20-30-35

But I wonder if this has not been noticed before and it looks like that is because since
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2003/
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2004/

The parameters are defined within the pipeline instead of being defined as job parameters in the job configuration outside the pipeline itself.

But lets see if the next nightly I-build confirms that.

Since I'm currently working on unifying the I-build test-pipelines in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2005 I would like to fix the parameter definition on the first run after the pipelines have been merged to have less changes.

**Comment by merks** [comment]
Yes, it's a bit frustrating that parameter changes to a Jenkinsfile aren't noticed earlier and there is no mechanism (that I know of) for telling the job to process the Jenkinsfile purely for the purposes of updating the parameter details.

In some cases I did this:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/2084d62c-f5ec-4536-a35f-ce1eb2c7a313)

One can guard all the steps that it's the expected version and increment the version when the parameter definitions change.  The first launch will use the older version definition and skip everything.  But surely there must be a better way...

**Comment by HannesWell** [comment]
> Yes, it's a bit frustrating that parameter changes to a Jenkinsfile aren't noticed earlier and there is no mechanism (that I know of) for telling the job to process the Jenkinsfile purely for the purposes of updating the parameter details.

Absolutely. I have just submitted https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2129 to fix that.
For pipelines from the SCM (e.g. multibranch pipelines) this is not really a solution for the problem, but since we create the test jobs as standalone pipelines from a seed job, this works well.
