### ISSUE TITLE
Does the org.eclipse.rcp.configuration feature have a purpose, or can we delete it?

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.releng.aggregator#2109]
Yesterday I noticed that BIRT depends on something that is not on the release train, specifically the org.eclipse.rcp.configuration feature.  Then I wondered, can BIRT get rid of that thing, which of course begs the question, what does that thing provide?  So I looked today and see that this thing provides nothing and looking at the history has never provided anything.

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/37c677ad-6806-458d-8d2c-5a85294c598c)

This suggest to me that it is historical noise that we can eliminate.

**Comment by laeubi** [comment]
I'm not sure if it really is empty, it includes root files (that is these getting placed inside an eclipse installation when installed) so maybe it still serves a purpose but not much anyone else should depend on?

**Comment by laeubi** [comment]
Looking a bit closer it seems to copy the native launcher binaries into some test, can probably be replaced by https://tycho.eclipseprojects.io/doc/latest/tycho-p2-repository-plugin/repo-to-runnable-mojo.html today.

**Comment by HannesWell** [comment]
> Looking a bit closer it seems to copy the native launcher binaries into some test, can probably be replaced by https://tycho.eclipseprojects.io/doc/latest/tycho-p2-repository-plugin/repo-to-runnable-mojo.html today.

Another alternative might be to use the [org.eclipse.equinox.executable.feature](https://github.com/eclipse-equinox/equinox/tree/master/features/org.eclipse.equinox.executable.feature) instead? I haven't looked into the details yet, but there might have been a reason why another feature has been introduced for this?

**Comment by merks** [comment]
Yes, that seems to have similar build.properties:

https://github.com/eclipse-equinox/equinox/blob/master/features/org.eclipse.equinox.executable.feature/build.properties

If there's a reason to duplicated that, one used only for PDE build tests, I don't see it recorded anywhere. 

The build for this passed:

https://github.com/eclipse-pde/eclipse.pde/pull/1293

but apparently that doesn't really test the removal from the test.xml which is disturbing at best.

It seems the only thing to do is to proceed and see what happens.  Or?

**Comment by HannesWell** [comment]
> Yes, that seems to have similar build.properties:
> 
> https://github.com/eclipse-equinox/equinox/blob/master/features/org.eclipse.equinox.executable.feature/build.properties
> 
> If there's a reason to duplicated that, one used only for PDE build tests, I don't see it recorded anywhere.

In general it is similar, but in detail the rcp.config feature uses hard-coded relative paths pointing to the equinox.binaries repository, while the equinox.exe feature uses only project relative paths (that are feed by Maven).
In an I-build or releng verification build the result should be the same, depending on when the instructions are evaluated?

But looking at it I think it would be good to remove the rcp.config feature before submitting
- https://github.com/eclipse-equinox/equinox/pull/641


> It seems the only thing to do is to proceed and see what happens. Or?

Yes. Overall it is probably simpler to try it out investigating for a long time.

**Comment by merks** [comment]
I see that the feature was in this build:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/1e734103-8b68-4b5f-8d9c-50731f4a962a)

but is absent from this build:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/af28a2da-3b11-474d-80c2-1e9f424c326b)

So it appears we've successfully garbage collected this without ill effect.
