### ISSUE TITLE
https://download.eclipse.org/eclipse/updates/I-builds/ still pointing to 4.32-I-Build

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-platform/eclipse.platform.releng.aggregator#2117]
https://download.eclipse.org/eclipse/updates/I-builds/ is still referencing previous stream.
We should fix it, and also improve the documentation so that further updates to get forgotten when releasing/starting a new stream.

**Comment by sravanlakkimsetti** [comment]
@mickaelistria this gets updated once the 4.32 is released. this is one of the release activities

**Comment by MohananRahul** [comment]
> https://download.eclipse.org/eclipse/updates/I-builds/ is still referencing previous stream. We should fix it, and also improve the documentation so that further updates to get forgotten when releasing/starting a new stream.

Usually on the release day. ie tomorrow.

**Comment by mickaelistria** [comment]
OK. IMO it would make sense to update it when we start a new stream instead, after the 1st successful build upon version bumps. What do you think ?

**Comment by merks** [comment]
I tend to agree with @mickaelistria that once there is a newly populated 4.x I-Build it makes sense to update I-builds to this repository.  Yes, we keep the release "mostly hidden" until release day, but this is not a release repo.

The only small potential counter argument is that some SimRel projects might be building against this repo and if it switches before the final SimRel RC2 day, that might be surprising and undesirable.  But one could argue they shouldn't do that and in any event most certainly shouldn't be re-publishing the Platform's IUs...

**Comment by sravanlakkimsetti** [comment]
> I tend to agree with @mickaelistria that once there is a newly populated 4.x I-Build it makes sense to update I-builds to this repository. Yes, we keep the release "mostly hidden" until release day, but this is not a release repo.
> 
> The only small potential counter argument is that some SimRel projects might be building against this repo and if it switches before the final SimRel RC2 day, that might be surprising and undesirable. But one could argue they shouldn't do that and in any event most certainly shouldn't be re-publishing the Platform's IUs...

I am not sure how many teams know about these generic repos in the first place. We should be safe here. I feel we can move these generic repos once the first build is complete.

@MohananRahul Please move the generic repos immediately after the first build.

**Comment by merks** [comment]
Don't forget that 4.32 should be complete within 20 minutes...
