### ISSUE TITLE
Downgrade tycho version used in aggregator to 2.7.0

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#212]
We are facing issues with running out of heap with tycho 3.0.0 Move back to 2.7.0

**Comment by mickaelistria** [comment]
Are those issues described somewhere? IIRC there are some important patches for PGP stuff in 3.0.0-SNAPSHOT that were not backported to 2.x

**Comment by iloveeclipse** [comment]
I guess that one: https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2

**Comment by sravanlakkimsetti** [comment]
> Are those issues described somewhere? IIRC there are some important patches for PGP stuff in 3.0.0-SNAPSHOT that were not backported to 2.x

hmm in that case I will revert this and use tycho.version 2.7.0 in jdt pr-validation job

**Comment by merks** [comment]
Note that you'd need 2.7.1 to ensure that PGP signed content looks that way in the about dialog...

**Comment by sravanlakkimsetti** [comment]
I reverted the downgrade so we use tycho 3.0.0 in the build

**Comment by merks** [comment]
Note that I've been successfully using 2.7.1 for the PGP support which I tested locally for EPP and used it here:

https://git.eclipse.org/r/c/epp/org.eclipse.epp.packages/+/192644

So if there is some need to downgrade, use this version please.
