### ISSUE TITLE
Update site - "Eclipse Platform SDK" feature is missing

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.releng.aggregator#2126]
Since Eclipse 4.30 the "Eclipse Platform SDK" feature is missing from the update site.

1. In Eclipse open the "Install New Software" dialog
2. Select `https://download.eclipse.org/eclipse/updates/4.32` (or 4.30 or 4.31) as the update site
3. Ensure "Group items by category" is checked
4. Try to select something from the "Eclipse Platform SDK" category. It should contain the "Eclipse Platform SDK" feature but it doesn't. In fact even if "Group items by category" is unchecked the "Eclipse Platform SDK" feature is missing.

<img width="985" alt="Screenshot 2024-06-12 at 16 01 41" src="https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/600504/54e15a22-8546-4e5d-91a7-56ea1354095c">

<br/><br/>

In previous releases the "Eclipse Platform SDK" feature was present. Example:

<img width="1102" alt="Screenshot 2024-06-12 at 16 17 45" src="https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/600504/5a36f94e-2b1c-4070-b26e-1120a8f8b561">

**Comment by vogella** [comment]
I think you have to use the    <unit id="org.eclipse.platform.feature.group" version="0.0.0"/> now. IIRC the SDK feature was removed as it was not

**Comment by HannesWell** [comment]
I'm not aware that the org.eclipse.sdk feature was removed and it is still in (heavy?) use.
But I also see it being present when looking at https://download.eclipse.org/eclipse/updates/4.32/R-4.32-202406010610/features

**Comment by Phillipus** [comment]
I extracted the `content.xml` file from https://www.eclipse.org/downloads/download.php?file=/eclipse/updates/4.32/R-4.32-202406010610/content.jar and compared it with the one from https://www.eclipse.org/downloads/download.php?file=/eclipse/updates/4.29/R-4.29-202309031000/content.jar and there's a whole section missing for `org.eclipse.platform.sdk`.

This is some of that xml:

```xml
<unit id="org.eclipse.platform.sdk" version="4.29.0.I20230903-1000">
    <update id="org.eclipse.platform.sdk" range="[4.0.0,4.29.0.I20230903-1000)" severity="0" description="An update for 4.x generation Platform SDK"/>
    <properties size="5">
        <property name="org.eclipse.equinox.p2.name" value="Eclipse Platform SDK"/>
        <property name="org.eclipse.equinox.p2.type.product" value="true"/>
        <property name="org.eclipse.equinox.p2.type.group" value="true"/>
        <property name="org.eclipse.equinox.p2.description" value="4.29 Release of the Platform SDK."/>
        <property name="org.eclipse.equinox.p2.provider" value="Eclipse.org"/>
    </properties>

```

(Note, I have no need of this feature myself, I'm just reporting it in case this is a bug)

**Comment by akurtakov** [comment]
This is result of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1235 in which products and features have been reduced to more manageable list.

**Comment by Phillipus** [comment]
> This is result of #1235 in which products and features have been reduced to more manageable list.

OK, thanks for the info. I just thought I would report this in case of problems.

As the group category "Eclipse Platform SDK" is now empty should that also be removed? (Sorry, I don't know where/how that is so can't provide PR)

**Comment by HannesWell** [comment]
> This is result of #1235 in which products and features have been reduced to more manageable list.

That's right. Sorry I assumed we are talking about a feature. But if you are looking for a replacement in your target-platform, I suggest to use the `org.eclipse.sdk` feature. It should contain all artifacts previously contained in the platform.sdk.product and some more. 

> As the group category "Eclipse Platform SDK" is now empty should that also be removed? (Sorry, I don't know where/how that is so can't provide PR)

That sounds reasonable, but I cannot find where it is defined.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/de6180058bf13be5f9412418578e4b31a37c391c/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml
does not define any category and if search all sdk repos for `Eclipse Platform SDK` I don't get hits that seem to be associated.
Are you sure the `Eclipse Platform SDK` category is still there? If I check the 4.32 content.jar I can't find it.

**Comment by Phillipus** [comment]
> Are you sure the Eclipse Platform SDK category is still there? If I check the 4.32 content.jar I can't find it.

It's showing in the update dialog.

Is a category defined in a "category.xml" file?

**Comment by merks** [comment]
One has to look in the right place.  A release repository is a composite:
```
<?xml version='1.0' encoding='UTF-8'?>
<?compositeMetadataRepository version='1.0.0'?>
<repository name='The Eclipse Project repository' type='org.eclipse.equinox.internal.p2.metadata.repository.CompositeMetadataRepository' version='1.0.0'>
  <properties size='3'>
    <property name='p2.timestamp' value='1718200308702'/>
    <property name='p2.compressed' value='true'/>
    <property name='p2.atomic.composite.loading' value='true'/>
  </properties>
  <children size='2'>
    <child location='categories'/>
    <child location='R-4.32-202406010610'/>
  </children>
</repository>
```

So you have to look here:

https://download.eclipse.org/justj/?file=eclipse/updates/4.32/categories

Where that comes from and how IUs are associated with it's categories is not yet clear.

**Comment by merks** [comment]
@MohananRahul 

I really can't find where this comes from.  E.g., here it is again in the 4.33-I-builds:

https://download.eclipse.org/eclipse/updates/4.33-I-builds/categories/content.jar

Maybe it's just copied from one place to another each time.

The generated report:

https://download.eclipse.org/oomph/archive/reports/download.eclipse.org/eclipse/updates/4.33-I-builds/index.html

Shows that it's empty:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/9724b0aa-2e15-4774-8fb3-dc7a6e87c044)

**Comment by MohananRahul** [comment]
> @MohananRahul
> 
> I really can't find where this comes from. E.g., here it is again in the 4.33-I-builds:
> 
> https://download.eclipse.org/eclipse/updates/4.33-I-builds/categories/content.jar
> 
> Maybe it's just copied from one place to another each time.
> 
> The generated report:
> 
> https://download.eclipse.org/oomph/archive/reports/download.eclipse.org/eclipse/updates/4.33-I-builds/index.html
> 
> Shows that it's empty:
> 
> ![image](https://private-user-images.githubusercontent.com/208716/339224961-9724b0aa-2e15-4774-8fb3-dc7a6e87c044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTgxMzEsIm5iZiI6MTcxODI1NzgzMSwicGF0aCI6Ii8yMDg3MTYvMzM5MjI0OTYxLTk3MjRiMGFhLTJlMTUtNDc3NC04ZmIzLWRjN2E2ZTg3YzA0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwNTUwMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTAxMzA4ODRjNzE3MjZjYzBjZGY5OWJmYjcwZTM3NjM1NmVjMjA4ODA4MzgzOWU1NjhkZjNmY2QyYzkxNjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8hKU5yfqSjH0ET0vAgNIwIdjoVOpsmVP5f6c0W6_QfM)

This is copied from template format while creating new stream. https://download.eclipse.org/eclipse/updates/template_repo/

**Comment by merks** [comment]
@MohananRahul

So "we" should fix these:

- https://download.eclipse.org/eclipse/updates/4.33/categories/
- https://download.eclipse.org/eclipse/updates/template_repo/categories/

Probably also this:

- https://download.eclipse.org/eclipse/updates/4.33-I-builds/categories/

and maybe also these

- https://download.eclipse.org/eclipse/updates/4.32/categories/
- https://download.eclipse.org/eclipse/updates/4.31/categories/

Here is the modified content.jar renamed to append .zip so I can drop it here:

[content.jar.zip](https://github.com/user-attachments/files/15814918/content.jar.zip)

**Comment by MohananRahul** [comment]
> @MohananRahul
> 
> So "we" should fix these:
> 
> * https://download.eclipse.org/eclipse/updates/4.33/categories/
> * https://download.eclipse.org/eclipse/updates/template_repo/categories/
> 
> Probably also this:
> 
> * https://download.eclipse.org/eclipse/updates/4.33-I-builds/categories/
> 
> and maybe also these
> 
> * https://download.eclipse.org/eclipse/updates/4.32/categories/
> * https://download.eclipse.org/eclipse/updates/4.31/categories/
> 
> Here is the modified content.jar renamed to append .zip so I can drop it here:
> 
> [content.jar.zip](https://github.com/user-attachments/files/15814918/content.jar.zip)

let me check and do

**Comment by MohananRahul** [comment]
Removed Empty category:

<img width="772" alt="image" src="https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/121536011/4e5b0dd7-2503-42fa-804d-a33a338a14c7">

**Comment by Phillipus** [comment]
Can confirm the empty category is gone now in the 4.30, 4.31 and 4.32 update sites. Thanks!

**Comment by akurtakov** [comment]
CLosing as per previous comments

**Comment by merks** [comment]
@MohananRahul 

Thank you!  😀

**Comment by HannesWell** [comment]
Thank you for fixing that!

Ideally these categories would be defined in some 'source' files and not only in binaries.

Do you think this would be possible?

**Comment by laeubi** [comment]
@merks  the "update-site" packaging can be sourced from various sources:

- product(s)
- `category.xml`
- `p2.inf`

none of them is mandatory...

The mojo used there is [tycho-p2-repository:assemble-repository](https://tycho.eclipseprojects.io/doc/latest/tycho-p2-repository-plugin/assemble-repository-mojo.html) has a parameter [createArtifactRepository](https://tycho.eclipseprojects.io/doc/latest/tycho-p2-repository-plugin/assemble-repository-mojo.html#createArtifactRepository) that can skip generation of artifact repository, you can also set the name, properties and so on. The advanced syntax supported by P2/Tycho in category.xml is explained [here](https://tycho.eclipseprojects.io/doc/latest/Category.html).

So I think its just a matter of creativity to combine all those to create such thing "from code", one even can define everything in a `p2.inf` file.

**Comment by merks** [comment]
Yes, problems to be solved are generally a matter of sufficient creativity along available time.  Where there's a will, there's a way...

Also, there is generally a list of all problems that one might spend time trying to resolve and the prioritization within that list of any particular problem.  So who will prioritize this problem to the top of their queue?  👼

**Comment by laeubi** [comment]
If one think its useful just create an issue and describe the input and the desired outcome, I'll try to take a look, I just wanted to note that actually the tooling should be there... I just don't know about where / when / why / ... about this.

**Comment by merks** [comment]
A simple solution is to keep the content.xml is source from, build a jar from it, and call it done..   

If I understand the problem correctly we'd want to maintain this entire thing in source form so that we can change it and find it in the future rather than knowing to look here:

https://download.eclipse.org/eclipse/updates/template_repo/

**Comment by HannesWell** [comment]
> A simple solution is to keep the content.xml is source from, build a jar from it, and call it done..
> 
> If I understand the problem correctly we'd want to maintain this entire thing in source form so that we can change it and find it in the future rather than knowing to look here:
> 
> https://download.eclipse.org/eclipse/updates/template_repo/

A bit hacky, but definitively better than the current situation. 😅

Btw. can't we just define the category as usual in the [eclipse.platform.repository/category.xml](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/0437e5fad74c4a8a3429a2a2f857406e25036b09/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml)? Or is it necessary to maintain the categories in a sub-repo?

**Comment by merks** [comment]
I'm not sure if there is a specific reason to avoid having the categories redefined separately (and in duplicate) in each and every simple repository.  I tested a site that is a composite where each child does define the categories and p2 does unify them even though each category IU has a different version:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/7d08adcb-ce11-49c3-8c1e-3b64576eb270)

So I don't know of a compelling reason or any reason not to define this in the category.xml in the normal way.  Probably just for historical reasons.
