### ISSUE TITLE
Comparator Errors in 4.33 I20240703-1800

### ISSUE THREAD

**Issue by MohananRahul** [eclipse-platform/eclipse.platform.releng.aggregator#2163]
Comparator Error found :
https://download.eclipse.org/eclipse/downloads/drops4/I20240703-1800/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

1.  eclipse.jdt.core/org.eclipse.jdt.core.tests.performance/pom.xml
   no-classifier: different
      org/eclipse/jdt/core/tests/performance/FullSourceWorkspaceBuildTests.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

**Comment by MohananRahul** [comment]
This is the comparison 

<img width="1644" alt="image" src="https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/121536011/e5b62c87-2d11-4480-a4e5-5641e567082d">

**Comment by mpalat** [comment]
This is due to a compiler change - investigating

**Comment by MohananRahul** [comment]
https://ci.eclipse.org/releng/job/Builds/job/I-build-4.33/49/ 

No Comparator Errors https://download.eclipse.org/eclipse/downloads/drops4/I20240704-0240/
