### ISSUE TITLE
[platform-releng-dev] 4.33 I-Build: I20240709-1820 - BUILD FAILED

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#2178]
See https://ci.eclipse.org/releng/job/Builds/job/I-build-4.33/56/console
```
10:56:52  [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.8:compile (default-compile) on project org.eclipse.jdt.debug: Compilation failure: Compilation failure: 
10:56:52  [ERROR] /home/jenkins/agent/workspace/Builds/I-build-4.33/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/eclipse.jdt.debug/org.eclipse.jdt.debug/model/org/eclipse/jdt/debug/core/JDIDebugModel.java:[67] 
10:56:52  [ERROR] 	@SuppressWarnings("deprecation")
10:56:52  [ERROR] 	                  ^^^^^^^^^^^^^
10:56:52  [ERROR] Unnecessary @SuppressWarnings("deprecation")
```

Looks like caused by recent compiler changes in https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2680

**Comment by iloveeclipse** [comment]
I fear this will require more rebuilds, let see how many unneeded deprecation warnings we have elsewhere. I've fixed one in  JDT Debug https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/457...

**Comment by iloveeclipse** [comment]
Started new build https://ci.eclipse.org/releng/job/Builds/job/I-build-4.33/58/

**Comment by akurtakov** [comment]
@iloveeclipse Please try using https://ci.eclipse.org/platform/job/eclipse.platform.releng.aggregator/job/master/ to test instead of starting new I-builds. That should reduce needless tags in git repos.

**Comment by iloveeclipse** [comment]
Fixed, see https://download.eclipse.org/eclipse/downloads/drops4/I20240710-0530
