### ISSUE TITLE
Latest  jarsign service produces CODESIGN.SF and CODESIGN.RSA instead of ECLIPSE_SF and ECLIPSE_.RSA

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.releng.aggregator#2193]
If you look at a file signed with the latest signing service, e.g., 

https://www.eclipse.org/downloads/download.php?file=/eclipse/updates/4.33-I-builds/I20240722-1800/plugins/org.eclipse.core.filesystem_1.11.0.v20240722-2044.jar

you'll see that the signature files have a different names

![image](https://github.com/user-attachments/assets/7c56089f-3a86-47a2-b269-2bd00b66b7f1)

The names previously were like this:

![image](https://github.com/user-attachments/assets/ef58bc12-aecd-4bb0-adbb-2c74f5d57ad1)

I searched my SDK IDE and found these references to the old name:

![image](https://github.com/user-attachments/assets/8a337c11-3da7-46f7-bc8f-bf8f8c926f24)

I expect all of these need attention and that there might be more things that need attention.

**Comment by merks** [comment]
@akurtakov @iloveeclipse @laeubi 

FYI, I expect all the above places will need attention...

**Comment by iloveeclipse** [comment]
Does it mean, we have to touch every bundle to have new `CODESIGN.SF` and `CODESIGN.RSA` files, or do you mean that we should check/update scripts that do something with these signature files?

**Comment by merks** [comment]
No, I don't think we need to force new signatures.  I think the first three here need to specify additional patterns and the last thing here needs to update the regex to include also the new name:

![image](https://github.com/user-attachments/assets/4a2724cd-d84f-4f34-880f-0227b45d4d8a)

If folks agree with that, I'll create the necessary PRs for them...

**Comment by merks** [comment]
@iloveeclipse 

All the changes except the JDT one are merged.  So I'll close this as done now.

**Comment by iloveeclipse** [comment]
JDT is also merged now. Thanks Ed.

**Comment by HannesWell** [comment]
Thank you Ed for all the fixes!
But now that the old name is used again (https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4680#note_2548722), should we revert these in order to 'fail-fast' or at least faster?

**Comment by merks** [comment]
I thought the suggestion was we do both.  We did already produce and publish to download.eclipse.org with the new signature name so now that will continue to play well into the future is not clear.  Given they are in the wild, it seems best to accommodate that name.  Even better would be to not care about the actual name.

In any case, I'm not sure what if anything was failing yet without the changes and I don't know what will not work well with the current mixture.  Someone else can decide that.

**Comment by laeubi** [comment]
The only point we have this is because sometimes we build without signing (e.g. verification builds, local builds) and sometimes with (e.g. i-build) so we don't want the build to complain about additional files. From that perspective, even `*.SF` and `*.RSA` are sufficient, an exact pattern does not buy us much.

**Comment by merks** [comment]
Yes, given the comments on the issue, the file name is arbitrary and only the location in META-INF and file suffixes are relevant, at least as I understand it.  So all the places changed could be improved with better, more-general patterns.

**Comment by HannesWell** [comment]
> Yes, given the comments on the issue, the file name is arbitrary and only the location in META-INF and file suffixes are relevant, at least as I understand it. So all the places changed could be improved with better, more-general patterns.

Yes that would probably the best. I just wanted to have discussed that now that the service is back to the previous state.
I think we should go with `META-INF/*.RSA` and `META-INF/*.SF` (a bit more specific than what Christoph suggested).

**Comment by ewillink** [comment]
Reversion to the traditional names is presumably necessary to provide the compatibility that allows users of an older platform (expecting traditional names) to use a new add-on project built with 'new' traditional names.

**Comment by merks** [comment]
In general the name is arbitrary and is generally (expected) only to be consumed by the signature validation logic of the Java runtime.   In the BIRT build, somewhere they expected ECLIPSEF and somewhere else ELCLIPSE_ so presumably/maybe the name has changed in the past.  I think for the Platform it would be better to do as @HannesWell  suggests.  The PRs are all linked so the place to do this are clear.
