### ISSUE TITLE
Commits not linked to any tickets

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#22]
Commit https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/f5bf4f124b8563a05d4a966db6628b29566417be
should be linked to
https://bugs.eclipse.org/bugs/show_bug.cgi?id=578004
but of course there is nothing.

If we now move to github, should we have bugs in github or should link to bugzilla, but just committing without any ticket should be avoided, at least for all non trivial commits.

**Comment by rolfth** [comment]
Commit d3d87307b82722831e9846a863ae9d9813a7691a is linked to https://bugs.eclipse.org/bugs/show_bug.cgi?id=578341 in bugzilla.

However, the pull-request was not linked yet, as is for Gerrit Changes.

**Comment by rolfth** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=462471 for linking PR with Bugzilla

**Comment by akurtakov** [comment]
@rolfth so is there some configuration we are missing here or this is already working and issue can be closed?

**Comment by iloveeclipse** [comment]
The one from bug description:
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/21
https://bugs.eclipse.org/bugs/show_bug.cgi?id=578004

**Comment by akurtakov** [comment]
I asked on the bugzilla  @rolfth  pointed to but overall I don't have high hopes as bugzilla is in the same "deprecated" state as gerrit. Thus it's better to use Github issues.

**Comment by akurtakov** [comment]
Linking in bugzilla would have to be manual if needed but it's preferred to use Github issues which will do the linking automatically.
