### ISSUE TITLE
arm-64 application crashes with an error related to code signing.

### ISSUE THREAD

**Issue by vik-chand** [eclipse-platform/eclipse.platform.releng.aggregator#225]
See bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=579730
From above link

"I am testing Eclipse RCP application builds for MacOS. The application is built for both x86-64 and arm-64 architectures using target of Eclipse 2022-03 (4.23.0). Using PDE build wizard. The x86-64 binaries are good and running with no issues on various computers. However, arm-64 application crashes with an error related to code signing. Attached is the crash report dump. I have verified the signature of the binary produced by the build in /MacOS folder and it looks like this: 

***
Identifier=SigningServlet-7029897199180243499-unsigned-eclipse
Format=Mach-O thin (arm64)
CodeDirectory v=20500 size=767 flags=0x10000(runtime) hashes=14+5 location=embedded
Signature size=8998
Authority=Developer ID Application: Eclipse Foundation, Inc. (JCDTMS22B4)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=10 Jun 2021 at 14:36:42
Info.plist=not bound
TeamIdentifier=JCDTMS22B4
Runtime Version=11.1.0
Sealed Resources=none
Internal requirements count=1 size=212
***

Apparently Apple doesn't like this signature.. Or is there another possible issue?"

**Comment by Phillipus** [comment]
My 2 cents - I tested our RCP app using the .product file's "Eclipse product export wizard" for aarch64 and the resulting binary launched OK on Mac M1 Mini, macOS 12.3.1

**Comment by Phillipus** [comment]
One thing I have to do to get it to work is change the output folder name from `macosx.cocoa.aarch64` to `Eclipse` and edit the `*.ini` file to reference this.

**Comment by vik-chand** [comment]
cc @sravanlakkimsetti

**Comment by akurtakov** [comment]
Should this one be closed now?

**Comment by akurtakov** [comment]
I take no reply as yes.
