### ISSUE TITLE
Native support for Eclipse SDKs on riscv64

### ISSUE THREAD

**Issue by yuzibo** [eclipse-platform/eclipse.platform.releng.aggregator#2310]
I am trying to build Eclipse SDKs on riscv64. It's obvious that this is the correct repo so I opened the issue to keep track of various tasks done and/or underway like WoA [did](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/577).

- [x] add support for riscv64 to `eclipse.platform.swt` submodule
  - [x] https://github.com/eclipse-platform/eclipse.platform.swt/pull/1444 for build.sh
  - [x] https://github.com/eclipse-platform/eclipse.platform.swt/pull/1445 add linux riscv64 build
  - [x] https://github.com/eclipse-platform/eclipse.platform.swt/pull/1469 Fix riscv64 MANIFEST.MF header field(fix pr 1445)
  - [x] https://github.com/eclipse-platform/eclipse.platform.swt/pull/1474 Build gtk.linux.riscv64 native SWT fragment
  - [x] https://github.com/eclipse-platform/eclipse.platform.swt/pull/1490 bump riscv64 version [closed, combined into 1474] 
  - [x] https://github.com/eclipse-platform/eclipse.platform.swt/pull/1485 Add support riscv64 with p2.inf
  - [ ] Once JustJ supports riscv64, to reset [Jenkins](https://github.com/eclipse-platform/eclipse.platform.swt/pull/1474/files#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8) to use it as native jdk
- [x] Add support for riscv64 on `equinox` submodule
  - [x] https://github.com/eclipse-equinox/equinox/pull/669
  - [x] https://github.com/eclipse-equinox/equinox/pull/672 Version bumps for 4.34 stream [closed; combined into the [PR](https://github.com/eclipse-equinox/equinox/pull/669) ]
  - [x] https://github.com/eclipse-equinox/equinox/pull/680
  - [x] ToDo: once `gtk.linux.riscv64` environment is enabled in general, revert the temporary addition of the [linux.riscv64 environment in o.e.equinox.executable.feature/pom.xml](https://github.com/eclipse-equinox/equinox/pull/669/files#diff-ed29dcec78f53ccece5e89f61195150d2356f80b793d3368dce3bc4247d0167a):
    - [x] https://github.com/eclipse-equinox/equinox/pull/681
  - [ ] #2632
- [x] add support for riscv64 on `eclipse.platform.ui` submodule
  - [x] https://github.com/eclipse-platform/eclipse.platform.ui/pull/2318  
- [x] eclipse.platform.releng.aggregator
  - [x] https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2348 
  - [x] https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2394 Add linux.riscv64 environment to eclipse-platform-parent and publish win32.aarch64 artifacts 
  - [x] https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2397 Add linxu/gtk/riscv64 the SDK4Mvn.aggr
- [x] add support for riscv64 on `eclipse.platform` submodule
  - [x] https://github.com/eclipse-platform/eclipse.platform/pull/1575  
- [x] Add support for riscv64 on JustJ
  - [x] https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5031 Add riscv64 ci node for JustJ 
  - [x] [Update for Java 23 and add scaffolding for riscv64](https://github.com/eclipse-justj/justj/commit/07754f5857b045445a40f26baf37f0e570e27a91)
  - [x] [Fully enable riscv64 support](https://github.com/eclipse-justj/justj/commit/6571be4b505fc0a0e1b2d8fa40cc87bba979b48c)
- [x] Add riscv64 support for eclipse infra 
  - [x] https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4978 Add riscv64 ci node for eclipse
- [x] external porting work
  - [x] https://github.com/java-native-access/jna/issues/1622
- [x] Package support for riscv64
  - [x] https://github.com/eclipse-packaging/packages/issues/213  

Next I will always update this.

**Comment by Sakura286** [comment]
On Debian Sid riscv64, Milk-V Pioneer.
![1510c05927436e18546f7e2c4f4015b](https://github.com/user-attachments/assets/b931149c-5786-4e6c-bcd6-f199d02ff47f)

**Comment by yuzibo** [comment]
That is amazing!

**Comment by HannesWell** [comment]
Since the latest I-build the Eclipse SDK is also build for linux.riscv64
- https://download.eclipse.org/eclipse/downloads/drops4/I20240929-0810/

Implementation-wise almost everything is done now, the last pending two PRs should succeed now too.

The only thing that are missing to complete this entirely are some form of tests, at least smoke tests, ideally full I-build tests (for Windows on ARM they are still pending since some preparatory work to simplify their setup is not yet completed).

Furthermore we could/should provide the Eclipse-Packages for linux.riscv64 too, similar to WoA:
- https://github.com/eclipse-packaging/packages/issues/162

But unlike WoA since shouldn't be too difficult since Temurin already provides JDKs for linux.riscv64 and JustJ is now able to provide JDK bundles since there is also a Eclipse-SDK for it.

**Comment by Sakura286** [comment]
Test with the newest **official Integration Build**, on Debian Sid riscv64, Milk-V Pioneer, with x11 forward:

![image](https://github.com/user-attachments/assets/509ca1c2-e6fa-4963-aa83-121a2fd0d363)

https://download.eclipse.org/eclipse/downloads/drops4/I20240929-0810/

Choose `Eclipse SDK` -> `Linux (64 bit version for RISC-V)` to download.

**Comment by HannesWell** [comment]
> > Since the latest I-build the Eclipse SDK is also build for linux.riscv64
> > 
> > * https://download.eclipse.org/eclipse/downloads/drops4/I20240929-0810/
> 
> I would like to express my heartfelt gratitude to everyone for your efforts in achieving Eclipse support for riscv64 here. Your hard work and help are truly appreciated!

Thank you for these nice words, it's great to get them.
And thanks for all your contributions.
I think adding support for more arches challenges the complexity of the overall Eclipse SDK project and helps to reduce it.

> > But unlike WoA since shouldn't be too difficult since Temurin already provides JDKs for linux.riscv64 and JustJ is now able to provide JDK bundles since there is also a Eclipse-SDK for it.
> 
> Yeah, I noticed this also. I will ping JustJ first.

@merks is already aware of the need for a change in JustJ and has already prepared it:
- https://github.com/eclipse-justj/justj/commit/07754f5857b045445a40f26baf37f0e570e27a91
- https://github.com/eclipse-justj/justj/commit/6571be4b505fc0a0e1b2d8fa40cc87bba979b48c

and is currently working on providing the new artifacts.

**Comment by merks** [comment]
@yuzibo 

There is an installer with an embedded JustJ JRE available for rsicv64:

https://download.eclipse.org/oomph/products/latest/eclipse-inst-jre-linux-riscv64.tar.gz

The installer filters products that don't support that architecture (and I've been fine-tuning that support today), so it only shows applicable products, i.e., only the Eclipse SDK can currently be installed:

![image](https://github.com/user-attachments/assets/1a54607b-4283-42d5-9a55-2919f648c14a)

It would be much appreciated if you could test whether the riscv64 installer works given I have no way of testing it myself.

**Comment by yuzibo** [comment]
> @yuzibo
> 
> There is an installer with an embedded JustJ JRE available for rsicv64:
> 
> https://download.eclipse.org/oomph/products/latest/eclipse-inst-jre-linux-riscv64.tar.gz
> 

\o/.

> 
> It would be much appreciated if you could test whether the riscv64 installer works given I have no way of testing it myself.

Okay, No problem, I will test it on my local riscv64 hardware ASAP(maybe in next days because I am on my holiday).

Thanks for your work again!

**Comment by yuzibo** [comment]
> @yuzibo
> 
> There is an installer with an embedded JustJ JRE available for rsicv64:
> 
> https://download.eclipse.org/oomph/products/latest/eclipse-inst-jre-linux-riscv64.tar.gz
> 

if i didn't do anything wrong, I think the eclipse installer is working:
![in-pocess](https://github.com/user-attachments/assets/978dcbaa-8425-404c-9e10-8248f1dd10f6)
![launch](https://github.com/user-attachments/assets/deb2d9c3-f6b2-40e6-9ab8-4bbc3e381a3f)

Thanks for your work again!

**Comment by yuzibo** [comment]
So the left work for riscv64 on Eclipse is to use `justj`  to replace [temurin](https://github.com/eclipse-platform/eclipse.platform.swt/pull/1474/files#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8) I think. 

But I am not sure how long this will happened to update the link of [download](https://github.com/eclipse-platform/eclipse.platform.swt/pull/1474/files#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8R61)

**Comment by merks** [comment]
As mentioned in https://github.com/eclipse-packaging/packages/issues/213#issuecomment-2393884004 mostly everything is in place to produce riscv64 packages for M2.

It will appears here:

https://www.eclipse.org/downloads/packages/release/2024-12/

**Comment by sratz** [comment]
The riscv-build2 node on Jenkins currently fails to launch, blocking building of SWT native fragments: https://ci.eclipse.org/releng/computer/riscv%2Dbuild2/

**Comment by merks** [comment]
For what it's worth, the riscv node did start and complete:

![image](https://github.com/user-attachments/assets/90cef322-bf96-4a81-8161-b9eed1e823b2)

**Comment by akurtakov** [comment]
Should we close this one?

**Comment by yuzibo** [comment]
Thanks! 
I think we can close it also as we have done everything almost already and I will track the  https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2632

**Comment by HannesWell** [comment]
Thank you @yuzibo for all your work to make this possible.

As the very final step I have now created a change to add a smoke-test for linux.riscv64:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2641
