### ISSUE TITLE
www.eclipse.org/swt.git

### ISSUE THREAD

**Issue by niraj-modi** [eclipse-platform/eclipse.platform.releng.aggregator#233]

**Comment by niraj-modi** [comment]
@sravanlakkimsetti 
We have got swt website repo moved to github via:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1198

Next step is to work on Jenkins file creation via:
https://github.com/eclipse-platform/www.eclipse.org-swt/issues/1

**Comment by akurtakov** [comment]
This one is done AFAICT.
