### ISSUE TITLE
Replace SWT docker-images in platform.releng.aggregator by docker images from SWT repository

### ISSUE THREAD

**Issue by HannesWell** [eclipse-platform/eclipse.platform.releng.aggregator#2401]
Currently there is a docker-image dedicated and used by SWT which is maintained in the platform.releng.aggregator repository:
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/650d043c6efef7748dc6fb0c2aa4f0b66a8e5f45/cje-production/dockerfiles/centos-gtk4-mutter/9-swtBuild

And there is a Docker-image in the SWT repository for which I'm not aware of a user (it also seems not to be build and published):
https://github.com/eclipse-platform/eclipse.platform.swt/blob/8c39dcdfd2e28009e3866e61e1d40bf30d583c66/container/Dockerfile

My proposal is to remove unused images and to consider to maintain the image used by SWT (and Equinox) only in the SWT repository, to have it closer to the code that (mainly) uses it.

And since the [`centos-gtk4-mutter/9-gtk4`](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/cje-production/dockerfiles/centos-gtk4-mutter/9-gtk4) has a lot of lines in common with [`centos-gtk4-mutter/9-swtBuild`](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/cje-production/dockerfiles/centos-gtk4-mutter/9-swtBuild) I wonder if the latter could/should inherit from the former?

**Comment by akurtakov** [comment]
I'll drop the swt one as splitting docker images definitions in multiple repos when used by more than the repo itself (e.g. equinox should use it too) only complicates where to look for things.

**Comment by akurtakov** [comment]
One in swt is gone now, feel free to close this if you don't plan to use it for other docker images rearrangements too.

**Comment by HannesWell** [comment]
Thank you Alex for reducing the duplication.

> And since the centos-gtk4-mutter/9-gtk4 has a lot of lines in common with centos-gtk4-mutter/9-swtBuild I wonder if the latter could/should inherit from the former?

That's from my POV the only remaining point in this issue. 
If that is done or decided not to be done, this issue is completed.

**Comment by akurtakov** [comment]
@laeubi What is the status of switching swt build to debian for gtk4 ?
@HannesWell I believe both centos 9 can be removed now - due to it being "rolling release" and creating too new glibc deps - aka won't be used for compiling.

**Comment by HannesWell** [comment]
Thank you Alex for carrying this out!
