### ISSUE TITLE
Signature mismatch on mavenCentral JFace starting in 4.33 

### ISSUE THREAD

**Issue by nedtwigg** [eclipse-platform/eclipse.platform.releng.aggregator#2422]
I am seeing these errors:

```
java.lang.SecurityException: class "org.eclipse.jface.text.ITextSelection"'s signer information does not match signer information of other classes in the same package

java.lang.SecurityException: class "org.eclipse.jface.text.ITextViewer"'s signer information does not match signer information of other classes in the same package
```

I am downloading the artifacts from Maven Central using two different projects

- https://github.com/diffplug/goomph
- https://github.com/equodev/equo-ide

They both end up generating the same signing errors in Eclipse 4.33, I did not see them in 4.32.

**Comment by akurtakov** [comment]
@merks has some tooling to monitor these so hopefully they no longer happen. Long term and "safer" (not relying on someone monitoring a list constantly) are 2 possible things - stop jarsigning or preferably get rid of the split package. As Maven central doesn't allow changing already deployed artifacts there isn't much we can do now.

**Comment by merks** [comment]
This was reported in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2335 and as @akurtakov mentions, testing has been put in place to prevent a recurrence for the next release to Maven Central in December.  

For example, a new instance of the problem has just arisen and will now need attention:

https://ci.eclipse.org/oomph/job/repository-analyzer/lastCompletedBuild/testReport/eclipse.updates._4_34_I_builds.I20241003_0820/Simple/validSplitPackages_org_eclipse_core_internal_runtime_0_0_0/
