### ISSUE TITLE
Y Build for Java 24 work off BETA_JAVA24 branches

### ISSUE THREAD

**Issue by jarthana** [eclipse-platform/eclipse.platform.releng.aggregator#2434]
We need to start making Y builds for Java 24 development. At the moment, only jdt.core has branched but should be good enough to kick off the Y builds. Most importantly, I think this help the PRs going into the BETA branch. At the moment, the PRs seem to be failing since they baseline is that of R4_33.

**Comment by jarthana** [comment]
Looks like this is still failing.
https://ci.eclipse.org/releng/job/YPBuilds/job/Y-build-4.34/6/console

**Comment by MohananRahul** [comment]
https://ci.eclipse.org/releng/job/YPBuilds/job/Y-build-4.34/10/ YBuild created
