### ISSUE TITLE
4.34 M2 build link is not available on https://download.eclipse.org/eclipse/downloads/

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#2467]
https://download.eclipse.org/eclipse/downloads/ should have a link to 4.34 M2.

I assume it should correspond to build https://download.eclipse.org/eclipse/downloads/drops4/I20241017-2140/ 

See for example why it is needed: https://gitlab.com/qfs/qfs-swt-patches/-/issues/4#note_2168859909

**Comment by iloveeclipse** [comment]
@MohananRahul : could you please chek this?

**Comment by iloveeclipse** [comment]
Thanks @MohananRahul.
Should we also send mail to platform releng list?

**Comment by MohananRahul** [comment]
We typically don't send notification / promote builds for M2. and As outlined in the [RELEASE.md](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/RELEASE.md#milestonerc-week).

**Comment by iloveeclipse** [comment]
OK, thanks, then we are done here.
