### ISSUE TITLE
Linux test results summary broken

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#2494]
See https://download.eclipse.org/eclipse/downloads/drops4/I20241028-1800/

Probably caused by renaming configs in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2481

All three test rows for Linux show same result for the Linux ep434I-unit-linux-x86 64-java23_linux.gtk.x86_64 23 build:

![image](https://github.com/user-attachments/assets/fe8989d9-ef67-4dc0-9503-c91a0587d87a)

In reality all three rows can't be same as we have different count of compiler tests per build.

@HannesWell : please check.

**Comment by HannesWell** [comment]
Verified with https://download.eclipse.org/eclipse/downloads/drops4/I20241029-1420/ that this is really fixed.
And the labels now look good again as well.

Thanks for the report.
