### ISSUE TITLE
More plugins to join Y-Builds from their BETA_JAVA24 branch

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-platform/eclipse.platform.releng.aggregator#2505]
Follow-up from #2434:

Meanwhile also jdt.ui and jdt.debug have BETA_JAVA24 branches. Moreover, successful test runs on JDK 24 require that jdt.debug can recognize this version.

OTOH, after some successful builds, I see some inconsistencies and failures in latest Y-Builds:
* https://download.eclipse.org/eclipse/updates/4.34-Y-builds/Y20241029-1000 contains previous artifacts, see:
   *  [org.eclipse.jdt_3.19.700.v20241029-1000.jar](https://www.eclipse.org/downloads/download.php?file=/eclipse/updates/4.34-Y-builds/Y20241029-1000/plugins/org.eclipse.jdt_3.19.700.v20241029-1000.jar) - good
   * [org.eclipse.jdt.core.compiler.batch_3.40.50.v20241028-0654.jar](https://www.eclipse.org/downloads/download.php?file=/eclipse/updates/4.34-Y-builds/Y20241029-1000/plugins/org.eclipse.jdt.core.compiler.batch_3.40.50.v20241028-0654.jar) - not good
* Failure in https://ci.eclipse.org/releng/job/YPBuilds/job/Y-build-4.34/27 :
```
[2024-11-01T14:14:12.664Z] [ERROR] Cannot resolve project dependencies:
[2024-11-01T14:14:12.664Z] [ERROR]   Software being installed: org.eclipse.equinox.sdk.product 4.34.0.qualifier
[2024-11-01T14:14:12.664Z] [ERROR]   Missing requirement: org.eclipse.equinox.sdk.feature.group 3.23.1500.v20241030-2121 requires 'org.eclipse.equinox.p2.iu; org.eclipse.jdt.core.compiler.batch [3.40.0.v20241030-0335,3.40.0.v20241030-0335]' but it could not be found
[2024-11-01T14:14:12.664Z] [ERROR]   Cannot satisfy dependency: org.eclipse.equinox.sdk.product 4.34.0.qualifier depends on: org.eclipse.equinox.p2.iu; org.eclipse.equinox.sdk.feature.group 0.0.0
```

As a result of these, job https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/BETA_JAVA24/ currently fails, because it does not find the current version of `org.eclipse.jdt.core.compiler.batch` in Y-Builds, resulting in compile errors.

I have no theory why the master version 3.40.0.v20241030-0335 of org.eclipse.jdt.core.compiler.batch cannot be found.

Hopefully, consistently switching to beta branches will sort out some issues?

**Comment by laeubi** [comment]
> As a result of these, job https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/BETA_JAVA24/ currently fails, because it does not find the current version of org.eclipse.jdt.core.compiler.batch in Y-Builds, resulting in compile errors.

Should the jobs not be using a always up-to-date compiled batch-compiler anyways? I even wonder if these BETA branches are good for anything today and not just producing more releng efforts than they solve?

1. As we since a while always use the just-compiled-compiler, integrating work for new java versions might better be directly done on the current stream so we find regressions much faster
2. If even partly support is shipped with milestones already (_maybe giving a warning in the project that it is incomplete_) could even let people try out new features even faster and give earlier feedback
3. Les work required with extra jobs / configurations / update-sites and so on...

**Comment by stephan-herrmann** [comment]
> > As a result of these, job https://ci.eclipse.org/jdt/job/eclipse.jdt.ui-github/job/BETA_JAVA24/ currently fails, because it does not find the current version of org.eclipse.jdt.core.compiler.batch in Y-Builds, resulting in compile errors.
> 
> Should the jobs not be using a always up-to-date compiled batch-compiler anyways?

It's not mainly about the compiler to be invoked, but about compiling against the API of org.eclipse.jdt.core.compiler.batch. In this case jdt.ui referenced a constant from the compiler, but used a dependency in which this constant is not present.

> I even wonder if these BETA branches are good for anything today and not just producing more releng efforts than they solve?

Just take my word that these branches solve a very, very relevant problem, and that no-one has yet come forward with another solution.

**Comment by stephan-herrmann** [comment]
Many thanks for merging, @merks .
With this simple change we have a green Y-build again: https://ci.eclipse.org/releng/job/YPBuilds/job/Y-build-4.34/29 :tada: :champagne:
