### ISSUE TITLE
New & Noteworthy

### ISSUE THREAD

**Issue by elsazac** [eclipse-platform/eclipse.platform.releng.aggregator#2533]

**Comment by elsazac** [comment]
For this release, the new and noteworthy task is set to begin shortly. If there are any additional features or developments to include, please add them to the news repository at your earliest convenience.

**Comment by BeckerWdf** [comment]
What about the removal of PHP in December?
There was a mail about it on the eclipse.org-committers mailing list that says:

> I wanted to remind everyone that PHP support will be removed at the end of December, and a final PHP brownout on eclipse.dev is scheduled for December 4th, 2024.
> 
> Thanks to the work that many of you have put in, only 46% of project websites still have some PHP content. 
> 
> We do have a Hugo based template[1] you can leverage, so please file a ticket[2] if you have questions, and we'll do what we can to help.  You can also chose to use a different tool to generate your project website if you feel it better fits your needs.

Doesn't our [N&N page](https://eclipse.dev/eclipse/news/4.33/platform.php) use PHP?

**Comment by jarthana** [comment]
> Doesn't our [N&N page](https://eclipse.dev/eclipse/news/4.33/platform.php) use PHP?

It sure does. So far, nobody had the time to even decide on putting them on markdown, let along actually doing it. Good new is, the actual content is all static HTML. So, there has to be a stop-gap way to do this. I just don't know what, though.
