### ISSUE TITLE
Re-enable Job Y-build-4.34

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-platform/eclipse.platform.releng.aggregator#2594]
On 2024-11-21_12-18-51 [job Y-build-4.34](https://ci.eclipse.org/releng/job/YPBuilds/job/Y-build-4.34) [was disabled](https://ci.eclipse.org/releng/job/YPBuilds/job/Y-build-4.34/jobConfigHistory/showDiffFiles?timestamp1=2024-11-08_10-00-01&timestamp2=2024-11-21_12-18-51) 

I have no background about who or why, so I can only kindly ask to re-enable this job.

**Comment by akurtakov** [comment]
I see https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2591enabling Y-build 4.35 by @MohananRahul . I am not the expert in anything non I-build but maybe 4.35 should be used now.

**Comment by stephan-herrmann** [comment]
> I see #2591 enabling Y-build 4.35 by @MohananRahul . I am not the expert in anything non I-build but maybe 4.35 should be used now.

This explains, thanks, @akurtakov !

I only wonder if disabling one stream could wait until the next stream builds cleanly? Note, that jdt.core BETA_JAVA24 is only now being updated to 4.34 RC2 (https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3348), not yet to 4.35.

@MohananRahul would it be a big burden for you to keep jdt-dev@eclipse.org informed about such moves?
