### ISSUE TITLE
Send a mail to releng list after docker rebuild

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#260]
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/133#issuecomment-1124549605
I think sending a mail to releng list from a job should be doable? 

@sravanlakkimsetti : could be that automated in the https://ci.eclipse.org/releng/view/Miscellaneous/job/Build-Docker-images/ job?

**Comment by akurtakov** [comment]
Already done by @sravanlakkimsetti  as said in the other issue. Link for completeness https://ci.eclipse.org/releng/job/Build-Docker-images/jobConfigHistory/showDiffFiles?timestamp1=2022-04-28_07-00-57&timestamp2=2022-05-12_01-41-03
