### ISSUE TITLE
Switch Linux tarballs to tar.xz

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.releng.aggregator#2604]
Linux world has been using tar.bz2 as a standard till a few years ago since then tar.xz has been the standard while Eclipse is still shipping ancient tar.gz files which are bigger to download and slower to decompress compared to tar.xz .
This has been long standing idea but it came again after reading that even Firefox is switching (from tar.bz2!) to tar.xz https://blog.nightly.mozilla.org/2024/11/28/announcing-faster-lighter-firefox-downloads-for-linux-with-tar-xz-packaging/

**Comment by akurtakov** [comment]
eclipse-SDK-I20241128-0520-linux-gtk-x86_64.tar.gz recompressed as tar.xz goes from 290 MB to 275 MB  - >5% reduction.

**Comment by HannesWell** [comment]
This will require a lot of changes in build scripts etc. when searching through this repo, without sub-modules I get over 150 hits for `.tar.gz`, but without investigating which one are just doc and which really have to be adapted.

But it might be worth it.

**Comment by merks** [comment]
Yes I also expressed concerns that such a simple improvement would be significantly disruptive. Of course one hates to poo poo improvements but there’s also the “if it ain’t broken, don’t fix it” principle.

**Comment by chirontt** [comment]
FYI: I'm playing around with FreeBSD build, and trying the `.tar.xz` format for it, but the `tycho-p2-director-plugin` doesn't support that format:
```
[INFO] eclipse.platform.releng.tychoeclipsebuilder 4.35.0-SNAPSHOT SUCCESS [  0.008 s]
[INFO] org.eclipse.rt.osgistarterkit.product 4.35.0-SNAPSHOT FAILURE [ 16.598 s]
[INFO] equinox-sdk 4.35.0-SNAPSHOT ........................ SKIPPED
[INFO] eclipse-junit-tests 4.35.0-SNAPSHOT ................ SKIPPED
[INFO] eclipse.platform.repository 4.35.0-SNAPSHOT ........ SKIPPED
[INFO] platform-aggregator 4.35.0-SNAPSHOT ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36:05 min
[INFO] Finished at: 2024-12-01T14:29:29-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-director-plugin:4.0.10:archive-products (archive-products) on project org.eclipse.rt.osgistarterkit.product: Unknown or unsupported archive format os=freebsd format=tar.xz -> [Help 1]
```
The current `.tar.gz` format does work, though. So it seems `tycho-p2-director-plugin` need be updated to support `.tar.xz` format.

**Comment by mickaelistria** [comment]
We could probably start by producing some .tar.xz artifacts, make sure that toolchain (including Tycho) is able to work with those, and then deprecate the .tar.gz with a clear note about there removal in every N&N until then.

**Comment by merks** [comment]
These are just observations, not arguments for or against...

When firefox updates, I am not required to unzip/untar or do anything else to install it.  It just happens even when I'm completely stupid and non-technical.  Reduced network traffic can only be a good thing.

I don't see that Adoptium is taking such a new approach:

![image](https://github.com/user-attachments/assets/acf7e24c-fba7-43a7-bf03-6b4f2df9c8ae)

Apache provides several options though:

![image](https://github.com/user-attachments/assets/ebbabbab-97a5-4f07-9d27-8990c24a773b)

I would be good to know that the Java Libraries, e.g., org.apache.commons.compress, can consume this.  I suppose that's what Tycho would use to produce it...

**Comment by chirontt** [comment]
> The current .tar.gz format does work, though. So it seems `tycho-p2-director-plugin` need be updated to support .tar.xz format.

A quick glance at the `tycho-p2-director-plugin` source code revealing the currently-supported archive formats:
https://github.com/eclipse-tycho/tycho/blob/39dbc4b07b06cd1b86f70184e67023197289f8d1/tycho-p2-director-plugin/src/main/java/org/eclipse/tycho/plugins/p2/director/ProductArchiverMojo.java#L52-L58
![image](https://github.com/user-attachments/assets/5ca0a0d8-a336-4174-9d42-bc2cb2eff420)
So `tar.xz` (and maybe `txz` too) need be added.
