### ISSUE TITLE
The future of the Linux PowerPC 64-bit little-endian port of Eclipse 

### ISSUE THREAD

**Issue by HannesWell** [eclipse-platform/eclipse.platform.releng.aggregator#2605]
## Suggestion

Eclipse SWT and Equinox currently provide native binaries respectively a native launcher for Linux on PowerPC 64-bit little-endian CPUs (`linux.ppc64le`). The Eclipse SDK product is also provided for that os-arch combination, but EPP does not provide packages for it:
https://github.com/eclipse-packaging/packages/blob/3bda445e267b42f5a477c34eeaeffb54a308d4fe/releng/org.eclipse.epp.config/parent/pom.xml#L133-L167

In general I have the impression that there is only a little user-base for `linux.ppc64le`, if there is any. When asking around if anybody is using it or does anybody know that uses it, I have not received any report about a know user so far.

If there are no known users and nobody is interested in helping to maintain `linux.ppc64le`, I suggest to remove support for it.
Dropping it would save use some configurations and the maintenance of the build machine and would reduce the build runtime and storage occupation. At the moment it does not cause problems but they might come in the future and it will require effort, e.g. to make a GTK-4 build of SWT work for it and to test it.

Therefore, if you are using Eclipse on `linux.ppc64le` and want to help keeping Eclipse alive at that platform, please speak up.
To ensure it's working in the future we need developers that can solve potential problems and have the hardware to test changes and solutions.

## Community

- [x] I understand suggesting an enhancement doesn't mandate anyone to implement it. Other contributors may consider this suggestion, or not, at their own convenience. The most efficient way to get it fixed is that I implement it myself and contribute it back as a good quality patch to the project.

**Comment by HannesWell** [comment]
@tjwatson and @gireeshpunathil I asked you a while ago if you know any `linux.ppc64le` user. Have you found any in the meantime?

**Comment by gireeshpunathil** [comment]
I haven't got any response from my consumers since I asked this question 5 weeks ago, so I deem we don't have any.

I agree with the plan to end support for this. thank you!

**Comment by HannesWell** [comment]
> I haven't got any response from my consumers since I asked this question 5 weeks ago, so I deem we don't have any.
> 
Ok, thanks for checking.

If the Eclipse SDK drops support for `linux.ppc64le`, JustJ could also consider to disable/drop it, basically undoing https://github.com/eclipse-justj/justj/issues/12. But that's a decision of JustJ.

About the roadmap if this issue; my proposal is:
If nobody interested in the continuing `linux.ppc64le` and willing to help to do that, speaks up within the next three weeks, i.e. until the 20th December 2024, I intent to stop the publication and building of the corresponding native SWT and Equinox fragments for Eclipse 2025-03 M1. If the silence persists until some time after the 2025-03 release, I plan to fully delete these native fragments and everything related to it and to disconnect the corresponding build machines from the RelEng Jenkins, making the removal permanent.

**Comment by laksono** [comment]
In our project ([HPCToolkit](https://hpctoolkit.org)), we currently use it on power9 systems. We are monitoring forthcoming systems at national labs that might employ power10.
It would be helpful if Eclipse could keep the support for ppc64le.

**Comment by HannesWell** [comment]
> we currently use it on power9 systems. We are monitoring forthcoming systems at national labs that might employ power10.

I assume power10 is also a ppc64le CPU-architecture, isn't it?

> It would be helpful if Eclipse could keep the support for ppc64le.

Are you also interested in contributing/helping to continue that support?

**Comment by laksono** [comment]
> 
> I assume power10 is also a ppc64le CPU-architecture, isn't it?

Yes, it is
> 
> Are you also interested in contributing/helping to continue that support?

I am not sure if I can contribute, but I can try.

**Comment by akurtakov** [comment]
Unless others object I would say let's close this one for now (aka "Till PPC64LE becomes a blocker for smth") and drop it at that point unless community engaged with the project by then to not allow this to happen.

**Comment by HannesWell** [comment]
> Unless others object I would say let's close this one for now (aka "Till PPC64LE becomes a blocker for smth") and drop it at that point unless community engaged with the project by then to not allow this to happen.

Yes.

Btw. @laksono have you tried in the meantime if you can use Eclipse for another CPU arch like x86_64, aarch64 or riscv64 with an emulator on ppc64le, similar like one can use an x86_64 Eclipse with a aarch64 CPU under Windows(11)?

**Comment by laksono** [comment]
@HannesWell, I looked at QEMU. That should work, but I have yet to try it.
