### ISSUE TITLE
I20220518-1100 Unstable!

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#268]
https://download.eclipse.org/eclipse/downloads/drops4/I20220518-1100/

Comparator errors, probably after rebuilding javadocs via https://github.com/eclipse-platform/eclipse.platform.common/commit/d9507d1c335db6df366144f5928c59d26ecef016

There are few .gitignore files found in 
https://download.eclipse.org/eclipse/downloads/drops4/I20220518-1100/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

Example:
 ```
1.  eclipse.jdt.ui/org.eclipse.jdt.ui.tests
   no-classifier: different
      org/eclipse/jdt/ui/tests/chkpii/.gitignore: not present in baseline
      testresources/JUnitWorkspace/.gitignore: not present in baseline
      testresources/JUnitWorkspace/JUnit4Tests/.gitignore: not present in baseline
      testresources/JUnitWorkspace/JUnitTests/.gitignore: not present in baseline
```

**Comment by sravanlakkimsetti** [comment]
raised https://github.com/eclipse/tycho/issues/966 for this

**Comment by akurtakov** [comment]
Once https://ci.eclipse.org/tycho/job/tycho-github/job/master/391/console completes new Platform build can be started (I'll do it).

**Comment by akurtakov** [comment]
New build triggered

**Comment by akurtakov** [comment]
Now I'm really puzzled. Most comparator errors are gone but there are still 2 https://download.eclipse.org/eclipse/downloads/drops4/I20220519-0130/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt , weirdly enough there is no .gitignore https://github.com/eclipse-platform/eclipse.platform.ui/tree/master/tests/org.eclipse.ui.tests

**Comment by iloveeclipse** [comment]
Was .gitignore shipped *by mistake*?

**Comment by akurtakov** [comment]
Nope, it's in the just produced jar and seems to come from https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/tests/org.eclipse.ui.tests/Eclipse%20UI%20Tests/.gitignore .

**Comment by akurtakov** [comment]
Marked https://download.eclipse.org/eclipse/downloads/drops4/I20220519-0130/ as stable as the comparator issues are in test bundles that are not contributed to simrel so we can proceed with M3 signoff
Further investigation where this changes comes from in Tycho and why org.eclipse.ui.tests have such file will continue.

**Comment by sravanlakkimsetti** [comment]
Still a problem

Comparator differences from current build
	/home/jenkins/agent/workspace/I-build-4.24/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/siteDir/eclipse/downloads/drops4/I20220520-0600
compared to reference repo at 
	https://download.eclipse.org/eclipse/updates/4.24-I-builds

1.  eclipse.jdt.ui/org.eclipse.jdt.ui.tests
   no-classifier: different
      org/eclipse/jdt/ui/tests/chkpii/.gitignore: not present in baseline
   classifier-sources: not present in baseline
    The main artifact has been replaced with the baseline version.
    The following attached artifacts are not present in the baseline and have been removed: [sources]

**Comment by akurtakov** [comment]
@mickaelistria @laeubi can you notice anything special in o.e.jdt.ui.tests that makes it handled differently?
