### ISSUE TITLE
Declare 4.24 M3

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#269]
Declare 4.24 M3

A "go" is needed from all the components below to declare this milestone.

Current Candidate

Eclipse downloads:
https://download.eclipse.org/eclipse/downloads/drops4/I20220519-0130

Build logs and/or test results (eventually):
https://download.eclipse.org/eclipse/downloads/drops4/I20220519-0130/testResults.php

Software site repository:
https://download.eclipse.org/eclipse/updates/4.24-I-builds

Specific (simple) site repository:
https://download.eclipse.org/eclipse/updates/4.24-I-builds/I20220519-0130

Equinox downloads:
https://download.eclipse.org/equinox/drops/I20220519-0130

---
Deadlines: 
- Friday, 2022-May-19, around 1 AM (Eastern): deadline for sign-off (or, by then, comment in this issue when you expect to sign-off).
- Friday, 2022-May-19, around 3 AM (Eastern): promote approved build to S-4.24M3-*, contribute to simultaneous release repo, and announce to mailing lists.

Remember to investigate and document here any failing JUnit tests. 

---

- [x] Platform:
- - [x] Resources
- - [x] UI
- - [x] Debug
- - [x] Ant
- - [x] SWT
- - [x] Releng

- [x] JDT:
- - [x] Core
- - [x] Debug
- - [x] UI

- [x] PDE
- [x] Equinox

**Comment by sravanlakkimsetti** [comment]
Go from platform releng. The single failure is due to comparator error in test bundles. This is being tracked in [I20220518-1100 Unstable!](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/268) . This does not affect the quality of the build

**Comment by niraj-modi** [comment]
Go from SWT.
Failing JUnits are tracked by:
- https://github.com/eclipse-platform/eclipse.platform.swt/issues/108

**Comment by SarikaSinha** [comment]
Go from Platform Ant, Debug and JDT Debug

Failing JDT debug tests are tracked by
- https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/28
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=488350

**Comment by sptaszkiewicz** [comment]
Go from Platform Resources.

**Comment by jarthana** [comment]
Go from JDT Core. The 4 failures are known issues tracked by bug 565083 and company.

**Comment by ktatavarthi** [comment]
Go from JDT UI. 

The 1 test failure on Windows is captured by the bug
- [Bug 572555](https://bugs.eclipse.org/bugs/show_bug.cgi?id=572555) - Avoid random failures of SaveParticipantTest

**Comment by ktatavarthi** [comment]
Go from Platform UI 

Test failures on Mac and Windows are captured by
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/81

Test failures on Mac only are captured by
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/80

Test failures on Windows only are captured by
- [Bug 521111](https://bugs.eclipse.org/bugs/show_bug.cgi?id=521111) - SyncExecWhileUIThreadWaitsForLock.testDeadlock fails on Windows
- [Bug 571317](https://bugs.eclipse.org/bugs/show_bug.cgi?id=571317) - No code mining updated when using Ctrl+End (was: CodeMiningTest are failing on Windows and Mac)
- [Bug 571316](https://bugs.eclipse.org/bugs/show_bug.cgi?id=571316) - JUnit tests in org.eclipse.jface.text.tests.contentassist are failing on Windows and Mac

**Comment by sravanlakkimsetti** [comment]
Build promoted, contributed to simrel, made visible and sent note to mailing lists
