### ISSUE TITLE
Y Build Failing from 24 Dec 2024

### ISSUE THREAD

**Issue by mpalat** [eclipse-platform/eclipse.platform.releng.aggregator#2710]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)
The above point is irrelevant - the issue with Y build not completing - ref:https://ci.eclipse.org/releng/job/YPBuilds/job/Y-build-4.35/37/console

## Steps to reproduce

see https://ci.eclipse.org/releng/job/YPBuilds/job/Y-build-4.35/37/console

## Here is some relevant log output
From the console output:

20:41:28  [ERROR] Cannot resolve dependencies of project org.eclipse.pde:org.eclipse.pde.ui.tests:eclipse-test-plugin:3.13.0-SNAPSHOT
20:41:28  [ERROR]  with context {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, org.eclipse.jdt.buildtime=true, osgi.arch=x86_64, org.eclipse.update.install.sources=true}
20:41:28  [ERROR]   Software being installed: org.eclipse.pde.feature.group 3.16.200.v20241229-1130
20:41:28  [ERROR]   Missing requirement: org.eclipse.pde.feature.group 3.16.200.v20241229-1130 requires 'org.eclipse.equinox.p2.iu; org.eclipse.pde [3.13.3000.v20241229-0630,3.13.3000.v20241229-0630]' but it could not be found: See log for details
20:41:28  [ERROR] -> [Help 1]
20:41:28  org.apache.maven.lifecycle.LifecycleExecutionException: Cannot resolve dependencies of project org.eclipse.pde:org.eclipse.pde.ui.tests:eclipse-test-plugin:3.13.0-SNAPSHOT

## Tested under this environment:
* OS & version: ...
* Eclipse IDE/Platform version (as shown in *Help > About*): ...
* ...Anything else that can be useful...

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by HannesWell** [comment]
The latest Y-build succeeded: https://ci.eclipse.org/releng/job/YPBuilds/job/Y-build-4.35/
But I haven't changed anything, at least not consciously. So I assume the problem described above still persists.

Btw. I have also fixed the Y-build test result collection task via:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2714

It was broken by my recent clean-ups/unifications.

**Comment by mpalat** [comment]
Thanks @HannesWell for the comments and for taking an immediate look. @SougandhS pointed me to [your earlier comment in another issue](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2658#issuecomment-2560164626) as well. Will merge master to Beta soon.
