### ISSUE TITLE
Add new test runs with Java 18 in Smoke tests

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#28]
Currently we are running smoke tests with Java 11 and Java 17. Need to run these with Java 18 as well

**Comment by jonahgraham** [comment]
Comment has Java 18 twice - was it supposed to read?

Currently we are running smoke tests with Java 11 and Java **17**. Need to run these with Java 18 as well

**Comment by sravanlakkimsetti** [comment]
Added Java 18 and Java 19 tests as part of #156
