### ISSUE TITLE
Update centos 8 docker files to use redhat base image 8

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#29]
Support for centos has been dropped by Dec 31, 2021. Need to migrate these to use redhat base image version 8.

Code is available here 

1. https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/cje-production/dockerfiles/centos-gtk3-metacity/8-gtk3
2. https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/cje-production/dockerfiles/centos-gtk3-metacity/8-swtBuild

**Comment by SDawley** [comment]
I created a PR for this that updates to ubi 8.5-226. I included registry.access.redhat.com because when I tested locally it defaulted to registry.redhat.io which needs a login. 

Also @sravanlakkimsetti since this is now UBI not CentOS should I rename the build and push scripts?
