### ISSUE TITLE
Eclipse namespace

### ISSUE THREAD

**Issue by wimjongman** [eclipse-platform/eclipse.platform.releng.aggregator#3]
Why are we not in the github.com/eclipse namespace like all other projects?

**Comment by mickaelistria** [comment]
Because we plan to have multiple repositories in here and this use GitHub teams (which are mapped by organization) for better permission control.

**Comment by akurtakov** [comment]
It's not all projects. There is https://github.com/eclipse-m2e/ and https://github.com/eclipse-linuxtools/ and etc. In general projects having more than one repo would better have their own organization as this makes keeping track of things easier.

**Comment by wimjongman** [comment]
That makes sense. Thanks for working on this. Please send some work my way if you need help with the transition.

**Comment by akurtakov** [comment]
Well, most valuable work is to review gerrits. We can't move a repository as long as there are many open gerrits against it.

**Comment by laeubi** [comment]
> Well, most valuable work is to review gerrits. We can't move a repository as long as there are many open gerrits against it.

Why not? If they are of value thanks to `git` we can convert them to PRs if desired, you just need to push your branch (there is a commandline in each gerrit to create one) to your github fork and your all set.

**Comment by wimjongman** [comment]
> Well, most valuable work is to review gerrits. We can't move a repository as long as there are many open gerrits against it.

Do you think we can ever win that battle?

**Comment by akurtakov** [comment]
> > Well, most valuable work is to review gerrits. We can't move a repository as long as there are many open gerrits against it.
> 
> Why not? If they are of value thanks to `git` we can convert them to PRs if desired, you just need to push your branch (there is a commandline in each gerrit to create one) to your github fork and your all set.

We have hundreds of gerrits. Many of them just staying because no committer found time to look at them. Asking people to move their unlooked patch to another place will just piss them off. Look bellow for kind of a plan.



> > Well, most valuable work is to review gerrits. We can't move a repository as long as there are many open gerrits against it.
> 
> Do you think we can ever win that battle?

If we look at it as one battle - NO . But we can look at it as many battles and try to win them one by one - concentrate on one repo till we get gerrits against it to some "acceptable" number and "quality" for conversion to github PRs. 
Flooding the new system with ancient PRs is a total no-go, just asking people to move even if it's simple, easy-to-merge and etc. patch is bad community gardening. So we have to go repo by repo with the move and cleanup the mess that accumulated over the years.
If that means it prolongs for some period so be it. I would rather see it done proper and with minimum damages than rushed.

**Comment by akurtakov** [comment]
E.g.
https://git.eclipse.org/r/q/project:platform/eclipse.platform.common+status:open
https://git.eclipse.org/r/q/project:platform/eclipse.platform.resources+status:open
https://git.eclipse.org/r/q/project:platform/eclipse.platform.text+status:open
https://git.eclipse.org/r/q/project:platform/eclipse.platform.runtime+status:open

are all with manageable amount of gerrits if people decide to jump in for reviewing.

**Comment by laeubi** [comment]
> We have hundreds of gerrits. Many of them just staying because no committer found time to look at them.

Then they seem of no great value, aynways they can be merged in the old git and then push that hcange to the new git remote as well.

> Asking people to move their unlooked patch to another place will just piss them off.

Or make them happy the dont need to use gerrit anymore ;-)

> I would rather see it done proper and with minimum damages than rushed.

Maybe it would make sense then not accepting any new features unless all gerrits are done and only bug-fixes for the 2022-06?

**Comment by akurtakov** [comment]
> Maybe it would make sense then not accepting any new features unless all gerrits are done and only bug-fixes for the 2022-06?

This would be the release adding support for Java 18 so can't happen :). Same for other low level enablements for latest Mac/Win/Linux.

**Comment by laeubi** [comment]
> This would be the release adding support for Java 18 so can't happen :).

I won't mind ... :-) Only adding new features dosen't help much ...

> Same for other low level enablements for latest Mac/Win/Linux.

I won't mind waiting for them one more release... ;-)
