### ISSUE TITLE
Declare 4.24 RC2a

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#323]
Declare 4.24 RC2a

A "go" is needed from all the components below to declare this milestone.

Current Candidate

Eclipse downloads:
https://download.eclipse.org/eclipse/downloads/drops4/I20220607-0700

Build logs and/or test results (eventually):
https://download.eclipse.org/eclipse/downloads/drops4/I20220607-0700/testResults.php

Software site repository:
https://download.eclipse.org/eclipse/updates/4.24-I-builds

Specific (simple) site repository:
https://download.eclipse.org/eclipse/updates/4.24-I-builds/I20220607-0700

Equinox downloads:
https://download.eclipse.org/equinox/drops/I20220607-0700

---
Deadlines:
- Friday, 2022-June-8, around 7 AM (Eastern): deadline for sign-off (or, by then, comment in this issue when you expect to sign-off).
-  Friday, 2022-June-8, around 10 AM (Eastern): promote approved build to S-4.24RC2a-*, contribute to simultaneous release repo, and announce to mailing lists.

Remember to investigate and document here any failing JUnit tests.
---
- [ ] Platform:
- - [ ] Resources
- - [ ] UI
- - [ ] Debug
- - [ ] Ant
- - [ ] SWT
- - [x] Releng
- [ ] JDT:
- - [ ] Core
- - [ ] Debug
- - [ ] UI
- [ ] PDE
- [ ] Equinox

**Comment by sravanlakkimsetti** [comment]
Go from platform releng.

**Comment by SDawley** [comment]
Closing as RC2a is available
