### ISSUE TITLE
Keep at least 2 stable repositories in I-build composite

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#358]
Currently we are keeping 4 stable repositories in I-build composite. At the same time if we have an unstable build, that is also being counted towards builds present in composite and accordingly the composite site is getting trimmed.

if we have 4 successive unstable builds, the cleaning scripts looks for all the builds in the I-builds folder and leave latest 4 builds. This results in leaving latest 4 unstable builds. 

Since we don't add unstable builds to composite, we end up a composite with no builds.

The changes to be done here are:
1. Update cleanup script to ignore unstable builds
2. Reduce the number of builds to 2

Notifications: @akurtakov

**Comment by akurtakov** [comment]
That would be more than welcome as having 4 I-builds make install/update/verification builds keep resolving from old build and potential breakage is noticed days after its merged.

**Comment by mickaelistria** [comment]
+1, I see only benefits here.

**Comment by merks** [comment]
+1  These URLs is widely used and there is an undesirable cost to downloading each child location's metadata (or even just checking its last modified).
