### ISSUE TITLE
Create docker images to centos stream 9 for gtk4 availability

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.releng.aggregator#36]
Needed in order to start building gtk4 bindings for swt.

**Comment by sravanQonway** [comment]
Please create a new image for this one.

**Comment by sravanlakkimsetti** [comment]
Let's create new image for this one

**Comment by akurtakov** [comment]
@SDawley would you please take care of this one?

**Comment by SDawley** [comment]
OK

**Comment by sravanlakkimsetti** [comment]
Require push scripts as well.

**Comment by SDawley** [comment]
I updated the job and kicked off a [build](https://ci.eclipse.org/releng/view/Miscellaneous/job/Build-Docker-images/320/console) to verify everything works like it did locally but its been waiting for a runner.

**Comment by akurtakov** [comment]
Next step is waiting on EF https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1019

**Comment by sravanlakkimsetti** [comment]
I think this done. Any thing else pending?
