### ISSUE TITLE
Missing org.hamcrest 2.x in repository

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-platform/eclipse.platform.releng.aggregator#365]
AssertJ requires hamcrest 2.x. While this one is correctly resolved during build, it seems to be missing from the resulting p2 repo.

**Comment by merks** [comment]
It was like this:

![image](https://user-images.githubusercontent.com/208716/176255418-ab3755eb-3824-4fe9-9e69-c28952cc6c2f.png)

So perhaps now it's not included in any feature that's included in the category.xml.

**Comment by mickaelistria** [comment]
Right, but the pom.xml has `<includeAllDependencies>true</includeAllDependencies>` so there is either another bug or another misconfiguration playing here.

**Comment by merks** [comment]
Is the plugin name different?  I don't see this new version in the *.target.

**Comment by mickaelistria** [comment]
I'm wrong `org.eclipse.sdk.tests` is listed in category.xml so the deps should be included. Maybe it's a bug in Tycho...

**Comment by merks** [comment]
I don't see the new version here though:

![image](https://user-images.githubusercontent.com/208716/176261787-f1b9142e-2acb-48eb-85a0-19c355fcd673.png)

**Comment by mickaelistria** [comment]
It's included transtively from https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target#L294

**Comment by mickaelistria** [comment]
OK thanks. I verified and it looks like assertj has an *optional* Import-Package requirement against org.hamcrest 2.0 packages. So it is fine that hamcrest is not part of the p2 repo. The issue is more that my build (or Tycho) is reporting this missing requirement as an error.
