### ISSUE TITLE
Out-the-box build failure/run failure

### ISSUE THREAD

**Issue by mablinov** [eclipse-platform/eclipse.platform.releng.aggregator#379]
Hi all, first time playing with Eclipse SDK. I am on Windows 10.

# Versions:

```
$ java -version
java version "1.8.0_331"
Java(TM) SE Runtime Environment (build 1.8.0_331-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.331-b09, mixed mode)
```
```
$ mvn --version
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: C:\Users\Maxim\Documents\opt\apache-maven-3.8.6
Java version: 13, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-13
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

# Issue

I followed the instructions on the front page, and after invoking `mvn clean verify -DskipTests=true` I got the following build failure:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:11 h
[INFO] Finished at: 2022-07-02T18:39:28+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.1.0:run (copy-launcher-natives) on project org.eclipse.equinox.launcher.cocoa.macosx: An Ant BuildException has occured: C:\Users\Maxim\prj\eclipse-sdk\rt.equinox.binaries\org.eclipse.equinox.launcher.cocoa.macosx is not a directory.
[ERROR] around Ant part ...<copy todir="C:\Users\Maxim\prj\eclipse-sdk\equinox\bundles\org.eclipse.equinox.launcher.cocoa.macosx\target" overwrite="true">... @ 4:132 in C:\Users\Maxim\prj\eclipse-sdk\equinox\bundles\org.eclipse.equinox.launcher.cocoa.macosx\target\antrun\build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :org.eclipse.equinox.launcher.cocoa.macosx
```

I did however have an `eclipse.exe` generated in (what I presume is) the build folder:
```
$ find . -type f | egrep 'eclipse\.exe'
./eclipse.pde/build/org.eclipse.pde.build.tests/resources/264743/build1/features/ee/bin/win32/win32/x86/eclipse.exe
./equinox/features/org.eclipse.equinox.executable.feature/library/win32/eclipse.exe.manifest
./rt.equinox.binaries/org.eclipse.equinox.executable/bin/win32/win32/x86_64/eclipse.exe
./rt.equinox.p2/bundles/org.eclipse.equinox.p2.tests/testData/EquinoxExecutableActionTest/win/eclipse.exe
```

However, when I tried to run them, all of them exited out with an error dialog stating that `The Eclipse executable launcher was unable to locate its companion shared library`.

I figured that perhaps I needed to run an 'install' step of some kind, so I invoked `$ mvn install -DskipTests=true`. After some time it encountered the same error as the `$ mvn clean verify ...` step, and it did not appear or add any new `eclipse.exe`'s into my directory tree.

**Comment by mickaelistria** [comment]
Can you please elaborate on what particularly you're trying to achive? You may not need to do a full build (which is more complex, more resource and time consuming).

**Comment by mablinov** [comment]
> Can you please elaborate on what particularly you're trying to achive? You may not need to do a full build (which is more complex, more resource and time consuming).

Just curiousity to be honest.

**Comment by akurtakov** [comment]
As a minimum you have to use Java 11 for working on Eclipse nowadays. Additionally, most people doing releng work run build scripts on Linux machines so doing full build on Windows is not well tested at least.
I'm closing this one as it's unclear how to help you further. If you have exact issue trying to solve we can continue though.
