### ISSUE TITLE
com.ibm.icu seem to be missing since I20220701-1800 in various tests

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#381]
[This](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/367) most likely caused test fails like https://github.com/eclipse-platform/eclipse.platform/issues/40 and also javadoc build failures.

See https://download.eclipse.org/eclipse/downloads/drops4/I20220703-0600/compilelogs/platform.doc.isv.javadoc.txt
```
../../../eclipse.platform.ui/bundles/org.eclipse.core.databinding/src/org/eclipse/core/databinding/conversion/NumberToStringConverter.java:24: error: package com.ibm.icu.text does not exist
import com.ibm.icu.text.NumberFormat;
```

**Comment by iloveeclipse** [comment]
@mickaelistria : please take a look at this one.

**Comment by mickaelistria** [comment]
https://github.com/eclipse-platform/eclipse.platform.common/pull/45 is supposed to fix javadoc generation.
The overall cause is that some plugins expect Maven artifactId, some others the Bundle-SymbolicName. It's not a big deal to adjust those when necessary, however, it questions whether the maven-dependency-plugin is usually a best choice as it introduces artifactIds, or whether it would be worth switching to tycho-dependency-plugin or even p2 director to get the dependencies in their more usual p2 form. Time will tell...

**Comment by iloveeclipse** [comment]
> [eclipse-platform/eclipse.platform.common#45](https://github.com/eclipse-platform/eclipse.platform.common/pull/45) is supposed to fix javadoc generation.

There are more failures now.
https://download.eclipse.org/eclipse/downloads/drops4/I20220703-0600/compilelogs/jdt.doc.isv.javadoc.txt
```
../../../eclipse.jdt.ui/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaEditor.java:31: error: package com.ibm.icu.text does not exist
import com.ibm.icu.text.BreakIterator;
                       ^
```

https://download.eclipse.org/eclipse/downloads/drops4/I20220703-0600/compilelogs/pde.doc.user.javadoc.txt
```
javadoc: error - Error reading file: ../org.eclipse.platform.doc.isv/reference/api/element-list
javadoc: error - Error reading file: ../org.eclipse.jdt.doc.isv/reference/api/element-list
2 errors
```


https://download.eclipse.org/eclipse/downloads/drops4/I20220703-0600/compilelogs/platform.doc.isv.javadoc.txt
```
../../../eclipse.platform.ui/bundles/org.eclipse.core.databinding/src/org/eclipse/core/databinding/conversion/NumberToStringConverter.java:24: error: package com.ibm.icu.text does not exist
import com.ibm.icu.text.NumberFormat;
```

**Comment by mickaelistria** [comment]
Next attempt: https://github.com/eclipse-platform/eclipse.platform.common/pull/47

**Comment by mickaelistria** [comment]
This is a very error-prone setup which takes ages to test locally, and I'm trying to fix the issue but am making a lot of errors. The root issue is that com.ibm.icu/icu4j is currently not visible to javadoc classpath because it now uses a 2 segment version while the ant scripts expect a 3 or 4 segment version... Trying to fix the regex is taking me lot of trial and error as it's easy to overlook 1 detail, 1 path which would suddently be different.

**Comment by vogella** [comment]
FYI com.ibm.icu is also planned to be removed from platfrom once we were able to replace its API usage. @akurtakov started that work but IIRC he ran out of time finishing the removal of usage of this library.

**Comment by mickaelistria** [comment]
This seems good now. New I-Build doesn't report issue with javadoc generation.
