### ISSUE TITLE
Fully replace Orbit's JUnit 5 by upstream Maven one

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-platform/eclipse.platform.releng.aggregator#389]
In order to simplify consumption of upstream libs and publication to Maven, we prefer using upstream Maven bundles in favor of Orbit's ones. Currently both Orbit's and Maven's JUnit 5 artifacts are in the .target file. We should remove Orbit's variant as soon as possible. This require to update some code in JDT and PDE to allow working with different artifacts.

- [x] https://github.com/eclipse-platform/eclipse.platform.releng/pull/68
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/pull/192
- [x] https://github.com/eclipse-jdt/eclipse.jdt/pull/25
Need immediate fix:
- [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/204
Next steps:
- [x] https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/138
- [x] https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/139
- [x] https://github.com/eclipse-pde/eclipse.pde/pull/199
Then when all plugins are supposed to work with junit- (Maven Central) bundles, 
- [x] https://github.com/eclipse-jdt/eclipse.jdt/pull/27
Other fixes
- [x] https://github.com/eclipse-jdt/eclipse.jdt/pull/28
- [x] https://github.com/eclipse-platform/eclipse.platform/pull/46
- [ ] https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/402

**Comment by iloveeclipse** [comment]
@mickaelistria: could you please check if #409 caused by the changes here?
