### ISSUE TITLE
org.apache.jasper.glassfish and com.sun.el versions have gone backwards

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-platform/eclipse.platform.releng.aggregator#438]
IMHO this is a bad idea - this maven artifact is actually from Orbit, and indeed from a much older version of Orbit which means that it has old (and now out of date) signatures. For this bundle (and the `com.sun.el` one too) the version number has gone backwards too.

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/9f0ce1bf6efe5ed8af3cd8ac18e035da7b4c0630/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target#L254-L255

The initial change to this was done in PR #367 - prior to that this was the version info:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/0d26ffecc9c54f81eb38255396cdb1631c5c3f67/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target#L140-L141

**Comment by merks** [comment]
It's a bad idea that all users will notice when they install or update to these things because this dialog will come up:

![image](https://user-images.githubusercontent.com/208716/184545860-d5411fdb-1009-4155-bfe0-06100782ef2f.png)

Note the trust-inspiring expired indication suggesting that some thing is really quite wrong and questionable.

**Comment by merks** [comment]
@jonahgraham I'm not sure that both have gone backwards.

I see this in the history when previously pulled from Orbit:

```
      <unit id="com.sun.el" version="2.2.0.v201303151357"/>
      <unit id="com.sun.el.source" version="2.2.0.v201303151357"/>

      <unit id="org.apache.jasper.glassfish" version="2.2.2.v201501141630"/>
      <unit id="org.apache.jasper.glassfish.source" version="2.2.2.v201501141630"/>
```

and this now when pulled from Maven:

```
			  <dependency>
				  <groupId>org.eclipse.jetty.orbit</groupId>
				  <artifactId>com.sun.el</artifactId>
				  <version>2.2.0.v201303151357</version>
				  <type>jar</type>
			  </dependency>
			  <dependency>
				  <groupId>org.eclipse.jetty.orbit</groupId>
				  <artifactId>org.apache.jasper.glassfish</artifactId>
				  <version>2.2.2.v201112011158</version>
				  <type>jar</type>
			  </dependency>
```
So glassfish is clearly an older version now, but these look the same:

- https://download.eclipse.org/oomph/archive/reports/download.eclipse.org/releases/2022-06/202206151000/index/com.sun.el_2.2.0.v201303151357.html
- https://download.eclipse.org/oomph/archive/reports/download.eclipse.org/releases/2022-06/202206151000/index/com.sun.el_2.2.0.v201303151357.html

Though it also has very old certificate signature and also results in a prompt.

I don't think a newer version of com.sun.el exists:

![image](https://user-images.githubusercontent.com/208716/184587753-8e25d67c-8e1a-4c05-8909-c7865c368a6f.png)

**Comment by jonahgraham** [comment]
I think you are correct that el hasn't gone backwards by version number, but it has gone backwards by contents. This is because Orbit resigned lots of bundles without changing their qualifier in the past. Which means that they have identical contents, but the jar is different due to different signatures. AFAICT the signature of the el bundle in the last release was OK because it came from a resigned Orbit repo. See [Bug 553288 Comment 2](https://bugs.eclipse.org/bugs/show_bug.cgi?id=553288#c2)

**Comment by merks** [comment]
@jonahgraham 

So if we reverted these changes (whose only purpose is to eliminate mapping rules from the *.aggr) the problem I'm seeing would likely go away, right?

@akurtakov 

I'll do the work for this, if we can avoid this degrading into a very long discussion.  Okay?

**Comment by jonahgraham** [comment]
> @jonahgraham
> 
> So if we reverted these changes (whose only purpose is to eliminate mapping rules from the *.aggr) the problem I'm seeing would likely go away, right?

I think so - i.e. if these bundles are pulled from the this repo https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/1ba1ece5cfc28b9ade0389aa2ca6924bbb63deda/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target#L86-L90 we should be good to go.

(Sorry, I didn't understand the mapping rules part of your comment.)

**Comment by jonahgraham** [comment]
Thanks for the extra info - I had mistakenly assumed the simrel .aggr file.

**Comment by akurtakov** [comment]
> 
> @akurtakov
> 
> I'll do the work for this, if we can avoid this degrading into a very long discussion. Okay?

Go on with this one . I dislike long discussions and it's more than clear that the move to maven and shipping uptodate deps will not happen over night and there will be steps back needed.

**Comment by merks** [comment]
@jonahgraham 

Even with the changes from the PR, I still get this prompt:

![image](https://user-images.githubusercontent.com/208716/184807970-299da4b7-0256-4f6f-a148-17abdd9f262d.png)

Looking at that bundle in the previous release

https://download.eclipse.org/oomph/archive/reports/download.eclipse.org/eclipse/updates/4.24/R-4.24-202206070700/index/com.sun.el_2.2.0.v201303151357.html

And the current one:

https://download.eclipse.org/oomph/archive/reports/download.eclipse.org/eclipse/updates/4.25-I-builds/https___download.eclipse.org_eclipse_updates_4.25-I-builds_I20220815-1800/com.sun.el_2.2.0.v201303151357.html

They both have this same very old root certificate:

![image](https://user-images.githubusercontent.com/208716/184808915-a6364efc-c0ae-4be8-834d-94ff325d3b8f.png)

This problem will not go away without a new version signed with a newer certificate, except if there is also a PGP signature as supported by this recent change:

https://github.com/eclipse-equinox/p2/issues/121

That would at least help with the installer...

BTW, the report shows quite a few versions going backwards:

https://download.eclipse.org/eclipse/downloads/drops4/I20220815-1800/buildlogs/reporeports/reports/versionChecks.html

![image](https://user-images.githubusercontent.com/208716/184808309-17c1941f-5957-4152-b353-ffaaa2ee4c6b.png)

**Comment by akurtakov** [comment]
Let's not touch these as they don't cause issues AFAICT.

**Comment by merks** [comment]
Yes, I'm not suggesting must revisit these yet again.  But in hindsight, we'd probably have been better to switch to a Maven version when a newer Maven version became available rather than all these backwards moving versions...

**Comment by akurtakov** [comment]
Ideally, our build scripts should be enhanced so such builds are not published to the composite repo much like what happens when there are comparator errors. But this is yet another fight too low in the list.

**Comment by akurtakov** [comment]
I consider this one in decent enough state to close it.
