### ISSUE TITLE
Update JUnit to 5.9.0

### ISSUE THREAD

**Issue by jjohnstn** [eclipse-platform/eclipse.platform.releng.aggregator#442]
Latest JUnit is 5.9.0 and Eclipse is using 5.8.1.

**Comment by cdietrich** [comment]
see also https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/449

**Comment by akurtakov** [comment]
@jjohnstn Is this one ready to be pushed?

**Comment by jjohnstn** [comment]
No, because org.eclipse.test has hard-coded 5.8.1 as a pre-req and needs to be changed first.
