### ISSUE TITLE
deploy-eclipse-platform-parent-pom job fails since 04.08

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#446]
See https://ci.eclipse.org/releng/job/deploy-eclipse-platform-parent-pom/

Fails since jenkins upgrade
https://ci.eclipse.org/releng/job/deploy-eclipse-platform-parent-pom/18742/

Last success
https://ci.eclipse.org/releng/job/deploy-eclipse-platform-parent-pom/18686/

Error:
```
Building remotely on [centos-8-jgqnp](https://ci.eclipse.org/releng/computer/centos-8-jgqnp) (centos-8 centos-latest) in workspace /home/jenkins/agent/workspace/deploy-eclipse-platform-parent-pom
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
The recommended git tool is: git
java.lang.UnsupportedClassVersionError: com/trilead/ssh2/ServerHostKeyVerifier has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:635)
	at hudson.remoting.RemoteClassLoader.loadClassFile(RemoteClassLoader.java:458)
Caused: java.lang.UnsupportedClassVersionError: Failed to load com.trilead.ssh2.ServerHostKeyVerifier
	at hudson.remoting.RemoteClassLoader.loadClassFile(RemoteClassLoader.java:460)
	at hudson.remoting.RemoteClassLoader.loadRemoteClass(RemoteClassLoader.java:300)
	at hudson.remoting.RemoteClassLoader.loadWithMultiClassLoader(RemoteClassLoader.java:269)
	at hudson.remoting.RemoteClassLoader.findClass(RemoteClassLoader.java:228)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:635)
	at hudson.remoting.RemoteClassLoader.loadClassFile(RemoteClassLoader.java:458)
```

Probably same fix needed like in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/437

**Comment by iloveeclipse** [comment]
https://ci.eclipse.org/releng/job/deploy-eclipse-platform-parent-pom/configure
configured to use `centos-latest` thing, whatever it is.
The jenkins doesn't know `centos-8-jdk11` as it was used in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/437/files#diff-0bec543ce69cc80bfea7c450140e3f1391d599d0f224491178565d2cb773dc41R17

**Comment by iloveeclipse** [comment]
@fredg02 : any idea how to configure this job?

**Comment by sravanlakkimsetti** [comment]
hmm some thing wrong with the centos image we are using. I am switching to basic image now. For this job we basic image would suffice.

**Comment by iloveeclipse** [comment]
Sravan, just for my understanding : does SDK build needs this job, or is this only for some 3rd party maven builds? I've read the job description but I've failed to understand who would need this parent pom...

**Comment by sravanlakkimsetti** [comment]
> Sravan, just for my understanding : does SDK build needs this job, or is this only for some 3rd party maven builds? I've read the job description but I've failed to understand who would need this parent pom...

This job deploys eclipse-parent-pom to repo.eclipse.org for use with build-individual-bundles profile. Basically all PR validation jobs require this.

SDK build doesnot need this as the pom is already available in the source.

**Comment by fredg02** [comment]
> https://ci.eclipse.org/releng/job/deploy-eclipse-platform-parent-pom/configure
> configured to use centos-latest thing, whatever it is.

`centos-latest` is a label/alias for the `centos-8` image

> The jenkins doesn't know centos-8-jdk11

That's correct. During the next Jenkins LTS upgrade (scheduled for next week), the `centos-8` image will be adapted to use JDK11 by default and the `centos-8-jdk11` image will become obsolete.
