### ISSUE TITLE
Enhance basicPerformance to show aggregated data

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.releng.aggregator#470]
When I look at page like https://download.eclipse.org/eclipse/downloads/drops4/I20220811-0140/performance/basicPerformance.php?name=org.eclipse.ui&build=I20220811-0140&baseline=R-4.24-202206070700 I see some speedups and some delays but I can't easily get an overall idea how things changed.
It would be nice if there is a line bottom/top-most one that aggregates all the times .
Bonus points if there is such aggregated data for each of the testclasses e.g. org.eclipse.ui.tests.performance.PerspectiveSwitchTest  - but I can understand how this can become cumbersome so if you find it that way - please ignore.

**Comment by SDawley** [comment]
If eclipse-platform/eclipse.platform.releng#86 is merged I'll have to rebuild and deploy build tools, then check the next performance results/

**Comment by akurtakov** [comment]
Mentioned patch is merged so please take the next steps.

**Comment by SDawley** [comment]
Will do.

**Comment by akurtakov** [comment]
Current state is good enough for me.
