### ISSUE TITLE
Revert ICU4J version bump to 71.1 for 4.25

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#476]
As commented on https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/439, the 71.1 ICU4J version is binary incompatible to the previously used 67.1.

This is coming from https://htmlpreview.github.io/?https://github.com/unicode-org/icu/blob/maint/maint-70/icu4j/APIChangeReport.html

```
Removed from ICU4J 69.1

Package com.ibm.icu.lang
UCharacter
(stable) public static boolean isHighSurrogate(char)
(stable) public static boolean isLowSurrogate(char)
(stable) public static final boolean isSurrogatePair(char, char)
(stable) public static final int toCodePoint(char, char)

Package com.ibm.icu.text
UTF16
(stable) public static boolean isLeadSurrogate(char)
(stable) public static boolean isSurrogate(char)
(stable) public static boolean isTrailSurrogate(char)
```

This, together with missing package versions metadata, may lead to following issue:

all downstream bundles that required smaller version of the bundle **or removed package version constraints** (after we've [removed Orbit version](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/367), see #381), will get now 71.1 bundle resolved and might run into incompatibility issues.

To fix that, all downstream clients should now either 

1) verify that the code isn't affected and be happy
2) or change require bundle to 67.1 and add maximum version range constraint to 71.1 
3) or change from package import **without version** to require bundle with version constraint

Since we are in 4.25 M3, I would propose to revert the change, because the possibility to break existing clients short before release is very high.

Note: the JDT UI bundles would need another "touch", just reverting https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/216 should be OK.

**Comment by akurtakov** [comment]
So the proposal is to revert not and push again for 4.26 from the very beginning?

**Comment by iloveeclipse** [comment]
> So the proposal is to revert not and push again for 4.26 from the very beginning?

Yes. Revert #439 for 4.25 M3 and update in 4.26, so downstream clients have a chance to react before release.

**Comment by iloveeclipse** [comment]
From where I was involved, GEF, Webtools, CDT, EMF validation are using ICU and were updated to **remove** versioned packages because of #381. 
Now they have to double check if they use affected classes and introduce version ranges / require bundle.

**Comment by akurtakov** [comment]
Do you mean reverting may create more work for these projects?

**Comment by iloveeclipse** [comment]
No, 71.1 is the problem. Reverting to 67 is not a problem.

**Comment by akurtakov** [comment]
OK. let's do it in that case.

**Comment by iloveeclipse** [comment]
In all cases, for the update to 71 the projects will have to check if they use affected classes and if yes, either update the code (in either way) or the dependencies constraints.

**Comment by merks** [comment]
What happened with the plan to remove it entirely?

https://www.eclipse.org/lists/cross-project-issues-dev/msg17598.html

**Comment by iloveeclipse** [comment]
> What happened with the plan to remove it entirely?

Someone could volunteer to do that :-)
At least to create issues in affected SDK repositories.

**Comment by iloveeclipse** [comment]
I will try to fix that for JDT UI classes.

**Comment by akurtakov** [comment]
> What happened with the plan to remove it entirely?
> 
> https://www.eclipse.org/lists/cross-project-issues-dev/msg17598.html

Last time it was blocked by https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.core.databinding/src/org/eclipse/core/databinding/conversion/NumberToStringConverter.java/StringToNumberConverter.java exposing it in our API.  It got deprecated in favor of classes in https://github.com/eclipse-platform/eclipse.platform.ui/tree/master/bundles/org.eclipse.core.databinding/src/org/eclipse/core/databinding/conversion/text. Unfortunately we haven't done the part to schedule these for removal ( I thought we did!) so we will have to leave with ICU4J for couple more years at least.

**Comment by akurtakov** [comment]
I've opened https://github.com/eclipse-platform/eclipse.platform.ui/issues/262 to schedule the removal.

**Comment by merks** [comment]
Thank you both for the prompt responses and the information!!

**Comment by akurtakov** [comment]
@iloveeclipse Pushed the revert of targetplatform. Would you please push the revert of touching bundles so the next I-build in couple of hours has the old icu4j.

**Comment by iloveeclipse** [comment]
> Would you please push the revert of touching bundles so the next I-build in couple of hours has the old icu4j.

Just waiting for tests to finish: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/218

**Comment by Phillipus** [comment]
FWIW GEF Legacy no longer uses ICU4J:

https://github.com/eclipse/gef-classic/commit/6b6eba6093e4f62536bec7d2f198aa961765cfa9

**Comment by akurtakov** [comment]
> FWIW GEF Legacy no longer uses ICU4J:
> 
> [eclipse/gef-classic@6b6eba6](https://github.com/eclipse/gef-classic/commit/6b6eba6093e4f62536bec7d2f198aa961765cfa9)

Thank you! Looks like this "churn" is beneficial after all :).

**Comment by Phillipus** [comment]
> or change require bundle to 67.1 and add maximum version range constraint to 71.1

But doesn't that mean a plug-in with dependency on icu4j will get the 71.1 version?

**Comment by iloveeclipse** [comment]
> > or change require bundle to 67.1 and add maximum version range constraint to 71.1
> 
> But doesn't that mean a plug-in with dependency on icu4j will get the 71.1 version?

I meant `[67, 71)` constraints. Most plugins I saw jad no upper version constraints for ICU at all.

**Comment by Phillipus** [comment]
I yes, I forgot that the maximum version can be set to "exclusive".

**Comment by Phillipus** [comment]
I have a plug-in that has a dependency on icu4j. Up until now I've been using the 67.1 Eclipse bundle by declaring it in Required Plug-ins.

Now I'm experimenting with including my own copy of the `icu4j-67.1.jar` taken from maven central and adding that to my plug-in's "lib" folder and declaring it in the `Bundle-ClassPath` section of MANIFEST.MF.

But then I discover that my plug-in is being loaded very early before the workbench is running because an EMF plug-in is trying to resolve class `com.ibm.icu.text.Collator` in its bundle loader in `org.eclipse.emf.common.CommonPlugin`:

```java
  private static final Method COLLATOR_GET_INSTANCE_METHOD;
  static
  {
    Method collatorGetInstanceMethod = null;
    try
    {
      Class<?> collatorClass = loadClass("com.ibm.icu", "com.ibm.icu.text.Collator");
      collatorGetInstanceMethod = collatorClass.getMethod("getInstance", Locale.class);
    }
    catch (Throwable throwable)
    {
      // Assume the class is not available.
    }
    COLLATOR_GET_INSTANCE_METHOD = collatorGetInstanceMethod;
  }
```

So if the EMF bundle finds my copy of `icu4j-67.1.jar` will it load that instead of the Eclipse bundle?

**Comment by iloveeclipse** [comment]
If you don't export any ICU package included in your bundle, you can use your own ICU copy,  thanks to bundles classloading isolation.

**Comment by iloveeclipse** [comment]
I would appreciate if we would not hijack this issue for "how to use 3rd party libraries". Please create dedicated issue or question.

**Comment by pcdavid** [comment]
> From where I was involved, GEF, Webtools, CDT, EMF validation are using ICU and were updated to **remove** versioned packages because of #381.
> Now they have to double check if they use affected classes and introduce version ranges / require bundle.

I've published (and contributed to the SimRel) new versions of EMF Validation ([1.13.1](https://github.com/eclipse/emf-validation/milestone/1)) and GMF Runtime ([1.15.1](https://github.com/eclipse/gmf-runtime/milestone/4)) which no longer depend on ICU4J at all.
EMF Transaction does not use ICU4J, so no new version for it.

A version of Sirius (7.0.3) with [a similar change](https://git.eclipse.org/r/c/sirius/org.eclipse.sirius/+/195142) should be released soon (this week) and contributed for M3.
