### ISSUE TITLE
4.25 Acknowledgements

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#506]

**Comment by sravanlakkimsetti** [comment]
Prepared as part of https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/17

**Comment by BeckerWdf** [comment]
Are you sure that the contributors stated in the acknowledgements are correct. Didn't we merge one repo into another in this release. And could it be that the contributors from the"old" commits from this repository now again appear in the a?cknowledgements
