### ISSUE TITLE
IBuilds should not manipulate content.xml (and remove content.jar/content.xml.xz )

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.releng.aggregator#509]
Recent I-Builds such as this one are missing content.jar/content.xml.xz:

https://download.eclipse.org/eclipse/updates/4.25-I-builds/I20220831-0600/

**Comment by merks** [comment]
@akurtakov @sravanlakkimsetti  Hopefully the final release repo will not be like this.

**Comment by akurtakov** [comment]
Hmm, there have been such problem in the not so distant past too. What I recall is that we had some long standing hack to keep these produced.

**Comment by merks** [comment]
That's really odd!!

**Comment by mickaelistria** [comment]
I believe this one is deleted because some further operation do process the content.xml file and then repacks it.

**Comment by sravanlakkimsetti** [comment]
We do create content.jar during our build promotion process. They exist in https://download.eclipse.org/eclipse/updates/4.24/R-4.24-202206070700/

Here is the location where they get created https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/1d31929a9d998442efb02f0a7f1329ae7ece4058/cje-production/promotion/promoteSites.sh#L238

**Comment by merks** [comment]
I see.  We should note though that the platform's IBuilds are one of the most heavily used update sites that exist at Eclipse, and it has new content daily, so not providing compressed content metadata is bad for the multitude of clients and hence bad for the server...  But nothing is actually broken...

**Comment by akurtakov** [comment]
For  4.26 stream I'll remove the xslt manipulation and use the content.jar as created by the build. If any breakage is uncovered we will fix it directly in the build to have proper content rather than manipulation postfactum.

**Comment by laeubi** [comment]
@akurtakov @sravanlakkimsetti we are having issues here again:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3748

can someone please explain why the tycho produced content is not good enough to be used? Tycho even has a "fix" goal for a repository that is modified by the current build with support to restore the compressed content if needed (but this depends on the actual modifications).

**Comment by akurtakov** [comment]
Honestly, I don't remember anything about this one.

**Comment by akurtakov** [comment]
Closing this one in favor of the new one https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1912 where hopefully a fix is implemented.
