### ISSUE TITLE
Configure SWT build scripts for 4.24

### ISSUE THREAD

**Issue by niraj-modi** [eclipse-platform/eclipse.platform.releng.aggregator#51]

**Comment by niraj-modi** [comment]
Created below bugzilla entry:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=579079

Corresponding Gerrit change:
https://git.eclipse.org/r/c/platform/eclipse.platform.swt/+/191440

**Comment by sravanlakkimsetti** [comment]
Merged the code now
