### ISSUE TITLE
OOmphh still points to Latest (4.25 - 2022-09)

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.releng.aggregator#546]
[oomph\PlatformSDKConfiguration.setup](https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse-platform/eclipse.platform.releng.aggregator/master/oomph/PlatformSDKConfiguration.setup&show=true)
Still asks me to install Latest = 4.25  - should be 4.26?!
![image](https://user-images.githubusercontent.com/51790620/188633444-140b614a-f560-460b-96ef-94ccf22eda05.png)

@merks  how is the update done?
does it relate to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/496 ?

**Comment by merks** [comment]
Sorry, this is a challenging period of time.    The platform is not yet released until next Wednesday and even the release repo does not yet exist here:

https://download.eclipse.org/eclipse/updates/4.25/

Lots of things need to be done to coordinated in the generated content and also shared tasks/variables.  E.g., here's an example of such a commit:

https://git.eclipse.org/c/oomph/org.eclipse.oomph.git/commit/?id=7e8e1c8c6b720fff55f35824cf4843ea64303c67

This will have to wait until next Wednesday...  Sorry for that...

**Comment by jukzi** [comment]
ok, thanks for the info
