### ISSUE TITLE
Publish 4.25 to maven central

### ISSUE THREAD

**Issue by SDawley** [eclipse-platform/eclipse.platform.releng.aggregator#548]

**Comment by sravanlakkimsetti** [comment]
final release repository is available 
```
	Promoted on: Thu Sep  8 15:11:49 UTC 2022


	             DROP_ID           I20220831-1800
	         BUILD_LABEL           I20220831-1800
	          DROP_ID_EQ           I20220831-1800
	      BUILD_LABEL_EQ           I20220831-1800

	             DL_TYPE                        R
	            DL_LABEL                     4.25
	         DL_LABEL_EQ                     4.25
	ECLIPSE_DL_DROP_DIR_SEGMENT      R-4.25-202208311800
	EQUINOX_DL_DROP_DIR_SEGMENT      R-4.25-202208311800
	   REPO_SITE_SEGMENT                     4.25
	           HIDE_SITE                     true
	Eclipse downloads:
	https://download.eclipse.org/eclipse/downloads/drops4/R-4.25-202208311800/

	Update existing (non-production) installs:
	https://download.eclipse.org/eclipse/updates/4.25/

	Specific repository good for building against:
	https://download.eclipse.org/eclipse/updates/4.25/R-4.25-202208311800/

	Equinox specific downloads:
	https://download.eclipse.org/equinox/drops/R-4.25-202208311800/
```

We can give a try to upload maven artifacts. should be released by Sep 14, 2022 10 AM newyork time

cc @mickaelistria @akurtakov

**Comment by akurtakov** [comment]
@merks Can you run your checks?

**Comment by merks** [comment]
Please keep in mind the comments here:

https://github.com/eclipse-platform/eclipse.platform.releng/pull/71#issuecomment-1234052526

I do believe you will need to make some minor changes as described in that comment.

Please do check the contents of the enhanced poms keeping in mind that the aggregator generates a name and a description from the IU metadata.

![image](https://user-images.githubusercontent.com/208716/189288567-9a6411a1-3673-4cb3-ac1d-abb3e5f82169.png)

When a description is missing, the name will be used as the description.

Look in particular that only single name and a single description present in the enhanced POMs.

In any case, the checks do not reveal any generated dependencies that are not resolvable, so that looks to be in good shape.

**Comment by mickaelistria** [comment]
Do you think this name/description issue is worth an immediate effort and potentially risking our ability to deliver in time?
If it's OK to release to Central despite this glitch, we can run the Publish scripts now so we'll have access to the Maven staging repositories if some are already willing to test them for their Maven projects. By the way, I've opened https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/549 as I think this should be more automated (only the Central staging->release step should be manual ideally)

**Comment by merks** [comment]
Maven central likely will reject the repo if the Pom doesn’t conform to the schema. It does, for example, when the description is missing.  You could try but better to avoid that risk.

**Comment by mickaelistria** [comment]
I'm trying to publish snapshots at the moment before publishing relase, and this fails with a lot of messages like
```
Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign-and-deploy-file (default-cli) on project org.eclipse.jdt.publish2maven: Error parsing POM /home/jenkins/agent/workspace/PublishJDTtoMaven/org/eclipse/jdt/org.eclipse.jdt/3.18.1300-SNAPSHOT/org.eclipse.jdt-3.18.1300-20220831.180000-0.pom: Duplicated tag: 'name' (position: START_TAG seen ...</description>\n  <name>... @23:9) -> [Help 1]
```
in https://ci.eclipse.org/releng/view/Publish%20to%20Maven%20Central/job/PublishJDTtoMaven/58/console

**Comment by sravanlakkimsetti** [comment]
From the pom generated.
```
  <name>Eclipse Java Development Tools</name>
  <description>Eclipse Java Development Tools</description>
  <name>Eclipse Java Development Tools</name>
```

\<name\> is generated twice

**Comment by merks** [comment]
Yes please see detailed comment I mentioned earlier that shows what needs to change. I can help with a pr but not until I’m home.

**Comment by mickaelistria** [comment]
I think https://github.com/eclipse-platform/eclipse.platform.releng/pull/99 will fix this issue.
I think it's a good thing if we manage to progressively remove duties from the EnrichPom. Ideally, if we manage the GAV properly in source and as the p2->pom CBI converter becomes smarter, such custom steps from Platform could be discarded in the future.

**Comment by mickaelistria** [comment]
OK, so this issue is solved. A new one is that I see a lot of `.log/artifact-upload.txt:gpg: signing failed: Bad passphrase` in the publish jobs...

**Comment by sravanlakkimsetti** [comment]
This we will require help from foundation. There are three gpg configurations we use each for platform, jdt and pde. Probably and issue with gpg configuration of pde and jdt.

**Comment by mickaelistria** [comment]
I've opened https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1919 to infra team. But if it works fine for Platform (does it), then shouldn't we use the Platform key for everything on that server and drop the PDE and JDT keys?

**Comment by sravanlakkimsetti** [comment]
Based on the log the maven upload is working for platform. but not for jdt and pde. We can try with the same gpg for pde and jdt if it works.

**Comment by mickaelistria** [comment]
OK, using Platform PGP credentials works.

**Comment by mickaelistria** [comment]
https://github.com/eclipse-platform/eclipse.platform.releng/pull/100

**Comment by mickaelistria** [comment]
> OK, using Platform PGP credentials works.

I was wrong, further errors are reported, we moved from "Bad passphrase" to "No secret key"

**Comment by mickaelistria** [comment]
I finally managed to get everything published to snapshots after a series of fixes in the various scripts.
I'll start the process to get those stages to OSSRH, let's hope for luck!

**Comment by merks** [comment]
@mickaelistria That's great to hear!

**Comment by mickaelistria** [comment]
So I've restored the project-specific PGP keys because OSSRH Nexus requires them (fine), and the reason why they were failing was a bug in the scripts that got fixed (good too).
Some repos are closed and staged for release, to be promoted by clicking "release" in Nexus when we're ready (the list will be updated as progress happens)
* PDE is staging at https://oss.sonatype.org/content/repositories/orgeclipsepde-1040
* JDT was published but fails to be staged because `Missing: no sources jar found in folder '/org/eclipse/jdt/ecj/3.31.0'`
* Platform publication is in progress at https://ci.eclipse.org/releng/job/PublishPlatformToMaven/104/

**Comment by iloveeclipse** [comment]
> * JDT was published but fails to be staged because `Missing: no sources jar found in folder '/org/eclipse/jdt/ecj/3.31.0'`

 This is a wrong version it should be `3.31.100`

**Comment by mickaelistria** [comment]
According to https://download.eclipse.org/eclipse/updates/4.25/R-4.25-202208311800/plugins/ , what we have in 4.25 is  org.eclipse.jdt.core.compiler.batch_3.31.0.v20220831-1439.jar. This is the version for ecj artifact, isn't it?

**Comment by iloveeclipse** [comment]
> This is a wrong version it should be `3.31.100`

I was wrong, checked wrong version. 3.31.0 should be OK.

**Comment by mickaelistria** [comment]
`Missing: no sources jar found in folder '/org/eclipse/jdt/ecj/3.31.0'` was fixed with a ugly hack to force inclusion of those sources when pushing to Maven: https://github.com/eclipse-platform/eclipse.platform.releng/blob/931be7b056591034a949bd182e3842c585a3adfe/publish-to-maven-central/publishJDT.sh#L119..L128 , but JDT Staging Maven repo is available for testing at https://oss.sonatype.org/content/repositories/orgeclipsejdt-1040

**Comment by merks** [comment]
I wonder how this worked in the past without this change to produce this previous version:

https://repo1.maven.org/maven2/org/eclipse/jdt/ecj/3.30.0/

**Comment by sravanlakkimsetti** [comment]
> I wonder how this worked in the past without this change to produce this previous version:
> 
> https://repo1.maven.org/maven2/org/eclipse/jdt/ecj/3.30.0/

https://github.com/eclipse-platform/eclipse.platform.releng/blob/8733c3bca7fcd864ce6a40ce1e0071f3a2222097/publish-to-maven-central/CBIaggregator.sh#L389 should get the ecj sources jar

**Comment by sravanlakkimsetti** [comment]
> So I've restored the project-specific PGP keys because OSSRH Nexus requires them (fine), and the reason why they were failing was a bug in the scripts that got fixed (good too). Some repos are closed and staged for release, to be promoted by clicking "release" in Nexus when we're ready (the list will be updated as progress happens)
> 
> * PDE is staging at https://oss.sonatype.org/content/repositories/orgeclipsepde-1040
> * JDT is stagng at https://oss.sonatype.org/content/repositories/orgeclipsejdt-1040
> * Platform fails to be staged because `Missing: no sources jar found in folder '/org/eclipse/platform/org.eclipse.e4.ui.progress/0.3.500'`

This we may need to find a way to fix it in next release. But for the current problem we have a way to recreate sources bundles here is the code that creates source bundles https://github.com/eclipse-platform/eclipse.platform.releng/blob/8733c3bca7fcd864ce6a40ce1e0071f3a2222097/publish-to-maven-central/CBIaggregator.sh#L383

Need to update https://github.com/eclipse-platform/eclipse.platform.releng/blob/master/publish-to-maven-central/sourceBundles.txt with necessary information. That will create the required source bundles

Adding 
```
eclipse-platform/eclipse.platform.ui.git \
	bundles/org.eclipse.e4.ui.progress \
	S4_25_0_RC2 \
	org/eclipse/platform org.eclipse.e4.ui.progress 0.3.500
```

**Comment by mickaelistria** [comment]
Thanks @sravanlakkimsetti 
I actually didn't edit the properties.sh file as it didn't happen to be necessary so far. Only the ECJ case would have deserved it, but I still think that we could/should get rid of this exception in a near future by publishing `org.eclipse.jdt.core.compiler.batch.source` to the p2 repo (see https://github.com/eclipse-jdt/eclipse.jdt.core/issues/384 ).
For `org.eclipse.e4.ui.progress.source`, this should be already fixed for 4.26-I-Builds, so we can get rid of the workaround very soon. I suspect we should apply a similar fix to  org.eclipse.e4.tools.emf.ui so the publish scripts can be simplified.

**Comment by mickaelistria** [comment]
All repos are now staging, can be tested and ready to be released:
* PDE is staging at https://oss.sonatype.org/content/repositories/orgeclipsepde-1040
* JDT is stagng at https://oss.sonatype.org/content/repositories/orgeclipsejdt-1040
* Platform is staging at https://oss.sonatype.org/content/repositories/orgeclipseplatform-1058

**Comment by mickaelistria** [comment]
@sravanlakkimsetti @SDawley please tell me when the artifacts can be published to Central, or you can also go to oss.sonatype.org and release the 3 staging repos directly.

**Comment by merks** [comment]
Note that the testing the changes for https://github.com/eclipse-platform/eclipse.platform.releng/issues/113 reveal that much of the "enriched" POM information has errors...

**Comment by sravanlakkimsetti** [comment]
> @sravanlakkimsetti @SDawley please tell me when the artifacts can be published to Central, or you can also go to oss.sonatype.org and release the 3 staging repos directly.

@mickaelistria You can release them now. It takes about 6 to 24 hours to update maven mirrors. You can release them now.

**Comment by mickaelistria** [comment]
Artifacts are now available on https://repo1.maven.org/maven2
