### ISSUE TITLE
Bouncycastle bundle duplication

### ISSUE THREAD

**Issue by serge-rider** [eclipse-platform/eclipse.platform.releng.aggregator#593]
After https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/418 resolution any RCP based on 2022-09 (as well as Eclipse IDE) contains both 1.70.0 and 1.71.0 versions of Bouncycastle. 

Also there are no new org.bouncycastle.bcpkix and org.bouncycastle.bcutil bundles (only old 1.70.0). So its not possible to get rid of old version even forcibly (e.g. by using tycho filters).

**Comment by vogella** [comment]
cc @mickaelistria

**Comment by mickaelistria** [comment]
bcpkix and bcpkix are not shipped by Platform. Platform only ships bouncycastle 1.71 as you can see in https://download.eclipse.org/eclipse/updates/4.25/R-4.25-202208311800/plugins/ . So this is not an issue in Eclipse Platform, so we'll close this bug.
The issue must be reported to the Eclipse Simultaneous Release which creates https://download.eclipse.org/releases/2022-09/202209141001/plugins/

**Comment by vogella** [comment]
@serge-rider you could restrict the used version via a target platform. Are you using a target platform?

**Comment by serge-rider** [comment]
@mickaelistria The main problem is not in missing bcpkix (I can take it from Orbit) but in duplicated bcprov.
Could you advise where can I report this issue to the Eclipse Simultaneous Release?

@vogella Yes, I do. But I can't. 
I can't force 1.70 usage because platform (p2.core) explicitly requires 1.71.  I can't force to 1.71 because there are no bcpkix and bcutil for version 1.71 in the target platform.

**Comment by vogella** [comment]
Adding @merks for simrel questions

**Comment by merks** [comment]
Yes there are quite a few duplicates on the train as seen in this report:

https://download.eclipse.org/oomph/archive/reports-extra/2022-09/download.eclipse.org/releases/2022-09/https___download.eclipse.org_releases_2022-09_202209141001.html

So yes depending on what you install you will have duplicates. 

This can only be avoided if all the projects contributing to simrel actively avoided the problem.  But all too often that is like trying to get 70 cats to run in the same direction. 

Does this duplication cause any actual problems?

**Comment by serge-rider** [comment]
@merks thanks for explanation.

Duplication is not critical. It just adds extra 7 mb to distro size. As it affects all RCP apps it is not good for environment ;)

It is potentially dangerous as different versions of bouncycastle may be loaded by different plugins. But I am not aware about any real problems.

**Comment by merks** [comment]
@serge-rider Yes, I know that duplication can cause wiring failures at runtime, but that only happens when the the library's classes are surfaced in the API, leading to conflicts about which version of the library to use.  So if you don't see writing issues in the log, then it's mostly likely not a problem to have duplicates.
