### ISSUE TITLE
I need to run Eclipse with different Java version

### ISSUE THREAD

**Issue by domino2** [eclipse-platform/eclipse.platform.releng.aggregator#605]
Hello, I found on stackoverflow.com to change the app's eclipse.ini file to contains this
```
...
-vm 
C:\Java\jre6\bin\javaw.exe
...
```
I did a build my self and found that file in the 
`./eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/target/products/org.eclipse.platform.ide/macosx/cocoa/x86_64/Eclipse.app/Contents/Eclipse/eclipse.ini`

But I'm wondering if this is proper way to do this as the **Eclipse.app** seems to me like distribution file and I would to expect to set some local file instead (for example in the ~/.config folder) or use the environment variable if running from command line (like JAVA_PATH), bud this understandably doesn't work (as I suppose this way is not consumed by the Eclipse application in behalf of the ini file).

**Comment by domino2** [comment]
I just tried the JAVA_PATH before running the Eclipse.app, but got and an issue with older java version. I would to point that I need older java version by default set to 1.8 because of the company app.

I didn't try to set the ini file yet.

**Comment by merks** [comment]
You can use -vm on the command line. I think whatever is returned by /usr/libexec/java_home is used on Mac be default:

![image](https://user-images.githubusercontent.com/208716/193442114-cc32c5be-b9d5-4df8-98d1-7b6b019b200b.png)

Of course you know that recent versions of Eclipse require Java 11, right?

**Comment by mickaelistria** [comment]
I'm closing this issue as it's not really an issue but a support request, which are not taken into account in the backlog. However, I don't think there is really a better channel for user support at the moment, so we can't blame you for choosing this one ;) The discussion can continue despite the issue being closed.

**Comment by domino2** [comment]
Great, this is the command to run it from cli:
`open -a "$(pwd)/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/target/products/org.eclipse.platform.ide/macosx/cocoa/x86_64/Eclipse.app" --args -vm /usr/local/Cellar/openjdk@17/17.0.4.1/bin/java`

I would to point, that there has to be absolute path, therefore `$(pwd)` is placed.

Thanks

**Comment by sravanlakkimsetti** [comment]
notifications: @lshanmug
