### ISSUE TITLE
org.eclipse.ua.tests.doc.internal.linkchecker.ApiDocTest fails since I20221002-0330

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#613]
https://download.eclipse.org/eclipse/downloads/drops4/I20221005-1800/testresults/html/org.eclipse.ua.tests.doc_ep426I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

```
expected:<[]> but was:<[ * Unexpected exported API packages in topics_Reference.xml: org.eclipse.equinox.http.jetty ]>

org.junit.ComparisonFailure: expected:<[]> but was:<[
* Unexpected exported API packages in topics_Reference.xml:
org.eclipse.equinox.http.jetty
]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at org.eclipse.ua.tests.doc.internal.linkchecker.ApiDocTest.testTopicsReference(ApiDocTest.java:183)
```

Interestingly, the test failed initially on all platforms , but now on all **except Windows**. ???

**Comment by akurtakov** [comment]
That's really weird. I touched all doc bundles via https://ci.eclipse.org/releng/job/Touch_doc_bundles/58/ to make sure that it's not some issue caused by the javadoc issues lately.

**Comment by iloveeclipse** [comment]
Probably related commits on aggregator went into I20221002-0330:
- 2a9abb394ca8368fd60972ae1c770b639d11394e
- 11e7d74a58e046d98d7791ac111ae33641ded0cd

**Comment by iloveeclipse** [comment]
Good news: the test is now **consistently** failing on all platforms. 
Bad news: it still fails.

Just in case it might be still needed, I've triggered https://ci.eclipse.org/releng/job/Touch_doc_bundles/60/

**Comment by iloveeclipse** [comment]
> the test is now **consistently** failing on all platforms.

Nope. It looks like fails on some random platforms every day. 
**Why** it is random?

**Comment by akurtakov** [comment]
My investigation pointed me in the direction that o.e.equinox.http.jetty sometimes is/isn't in the State returned here https://github.com/eclipse-platform/eclipse.platform.ua/blob/901a358e5cc6b64a4ed254affb7fb76ecd3ed9f8/org.eclipse.ua.tests.doc/src/org/eclipse/ua/tests/doc/internal/linkchecker/ApiDocTest.java#L284 .
Maybe @tjwatson  can help here?

**Comment by akurtakov** [comment]
I looked for this issue so I can close it in ua and .github repos but haven't thought to look for it here :)
