### ISSUE TITLE
Aggregator build fails trying deploy non existing Java 19 build

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#619]
See https://ci.eclipse.org/releng/job/Builds/job/I-build-4.26/42/console

`ERROR: No item named ep426I-unit-cen64-gtk3-java19 found`

Looks like something changed in aggregator to expect this job below to exist (which is not the case) :

https://ci.eclipse.org/releng/job/ep426I-unit-cen64-gtk3-java19

@akurtakov , @sravanlakkimsetti , @SDawley : any idea where and what was changed?

Did we forget to create new jenkins job now?

**Comment by iloveeclipse** [comment]
Should [ep426I-unit-cen64-gtk3-java18](https://ci.eclipse.org/releng/job/ep426I-unit-cen64-gtk3-java18/) be renamed to / replaced by https://ci.eclipse.org/releng/job/ep426I-unit-cen64-gtk3-java19 ?

**Comment by SDawley** [comment]
I'd hoped to move to java 19 as part of #568 but I'm having trouble getting the new jobs to run in a folder so I'll move the 18 jobs to 19 manually for now.

**Comment by iloveeclipse** [comment]
OK, whatever you did it seem to work now:
https://download.eclipse.org/eclipse/downloads/drops4/I20221010-1250

Thanks @SDawley.
Is your work documented somewhere, so that it could be repeated later with less troubles?
