### ISSUE TITLE
Update RedDeer to 4.4.0

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.releng.aggregator#648]
This version moved to require Java 17 which means we would have to bump org.eclipse.pde.ui.tests.smartimport bundle to Java 17 too. 
As our build already requires Java 17 for Tycho I see no issue in requiring it for test plugin too.

**Comment by vogella** [comment]
Don't we run tests with Java 11, Java 17, etc? Looks to me in https://download.eclipse.org/eclipse/downloads/drops4/I20221026-1800/testResults.php

**Comment by akurtakov** [comment]
We do so we need a way to not execute smartimport tests with Java 11 anymore. Or bite the bullet and run tests only with Java 17.

**Comment by sravanlakkimsetti** [comment]
jdt.core has a way. based on the java version they run a set of tests. with java 11 jdt core runs tests related to java 11 and below. for example tests related to multiline strings are not executed in java 11 test run.

**Comment by sravanlakkimsetti** [comment]
We can run a test bundle based on the jvm used. for example https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/e0b6bdfb195659c1fc784cc3a1885869108f0b91/production/testScripts/configuration/sdk.tests/testScripts/test.xml#L2079 we check whether the current jvm is higher than java 6 and run the jdt core tests. We do a similar approach. in this case.

We can achieve this programmatically as used in JDT.
1. create a method to compare java version with expected java version similar to https://github.com/eclipse-jdt/eclipse.jdt.core/blob/3d57dd0a6b1fc9c5585b663998ba21b3c063fcfb/org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/AbstractBatchCompilerTest.java#L45
2. use this method to check whether the test is valid for that specific version of jre like https://github.com/eclipse-jdt/eclipse.jdt.core/blob/3d57dd0a6b1fc9c5585b663998ba21b3c063fcfb/org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/BatchCompilerTest_15.java#L50

**Comment by akurtakov** [comment]
I'll be pushing this one soon.

**Comment by akurtakov** [comment]
So o.e.pde.ui.tests.smartimport are not run in I-build but that's actually good as these can no longer run on Java 11. Closing as we are done here.
