### ISSUE TITLE
Recent versions of Java, including the most recent Java 17 release, now consider some bundles to be unsigned

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.releng.aggregator#661]
In particular this issue has kicked in

https://www.oracle.com/java/technologies/javase/17-relnote-issues.html#JDK-8196415

As a result, everything signed  by this certificate between January 1, 2019 and when it expired is treated as unsigned:

![image](https://user-images.githubusercontent.com/208716/201321491-8b040035-ca6f-4d5d-93fe-bc1c742f6ce2.png)

For the platform specifically, this repository content of the most recent 4.26 I-Build is treated as unsigned:

https://download.eclipse.org/oomph/archive/reports-extra/4.26-I-builds/download.eclipse.org/eclipse/updates/4.26-I-builds/I20221109-1850/index.html

This includes many Orbit bundles, which needs to be fixed in Orbit, but also these platform project bundles:

![image](https://user-images.githubusercontent.com/208716/201322260-9c55ba77-5416-4240-acf7-bfc4d1e812da.png)

I assume these would need to be touched to force a new version.

CC @akurtakov @jonahgraham @sravanlakkimsetti

**Comment by akurtakov** [comment]
I'll start version bumping them (touch is not enough as it will bump only qualifier).

**Comment by merks** [comment]
Thank you * 💯

**Comment by akurtakov** [comment]
I hope I did it all. Please tell if there is anything left after the next build is analyzed.

**Comment by merks** [comment]
Only Obit things left now:

![image](https://user-images.githubusercontent.com/208716/201460982-d391dcbc-39a8-4084-a68c-e3f8a2eefbed.png)

One potential problem I noticed with split-package signatures:

1. **org.osgi.service.component.annotations**
   - _[org.eclipse.osgi.services 3.11.100.v20221006-1531, org.osgi.service.component.annotations 1.5.0.202109301733]_
   - {CN=Eclipse.org Foundation, Inc., OU=IT, O=Eclipse.org Foundation, Inc., L=Ottawa, ST=Ontario, from=2022-05-02, to=2024-05-22}
   - unsigned

I think it's best to open a new issue for that.

**Comment by merks** [comment]
@akurtakov I opened this as a follow up:

https://github.com/eclipse-equinox/equinox/issues/157

**Comment by merks** [comment]
@akurtakov 

I overlooked that org.eclipse.equinox.simpleconfigurator.manipulator is still in the list.  😢

**Comment by merks** [comment]
I'll look to provide a PR...

**Comment by merks** [comment]
@akurtakov 

Another thing I overlooked 😱 is that we are pulling content from a very old version of Orbit for bundles that have not been migrated to recipes...

https://download.eclipse.org/tools/orbit/downloads/drops/R20201118194144/repository

Most of that content suffers from this signing problem:

https://download.eclipse.org/oomph/archive/reports-extra/orbit-platform/download.eclipse.org/tools/orbit/downloads/drops/R20201118194144/repository/index.html

Only if we PGP sign these bundles will the problem be resolved.  

So I think all the ones list here:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/e1890a45cf78e4c6c034edb0726400a99c0fda2b/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target#L50-L88

Would need to be listed here:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/e1890a45cf78e4c6c034edb0726400a99c0fda2b/eclipse.platform.releng.tychoeclipsebuilder/pom.xml#L48-L51

What do you think?

**Comment by merks** [comment]
@akurtakov  I'm not asking you to do anything just asking your opinion.   The latest test report:

https://download.eclipse.org/oomph/archive/reports-extra/4.26-I-builds/download.eclipse.org/eclipse/updates/4.26-I-builds/I20221117-1330/index.html

Shows these remaining issues:

![image](https://user-images.githubusercontent.com/208716/202713692-1034f95c-7f21-4f6a-bb32-cd96118cb3b2.png)

We could force PGP sign these.  Should we?

**Comment by mickaelistria** [comment]
> We could force PGP sign these. Should we?

+1 for that.

**Comment by merks** [comment]
@mickaelistria Thank goodness we improved p2 to support the verification of this during that last release and that you did the Tycho stuff to generate it too!!

**Comment by merks** [comment]
The report is now clean:

https://download.eclipse.org/oomph/archive/reports-extra/4.26-I-builds/download.eclipse.org/eclipse/updates/4.26-I-builds/I20221118-1800/index.html
