### ISSUE TITLE
Releng: Missing testManifest.xml Files

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#669]
See https://download.eclipse.org/eclipse/downloads/drops4/I20221114-1800/testResults.php

There is a large table that says Releng: "Missing testManifest.xml Files"

![image](https://user-images.githubusercontent.com/964108/201856795-d84745f2-89d3-4c75-bb54-2d4e812d76b5.png)

I have no idea what that means, but that sounds bad.

**Comment by akurtakov** [comment]
Instabilities are to be expected as releng scripts are moved to be tracked in git so what/when/how changed can be tracked and not pure magic like we did it for years. With that said, @SDawley please give highest priority to fixing these.

**Comment by iloveeclipse** [comment]
@SDawley : still in RC 1 build.

https://download.eclipse.org/eclipse/downloads/drops4/I20221117-1330/testResults.php

**Comment by iloveeclipse** [comment]
Appeared again in https://download.eclipse.org/eclipse/downloads/drops4/I20221121-1800/testResults.php

**Comment by SDawley** [comment]
Fixed again
