### ISSUE TITLE
Release 4.26

### ISSUE THREAD

**Issue by SDawley** [eclipse-platform/eclipse.platform.releng.aggregator#687]
Umbrella bug to track release activities for 4.26
For previous bug please refer to eclipse-platform/eclipse.platform.releng.aggregator#495.

- [x] [New & Noteworthy](https://github.com/eclipse-platform/eclipse.platform.common/pull/93)
- [x] #690
- [x] [4.26 Acknowledgements](https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/23)
- [x] Tips & Tricks
- [x] Migration Guide
- [x] SWT Javadoc bash for 4.26
- [x] Publish  to Maven central
- [x] Tag Eclipse 4.26 Release
- [x] Clean up intermediate artifacts (milestones, I-builds and old releases)

@notifications:
@SDawley, @lshanmug, @SarikaSinha, @ktatavarthi, @niraj-modi, @vik-chand, @sravanlakkimsetti

**Comment by SDawley** [comment]
Making this issue early since I will be on holiday during the RC2 release.

**Comment by SarikaSinha** [comment]
[Read Me ](https://github.com/eclipse-platform/www.eclipse.org-eclipse/issues/24)

**Comment by akurtakov** [comment]
@SDawley please veriry that all cleanups are performed and close this one.
