### ISSUE TITLE
Declare 4.26 RC2

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.releng.aggregator#691]
A "go" is needed from all the components below to declare this milestone.

Current Candidate

Eclipse downloads:
https://download.eclipse.org/eclipse/downloads/drops4/I20221123-1800

Build logs and/or test results (eventually):
https://download.eclipse.org/eclipse/downloads/drops4/I20221123-1800/testResults.php

Software site repository:
https://download.eclipse.org/eclipse/updates/4.26-I-builds

Specific (simple) site repository:
https://download.eclipse.org/eclipse/updates/4.26-I-builds/I20221123-1800

Equinox downloads:
https://download.eclipse.org/equinox/drops/I20221123-1800

---
Deadlines: 
- Friday, 2022-November-25, around 1 AM (Eastern): deadline for sign-off (or, by then, comment in this issue when you expect to sign-off).
- Friday, 2022-November-25, around 3 AM (Eastern): promote approved build to S-4.26RC2-*, contribute to simultaneous release repo, and announce to mailing lists.

Remember to investigate and document here any failing JUnit tests. 

---

- [ ] Platform:
- - [ ] Resources
- - [x] UI
- - [x] Debug
- - [x] Ant
- - [x] SWT
- - [x] Releng

- [ ] JDT:
- - [ ] Core
- - [x] Debug
- - [x] UI

- [x] PDE
- [ ] Equinox

**Comment by sravanlakkimsetti** [comment]
Go from platform releng

**Comment by vik-chand** [comment]
Go from PDE

Intermittent test failures are tracked by
 - https://github.com/eclipse-pde/eclipse.pde/issues/300
 - https://github.com/eclipse-pde/eclipse.pde/issues/261

**Comment by noopur2507** [comment]
Go from JDT UI.

**Comment by ktatavarthi** [comment]
Go from Platform UI

Windows test failure is captured  by
 - https://github.com/eclipse-platform/eclipse.platform.text/issues/35

**Comment by akurtakov** [comment]
No Equinox, JDT Core and Platform Resources sign offs so I'm proceeding without them only failing test in these components tests is org.eclipse.jdt.core.tests.model.EncodingTests#test021 and on windows only.

**Comment by akurtakov** [comment]
Promoted, contributed and announced.
