### ISSUE TITLE
SDK build broken since I20221203-0210

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#740]
SDK build broken since I20221203-0210, see 
- first fail: https://ci.eclipse.org/releng/job/Builds/job/I-build-4.27/11/console
- last fail: https://ci.eclipse.org/releng/job/Builds/job/I-build-4.27/15/console

The error is happening here:
```
output: /home/jenkins/agent/workspace/Builds/I-build-4.27/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/siteDir/eclipse/downloads/drops4/I20221205-0050/buildlogs/reporeports/reports/versionChecksFeatures.html
08:22:38  all feature groups IUs
08:22:38  Number in reference from raw count:79
08:22:38  Number in reference from set: 79
08:22:38  Number in current from raw count:79
08:22:38  Number in current from set: 79
08:22:38  Number in reference missing from current: 0
08:22:38  Number in common in reference and current: 79
08:22:38  Number in current missing from reference: 0
08:22:38  Number in common in reference and current: 79
08:23:00  Unable to init server: Could not connect: Connection refused
08:23:00  P2analyze: Cannot open display: 
08:23:00  P2analyze:
08:23:00  An error has occurred. See the log file
08:23:00  /home/jenkins/agent/workspace/Builds/I-build-4.27/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/tmp/reportApplication/p2analyze/configuration/1670224956496.log.
08:23:00  + [[ 13 -ne 0 ]]
08:23:00  + echo 'Failed in Generate Repo reports stage'
08:23:00  Failed in Generate Repo reports stage
08:23:00  + exit 1
```

@sravanlakkimsetti, @akurtakov : according to @mickaelistria 
```
I recently tried to update that application t newer Eclipse versions; I suspect this cause the issue. 
Can we have access to this /home/jenkins/agent/workspace/Builds/I-build-4.27/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/tmp/reportApplication/p2analyze/configuration/1670057020766.log file?
```

**Comment by iloveeclipse** [comment]
@sravanlakkimsetti : great, thanks! 
Can you please share **how** did you access the log files? Is any committer able to do this, or are there extra rights needed? In later case, can we modify the job so it can "list" or "publish" the workspace / build artifacts somewhere?

```
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.equinox.p2.core.IProvisioningAgent.getService(java.lang.Class)" because "agent" is null
	at org.eclipse.equinox.internal.p2.artifact.processors.pgp.PGPSignatureVerifier.initialize(PGPSignatureVerifier.java:104)
	at org.eclipse.cbi.p2repo.analyzers.jars.PGPVerifier.verify(PGPVerifier.java:46)
	at org.eclipse.cbi.p2repo.analyzers.jars.SignerTest$SignerCheck.accept(SignerTest.java:154)
	at org.eclipse.cbi.p2repo.analyzers.jars.SignerTest$SignerCheck.accept(SignerTest.java:1)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

IProvisioningAgent is null in the code above...

**Comment by iloveeclipse** [comment]
I guess the update mentioned by Mickael was https://github.com/eclipse-cbi/p2repo-analyzers/pull/16.

**Comment by sravanlakkimsetti** [comment]
> Can you please share **how** did you access the log files? Is any committer able to do this, or are there extra rights needed? In later case, can we modify the job so it can "list" or "publish" the workspace / build artifacts somewhere?

I ran locally.
download locations for prerequisites
1. p2analyzer: https://download.eclipse.org/cbi/updates/analyzers/snapshot/org.eclipse.cbi.p2repo.analyzers.product-linux.gtk.x86_64.tar.gz
2. reference repository: https://download.eclipse.org/eclipse/downloads/drops4/S-4.26RC2-202211231800/download.php?dropFile=repository-4.26RC2.zip
3. repository to be analyzed:  https://download.eclipse.org/eclipse/downloads/drops4/I20221201-1800/download.php?dropFile=repository-I20221201-1800.zip

Command to be used (from https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/b2cbb328986cd314ee302fb661a441852493c3c1/cje-production/mbscripts/mb500_createRepoReports.sh#L38):
`p2analyze -data <workspace location>  -vmargs -DreferenceRepo=<extracted reference reopsitory -DreportRepoDir=<repository to be analyzed> -DreportOutputDir=<location of the report>`

**Comment by iloveeclipse** [comment]
> I guess the update mentioned by Mickael was [eclipse-cbi/p2repo-analyzers#16](https://github.com/eclipse-cbi/p2repo-analyzers/pull/16).

@mickaelistria: Looking at the code it can't work with 4.25: https://github.com/eclipse-cbi/p2repo-analyzers/blob/1ff2329d8875ce8f247fabacef4caa30f21b0ed2/bundles/org.eclipse.cbi.p2repo.analyzers-bundle/src/org/eclipse/cbi/p2repo/analyzers/jars/PGPVerifier.java#L46
```
 verifier.initialize(null, null, artifactDescriptor);
```

**Comment by akurtakov** [comment]
New I-build launched https://ci.eclipse.org/releng/job/Builds/job/I-build-4.27/16/

**Comment by mickaelistria** [comment]
I suspect this is a consquence of https://github.com/eclipse-cbi/p2repo-analyzers/commit/1ff2329d8875ce8f247fabacef4caa30f21b0ed2

**Comment by iloveeclipse** [comment]
Fixed by https://github.com/eclipse-cbi/p2repo-analyzers/pull/17 
See https://download.eclipse.org/eclipse/downloads/drops4/I20221205-0710/

**Comment by iloveeclipse** [comment]
Thanks @merks !
