### ISSUE TITLE
Undected invalid maven dependency on org.eclipse.jetty:jetty-apache-jsp in target platform:

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.releng.aggregator#758]
I believe this dependency is wrong:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/affbb3a6d1fecebae0f55a5ae9fa9137f9c37d34/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target#L313-L318

The target definition editor shows nothing resolved for the Jetty location:

![image](https://user-images.githubusercontent.com/208716/206899928-2a00c75f-12c5-4623-8800-7bf43d3ba43c.png)

But it doesn't show any errors.  The build apparently doesn't care either that it's wrong.

@laeubi Is it a bug that the m2e extension to the target edit and the Tycho target resolver don't diagnose this error?

It should be like this:

![image](https://user-images.githubusercontent.com/208716/206900046-541fdc13-8505-40ec-b48e-fdf6a0eddc4d.png)

Then it can be properly resolved:

![image](https://user-images.githubusercontent.com/208716/206900015-4e475c89-6775-47ea-8296-1ab090ccf6ef.png)

And that actually exists at Maven central:

https://repo1.maven.org/maven2/org/eclipse/jetty/apache-jsp/

@akurtakov 

So now the question is, should the dependency be removed or should it be fixed?

**Comment by laeubi** [comment]
Error reporting for target-file is really poor in PDE so probably there *is* an error (that it shows no no plugins seems an indication of this) but no one has noticed (yet). But at least for Tycho I would have expected that an errornous item is reported.

**Comment by akurtakov** [comment]
Should this one be closed now?
