### ISSUE TITLE
Available target platform  version updates

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.releng.aggregator#759]
The following is a generated list of direct-from-maven dependencies in the SDK target platform for which there are newer versions available in Maven central than are currently being used in the 4.27 version of the target platform.  All the items in the report are links to maven central...

It looks like we'd want to update most of the things in this list.  Some of the jakarta things have much higher versions, so maybe we don't want to update those for a good reason?  Do we want to update to Jetty 10.0.13 rather than 11.0.13?  Is there a good reason for two versions of slf4j-api?  

- [biz.aQute.bnd](https://repo1.maven.org/maven2/biz/aQute/bnd/)
  - [biz.aQute.bnd.annotation](https://repo1.maven.org/maven2/biz/aQute/bnd/biz.aQute.bnd.annotation/) **[6.3.1](https://repo1.maven.org/maven2/biz/aQute/bnd/biz.aQute.bnd.annotation/6.3.1/)** < [6.4.0](https://repo1.maven.org/maven2/biz/aQute/bnd/biz.aQute.bnd.annotation/6.4.0/)
  - [biz.aQute.bnd.util](https://repo1.maven.org/maven2/biz/aQute/bnd/biz.aQute.bnd.util/) **[6.3.1](https://repo1.maven.org/maven2/biz/aQute/bnd/biz.aQute.bnd.util/6.3.1/)** < [6.4.0](https://repo1.maven.org/maven2/biz/aQute/bnd/biz.aQute.bnd.util/6.4.0/)
  - [biz.aQute.bndlib](https://repo1.maven.org/maven2/biz/aQute/bnd/biz.aQute.bndlib/) **[6.3.1](https://repo1.maven.org/maven2/biz/aQute/bnd/biz.aQute.bndlib/6.3.1/)** < [6.4.0](https://repo1.maven.org/maven2/biz/aQute/bnd/biz.aQute.bndlib/6.4.0/)
- [com.fasterxml.jackson.core](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/)
  - [jackson-annotations](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/) **[2.13.2](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.13.2/)** < [2.14.1](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.14.1/)
  - [jackson-core](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/) **[2.13.2](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.13.2/)** < [2.14.1](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.14.1/)
  - [jackson-databind](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/) **[2.13.2.2](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.13.2.2/)** < [2.14.1](https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.14.1/)
- [jakarta.el](https://repo1.maven.org/maven2/jakarta/el/)
  - [jakarta.el-api](https://repo1.maven.org/maven2/jakarta/el/jakarta.el-api/) **[4.0.0](https://repo1.maven.org/maven2/jakarta/el/jakarta.el-api/4.0.0/)** **<<<** [5.0.1](https://repo1.maven.org/maven2/jakarta/el/jakarta.el-api/5.0.1/)
- [jakarta.inject](https://repo1.maven.org/maven2/jakarta/inject/)
  - [jakarta.inject-api](https://repo1.maven.org/maven2/jakarta/inject/jakarta.inject-api/) **[1.0.5](https://repo1.maven.org/maven2/jakarta/inject/jakarta.inject-api/1.0.5/)** **<<<** [2.0.1](https://repo1.maven.org/maven2/jakarta/inject/jakarta.inject-api/2.0.1/)
- [jakarta.servlet](https://repo1.maven.org/maven2/jakarta/servlet/)
  - [jakarta.servlet-api](https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/) **[4.0.4](https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/4.0.4/)** **<<<** [6.0.0](https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/6.0.0/)
- [net.bytebuddy](https://repo1.maven.org/maven2/net/bytebuddy/)
  - [byte-buddy](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/) **[1.12.18](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.12.18/)** < [1.12.19](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.12.19/)
  - [byte-buddy-agent](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/) **[1.12.18](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.12.18/)** < [1.12.19](https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.12.19/)
- [org.bouncycastle](https://repo1.maven.org/maven2/org/bouncycastle/)
  - [bcpg-jdk18on](https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk18on/) **[1.72](https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk18on/1.72/)** < [1.72.2](https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk18on/1.72.2/)
- [org.eclipse.jetty](https://repo1.maven.org/maven2/org/eclipse/jetty/)
  - [apache-jsp](https://repo1.maven.org/maven2/org/eclipse/jetty/apache-jsp/) **[10.0.12](https://repo1.maven.org/maven2/org/eclipse/jetty/apache-jsp/10.0.12/)** < [10.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/apache-jsp/10.0.13/) **<<<** [11.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/apache-jsp/11.0.13/)
  - [jetty-http](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/) **[10.0.12](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/10.0.12/)** < [10.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/10.0.13/) **<<<** [11.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/11.0.13/)
  - [jetty-io](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/) **[10.0.12](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/10.0.12/)** < [10.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/10.0.13/) **<<<** [11.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/11.0.13/)
  - [jetty-security](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-security/) **[10.0.12](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-security/10.0.12/)** < [10.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-security/10.0.13/) **<<<** [11.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-security/11.0.13/)
  - [jetty-server](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/) **[10.0.12](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/10.0.12/)** < [10.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/10.0.13/) **<<<** [11.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/11.0.13/)
  - [jetty-servlet](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlet/) **[10.0.12](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlet/10.0.12/)** < [10.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlet/10.0.13/) **<<<** [11.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlet/11.0.13/)
  - [jetty-util](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/) **[10.0.12](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/10.0.12/)** < [10.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/10.0.13/) **<<<** [11.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/11.0.13/)
  - [jetty-util-ajax](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util-ajax/) **[10.0.12](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util-ajax/10.0.12/)** < [10.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util-ajax/10.0.13/) **<<<** [11.0.13](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util-ajax/11.0.13/)
- [org.slf4j](https://repo1.maven.org/maven2/org/slf4j/)
  - [slf4j-api](https://repo1.maven.org/maven2/org/slf4j/slf4j-api/) **[2.0.3](https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.3/)** < [2.0.5](https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.5/)
  - [slf4j-api](https://repo1.maven.org/maven2/org/slf4j/slf4j-api/) **[1.7.36](https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/)** **<<<** [2.0.5](https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.5/)
  - [slf4j-nop](https://repo1.maven.org/maven2/org/slf4j/slf4j-nop/) **[1.7.36](https://repo1.maven.org/maven2/org/slf4j/slf4j-nop/1.7.36/)** **<<<** [2.0.5](https://repo1.maven.org/maven2/org/slf4j/slf4j-nop/2.0.5/)

@akurtakov I'll make any desired changes based on your guidance.

**Comment by akurtakov** [comment]
Btw, how have you generated this list ? It would be nice if this can be contributed so dependabot offers patches automatically.

**Comment by merks** [comment]
@akurtakov I'm not sure how dependabot works nor how one might extend it...

In any case, the current implementation is a work in progress with the idea to extract direct-from-maven dependencies directly from the *.target file of various projects, with the Platform of course being the starting point.  Long term, I want it also to automatically detected new versions in Maven and to keep the generated *.target up-to-date.  Of course the parts of this implementation are reusable and in fact I've updated what I currently have such that it modifies the platform's source  *.target file with the latest dependency versions; in this case, I filtered out all version changes that increment the major version, and then manually removed the slf4j-api change for now.  That's how the changes to the manual PR above were created.  (Note that I'm trying to restrict the implementation to depend purely on what's in a JRE with no additional libraries, so that it's trivial to deploy.)

I do expect we will be able to create a job that automatically keeps the platform's *.target up-to-date...

**Comment by merks** [comment]
@HannesWell  One change I didn't make is the following to upgrade from 2.0.3 to 2.0.5:
```
				<dependency>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-api</artifactId>
					<version>2.0.5</version>
				</dependency>
```
Will there continue to be a need for two versions of this artifact?

**Comment by merks** [comment]
Currently everything is update-to-date as far as we want it.
