### ISSUE TITLE
No I-builds

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#790]
Looks like some infra is broken.

https://ci.eclipse.org/releng/view/Automated%20tests/
![image](https://user-images.githubusercontent.com/964108/211260224-d278b438-a484-4ded-85ba-3fab5cf99310.png)

Console says 
https://ci.eclipse.org/releng/view/Automated%20tests/job/Builds/job/I-build-4.27/63/console
```
Still waiting to schedule task
All nodes of label ‘[aggrbuild-pod](https://ci.eclipse.org/releng/label/aggrbuild-pod/)’ are offline
```

**Comment by akurtakov** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2470 is already reported

**Comment by iloveeclipse** [comment]
@akurtakov , @SDawley : I see now `$TAG` on every platform / JDT etc repo used in SDK build.

![image](https://user-images.githubusercontent.com/964108/211274501-af196b7b-4101-445d-8d62-328883783ae7.png)

Is this a side effect of broken build or unrelated issue?

**Comment by iloveeclipse** [comment]
> I honestly have no idea how that one happened. @HannesWell can it be result of your efforts to simplify swt build?

Just in case: the broken tag exists on **all** SDk related repos, not only on SWT.

**Comment by HannesWell** [comment]
> https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2470 is already reported

The mac agent already had issues on Friday and the infra team restarted it, but the problem remained.


> > I honestly have no idea how that one happened. @HannesWell can it be result of your efforts to simplify swt build?
> 
> Just in case: the broken tag exists on **all** SDk related repos, not only on SWT.

I hope it is not related. At least I did not yet change anything intentionally that was committed to the SWT or any other repo. The only thing that changed in that regard was the move of the eclipse.platform.swt pipeline to the releng Jenkins.

But from the name I would guess that the resolution of the `TAG` variable does not happen in the I-build and therefore all repos are tagged, as Andrey pointed out. But I have no idea why.

**Comment by iloveeclipse** [comment]
Let see if this `$TAG` will re-appear on next I-Build. If yes, I will create dedicated issue to work on.

**Comment by iloveeclipse** [comment]
Actually we need a dedicated ticket anyway, to remove the `$TAG` from our repositories => https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/793

**Comment by iloveeclipse** [comment]
OK, we have next IBuild now.
