### ISSUE TITLE
git tag `$TAG` added on every platform / JDT etc repo used in SDK build

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#793]
@akurtakov , @SDawley : I see now git tag `$TAG` on every platform / JDT etc repo used in SDK build.

![image](https://user-images.githubusercontent.com/964108/211274501-af196b7b-4101-445d-8d62-328883783ae7.png)

This could be a side effect of broken build (https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/790) or a separated issue.

In any case the git tag `$TAG` should be removed **once** by same SDK script that added that tag.

**Comment by SDawley** [comment]
I'll take a look

**Comment by SDawley** [comment]
OK, I've retagged the release and run the script again to remove all the erroneous $TAG tags.

Added https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/797 to fix this for next release. 

Closing but please reopen if a tag got missed somewhere.

**Comment by iloveeclipse** [comment]
Thanks @SDawley ! I see no `$TAG` anymore.
