### ISSUE TITLE
Consider disabling signing of builds that are not based on master/maintenance branches

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.releng.aggregator#794]
The m2e project does that like this:

https://github.com/eclipse-m2e/m2e-core/blob/c5866a2f4ac2c731dc2fe2aeb2355af826aef6f7/Jenkinsfile#L42-L55

That idea could be applied here:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/66a703cd6ee9d75d6680fe380d0b2b0de13aca4a/Jenkinsfile#L42-L52

This has the added advantage that the GPG details are not available during such builds and hence can't be compromised by a PR...

**Comment by merks** [comment]
@akurtakov 

We could try to do it conditionally like the m2e example.  What do you think of that?

**Comment by akurtakov** [comment]
Sounds good.

**Comment by merks** [comment]
It looks like this failure is caused by this change:
```
17:25:25  [INFO] --- tycho-gpg-plugin:4.0.0-SNAPSHOT:sign-p2-artifacts (default) @ eclipse-junit-tests ---
17:25:25  gpg: signing failed: Bad passphrase
17:25:25  gpg: signing failed: Bad passphrase
```
I'll have to investigate.  I imagine somewhere the PGP signing isn't guarded the same profile as jar signing.

**Comment by merks** [comment]
The build time is reduced to 17 minutes:

![image](https://user-images.githubusercontent.com/208716/211379584-6562ec99-8085-4f3f-b983-9b6f5d822226.png)

versus a more typical 45 minutes:

![image](https://user-images.githubusercontent.com/208716/211379679-88a7237e-6c3b-4295-a268-3b951abcab4e.png)
