### ISSUE TITLE
[20] Y-Build for Java 20

### ISSUE THREAD

**Issue by mpalat** [eclipse-platform/eclipse.platform.releng.aggregator#801]
Will require Y-build for Java 20 - BETA_JAVA20 branch

**Comment by mpalat** [comment]
@SDawley : Can you please help with this?
CC: @sravanlakkimsetti @akurtakov

**Comment by SDawley** [comment]
Will do.

**Comment by SDawley** [comment]
Y-Build created: https://ci.eclipse.org/releng/job/YPBuilds/job/Y-build/
But currently failing because eclipse.jdt.ui doesn't have a BETA_JAVA20 branch.
