### ISSUE TITLE
[20] P -Build

### ISSUE THREAD

**Issue by mpalat** [eclipse-platform/eclipse.platform.releng.aggregator#802]
P-Build for Java 20 [current branch - BETA_JAVA 20]

**Comment by mpalat** [comment]
CC: @jarthana @sravanlakkimsetti

**Comment by SDawley** [comment]
P-Builds have been set up but are currently failing: https://ci.eclipse.org/releng/job/YPBuilds/job/P-build/

**Comment by sravanlakkimsetti** [comment]
Beta java 20 branch is refering to 4.26 pom.xml. Requires a merge from master
