### ISSUE TITLE
Link to test jobs wrong on I builds result page

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#827]
I can't find where the "test results" pages template content is saved.

The link there saying 
"The unit tests are run on the [releng ci instance](https://ci.eclipse.org/releng/view/Automated%20tests/)." 
is wrong: instead of broken https://ci.eclipse.org/releng/view/Automated%20tests/ it should point to https://ci.eclipse.org/releng/view/Builds/job/AutomatedTests/

See https://download.eclipse.org/eclipse/downloads/drops4/I20230126-1800/testResults.php

**Comment by SDawley** [comment]
Created https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/866

If you'd ever like to edit the results pages etc, the templates can all be found in [eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles)

**Comment by iloveeclipse** [comment]
Still broken in https://download.eclipse.org/eclipse/downloads/drops4/I20230219-0600/testResults.php

**Comment by sravanlakkimsetti** [comment]
Update is required in testresults generator in build tools repository. 
A PR is raised https://github.com/eclipse-platform/eclipse.platform.releng.buildtools/pull/22

**Comment by sravanlakkimsetti** [comment]
rebuilt build tools repository via https://ci.eclipse.org/releng/job/EclipseBuildTools/206/
Published using https://ci.eclipse.org/releng/job/ep-deploy-build-tools/34/
