### ISSUE TITLE
Missing org.apache.commons.jxpath 1.2.0 dependency 

### ISSUE THREAD

**Issue by cdietrich** [eclipse-platform/eclipse.platform.releng.aggregator#842]
with M2 we are getting 

Error:  Cannot resolve project dependencies:
[15](https://github.com/itemis/xtext-reference-projects/actions/runs/4089874757/jobs/7052893875#step:4:16)
Error:    Software being installed: org.eclipse.rcp.feature.group 4.27.0.v20230126-1800
[16](https://github.com/itemis/xtext-reference-projects/actions/runs/4089874757/jobs/7052893875#step:4:17)
Error:    Missing requirement: org.eclipse.e4.emf.xpath 0.3.100.v20221024-2137 requires 'osgi.bundle; org.apache.commons.jxpath 1.2.0' but it could not be found
[17](https://github.com/itemis/xtext-reference-projects/actions/runs/4089874757/jobs/7052893875#step:4:18)
Error:    Cannot satisfy dependency: org.eclipse.e4.rcp.feature.group 4.27.0.v20230124-0843 depends on: org.eclipse.equinox.p2.iu; org.eclipse.e4.emf.xpath [0.3.100.v20221024-2137,0.3.100.v20221024-2137]
[18](https://github.com/itemis/xtext-reference-projects/actions/runs/4089874757/jobs/7052893875#step:4:19)
Error:    Cannot satisfy dependency: org.eclipse.rcp.feature.group 4.27.0.v20230126-1800 depends on: org.eclipse.equinox.p2.iu; org.eclipse.e4.rcp.feature.group [4.27.0.v20230124-0843,4.27.0.v20230124-0843]

is this one no longer packaged ?

**Comment by akurtakov** [comment]
Platform moved to [org.apache.commons.jxpath_1.3.0.jar](https://download.eclipse.org/eclipse/updates/4.27-I-builds/I20230203-1800/plugins/org.apache.commons.jxpath_1.3.0.jar)  and looking at our repo https://download.eclipse.org/eclipse/updates/4.27-I-builds/I20230203-1800/plugins/ it's 1.3.0 there.

**Comment by cdietrich** [comment]
But it’s no longer part of a feature as it was before
This slicer example worked before https://github.com/itemis/xtext-reference-projects/tree/master/domainmodel/2.30.0/org.eclipse.xtext.example.domainmodel.releng

**Comment by merks** [comment]
Yes, on the release train, this version is available (which is older but OSGi considers it newer) and the dependencies on it are like this:

![image](https://user-images.githubusercontent.com/208716/216756128-340af611-9e20-40b1-9aba-ed78e3969f1e.png)

As the platform moves away from including third party dependencies in features the slicer approach becomes less helpful.  But 3rd part bundle names have been changing a lot too lately and that's also less helpful when consumers must list them themselves...

**Comment by cdietrich** [comment]
https://github.com/eclipse-platform/eclipse.platform.ui/commit/f626d1e105179ac01312c204a53340526c764a9d
this seems to have removed the bundling into the feature

**Comment by merks** [comment]
Yes, that's why I said:
> As the platform moves away from including third party dependencies in features the slicer approach becomes less helpful.

This is an example of that move...

**Comment by merks** [comment]
Sorry about the hassle, but having worked actively to help the platform keep their 3rd party dependency up-to-date, I know it's really a significant PITA to include those dependencies in features, because then when the dependency's version changes the feature's qualifier needs to be force touched to ensure the qualifier in the next build, which is required because the including feature's contents change and hence the feature's version much change...
