### ISSUE TITLE
Retire source tarball generation

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.releng.aggregator#882]
From https://github.com/eclipse-platform/eclipse.platform.ui.tools/issues/31#issuecomment-1437122784

````
After the build repos are not clean so either it would have to be cleaned or even worse repos would have to be cloned again. This raise the question who needs the source tarball anymore? It was added by Red Hat and used for the Fedora/RHEL rpm builds which we no longer use so maybe no one uses them at all.

````

This would save around 10 min in the aggregator build.

https://user-images.githubusercontent.com/139910/220134849-79eed542-de29-4b15-b569-6eb9952e606b.png

cc @laeubi @akurtakov

**Comment by akurtakov** [comment]
I've sent a link to this pr to eclipse-dev so if someone still uses it has a chance to jump in.

**Comment by sravanlakkimsetti** [comment]
I could not create a build using the tar ball 
+100 from my side

**Comment by iloveeclipse** [comment]
We also never used that. Let remove it and simplify build.

**Comment by HannesWell** [comment]
Never used that as well.

**Comment by akurtakov** [comment]
Haven't checked it but if @sravanlakkimsetti couldn't build it out of the box I doubt that anyone can do it without major work. I'll be dropping this one for RC1.

**Comment by sravanlakkimsetti** [comment]
This one caused tests to fail. Tests are dependent one small tarball containing the scripts that is not getting built now.

**Comment by sravanlakkimsetti** [comment]
Will fix shortly and restart build

**Comment by akurtakov** [comment]
I'm eager to see how this relates to tests.

**Comment by sravanlakkimsetti** [comment]
There are two tar balls we are creating in the build source bundles stage. 
1. [eclipse-platform-sources-I20230220-1800.tar.xz](https://download.eclipse.org/eclipse/downloads/drops4/I20230220-1800/download.php?dropFile=eclipse-platform-sources-I20230220-1800.tar.xz)
2. [eclipse.platform.releng.aggregator-hash.zip](https://download.eclipse.org/eclipse/downloads/drops4/I20230220-1800/eclipse.platform.releng.aggregator-f192e41ef63b1b5f4f43d9d55a7b645ef797f052.zip)

te second one contains the test scripts required to test on different configurations. its a zip of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/production/testScripts. These scripts are used for run ant based tests.

**Comment by akurtakov** [comment]
> There are two tar balls we are creating in the build source bundles stage.
> 
>     1. [eclipse-platform-sources-I20230220-1800.tar.xz](https://download.eclipse.org/eclipse/downloads/drops4/I20230220-1800/download.php?dropFile=eclipse-platform-sources-I20230220-1800.tar.xz)
> 
>     2. [eclipse.platform.releng.aggregator-hash.zip](https://download.eclipse.org/eclipse/downloads/drops4/I20230220-1800/eclipse.platform.releng.aggregator-f192e41ef63b1b5f4f43d9d55a7b645ef797f052.zip)
> 
> 
> The first one should be retired.
> 
> The second one contains the test scripts required to test on different configurations. its a zip of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/production/testScripts. These scripts are used for run ant based tests.

Is there a reason to not put them in "eclipse-test-framework-*.zip" ?

**Comment by sravanlakkimsetti** [comment]
We should put them in the framework.

**Comment by HannesWell** [comment]
The very last part seems to be the removal of the `eclipse-platform-sources` Maven project:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/3154
