### ISSUE TITLE
Update build calendar for platform 4.28 release

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#915]

**Comment by MohananRahul** [comment]
https://calendar.google.com/calendar/u/0/r?cid=cHJmazI2ZmRtcHJ1MW1wdGxiMDZwMGpoNHNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

Fixes : Build Calendar updated

**Comment by SDawley** [comment]
I don't see the updates to the build calendar?

**Comment by sravanlakkimsetti** [comment]
@MohananRahul Looks like you updated your personal calendar. Can you please check whether the build calendar is updated?

**Comment by MohananRahul** [comment]
https://www.eclipse.org/eclipse/platform-releng/buildSchedule.html
Please check.

**Comment by sravanlakkimsetti** [comment]
This looks good. Closing now
