### ISSUE TITLE
POM and product version changes for 4.28 release

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#916]

**Comment by MohananRahul** [comment]
@laeubi Could you please help me on this task.

**Comment by laeubi** [comment]
@MohananRahul the first step would be this:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/903

after that is merged (@akurtakov @sravanlakkimsetti when is this usually done?), then go into a temp directory and do:

```
git clone https://github.com/eclipse-platform/eclipse.platform.releng.aggregator.git
cd eclipse.platform.releng.aggregator
git submodule update --init --recursive
git submodule foreach git clean -f -d -x
git submodule foreach git reset --hard HEAD
git clean -f -d -x
git reset --hard HEAD
git checkout master
git pull --recurse-submodules
git submodule update
mvn -U -ntp org.eclipse.tycho:tycho-versions-plugin:4.0.0-SNAPSHOT:set-version -DnewVersion=4.28.0-SNAPSHOT org.eclipse.tycho:tycho-versions-plugin:4.0.0-SNAPSHOT:set-parent-version -DnewParentVersion=4.28.0-SNAPSHOT
```

then you could create a PR by pushing the changes of the aggregator repo to your fork.

**Comment by akurtakov** [comment]
@laeubi Shouldn't  we rely on the automation rather than this manual work?

**Comment by akurtakov** [comment]
@laeubi What I have found missing in this repo is https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/1e80e87da36dbc85d48cdb406f2e4f58149bcd65/pom.xml#LL21C12-L21C22 being bumped to 4.28-SNAPSHOT ? Should I do it manually now?

**Comment by MohananRahul** [comment]
@laeubi 
Could you please advise me, getting following errors.

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/121536011/223111932-89a37b62-681c-424b-8b77-17733c31699c.png">
