### ISSUE TITLE
N&N Eclipse platform user guide is not updated.

### ISSUE THREAD

**Issue by MohananRahul** [eclipse-platform/eclipse.platform.releng.aggregator#995]
N&N Eclipse platform user guide is not updated its pointed to 4.25. Images are also not available.

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/121536011/228440801-11f4749a-dcad-48af-b595-458cd21127a5.png">

**Comment by jukzi** [comment]
@MohananRahul can you contribute a fix, please?

**Comment by MohananRahul** [comment]
yes @jukzi We are working on N&N Highlight for the release. This Issue also will be fixed.

**Comment by MohananRahul** [comment]
Fixed in https://github.com/eclipse-platform/eclipse.platform.common/pull/141 and https://github.com/eclipse-platform/eclipse.platform.common/pull/142
